apiVersion: v1
kind: Secret
metadata:
    name: openwebui
    namespace: home
stringData:
    KEY: ENC[AES256_GCM,data:7xg8OUEQ48HjmQaN3iMo6qI0wXaXrO3v/u/PzSAow9vZ/lRFK7eA3HyZlsKUGivnXJg9,iv:K3NbDfTB2oY0EqclnlV+Ir0OMYqsOOG/3N9Qvs6gEh0=,tag:oVZsUHEkN+ggEJGVSkH/aw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:VZdo5iHqnbZf7TeNFvy0syJhKHXYRI6gnQ==,iv:UvKDSyBHqI7IPvG7yq9fdVAx3OEZMKcjosAHdnt2f9E=,tag:EED+yjwzBfsVWeLk/SK8sg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:pGutAU2D5Myp,iv:9sdOHD8AvkA8D8RZeEHqgFF5+MlFguKubfap1Gp12oc=,tag:0rnhp8prQJ37unzeZzK8OA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:LkMlOhscRw61jgEUXMIXw450wLE/THUfWw==,iv:kCJqN37sfbqgslvfgRL85n/FbHOpWktk0OA6C0lbIV0=,tag:l3wg+1vxwRxBKXeyapLw8A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:iTAH8Pfv7fr4AYmTl2fogZi87pPYPjU433TT2aY3uAS4e235fvVpcymtdzblR2tNghmA6UqqoU1eZ60d9hqCqeEgc1FYXckDG5z5D4fBRpiG4t1eAKAs49SVxuaK25USnH53flC5,iv:xxzzEuUbUDtjPeEwMeZ525kndmfLTkqebIgpeZvPsUM=,tag:3uyiP0/C5z/DXK+mNafXnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySUtKWi9JVnpad1o0NGx0
            OEovWGdhOTdBbWpCQWx4ZkRRdVlNcnVHd1RBCkJhcG1ScjNNZHg3Y0dFN2FBa0pO
            aSt3UXJqS25wOWxFNnJzTXQ1R2M1amsKLS0tIHBXR2hpYURIMEhaNXo1bXJuNTda
            V0lxaUMvcjkvT29ldU1Hdi92ZjQrZ2MKoUhI89bQspYd6IVpSAnnvuVqx79ZBHQn
            8dWzlZAecZIm656PER3ARq/SHzU0/OGeKTJNr9FCGt15dDRTtyJ5xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T21:29:40Z"
    mac: ENC[AES256_GCM,data:XbSyIpzjBawyfqAaK705paX+mt1zY6jWzPzac0uapU5vI5xFs9TNvLFNLbCVMP2szOlAlC9PMLMwicBppM+UYKYo0FegxPSfuq4BXN15BbImVcjLMXdPMzic2Zo2LKvGBn35jtcUPUpD/HbOGKmzA37fvWTSJ6E3Jlb9/1vMLRs=,iv:CQFJVTdc4L5KrOKNTXSYejA4OFuEafBUPgBuH3V66mI=,tag:Rgm9Szf2zAsJsWSxTBs0Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
