apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ragapi-credentials
    namespace: home
stringData:
    postgres-password: ENC[AES256_GCM,data:TYhpdPYaWtIAIaKqD5a8FNZCL9SZNQtkLyE2OLUN12s=,iv:HTLik0BjU5IfIechyz3Jumy93CrcrMNikr+h7rQaems=,tag:cz5xVKFEiHcm8hY0nzOUaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQ0p3d2U0M28vVUNURG1n
            aysxMDVUNmU0WEkyeWlCNGo5cE93RytWbHc0CnBsNlY5STMwbVF1Y20waThEYmpN
            clVWbEp4R0phN25NVmJCN0Nkb0ZueEEKLS0tIFd2bktLR3RCbXRmMzhUbVQ4R252
            ZVdaa3ZEWTkwRFJIanFCWWY0UE9zemcKkd8TzI56uW9aPzBthlOsmSujLEGSuZFw
            +D4c+oIcK161z7qzu7/eAp3cF4pahSCjCThTq+A6I6Qry03ZMGtuTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T08:08:30Z"
    mac: ENC[AES256_GCM,data:L/T3V0UMnM1dioqzGLusjtbCWnjwXYzkUWFezrB+1pG/g+S/80oH8w80RXDtt7eaPdpeDaOkeogD/+CRFYgsmE8n3XR30d0kVV5ZbtyYeapxiJBWnqsel2m3xy07QalRw+pS7zUdadLD54jCPD1rYxg8M3eubgWfKKSuWAwC4sc=,iv:xiSvmgCXsuBdmoFXC/AMxfEDyR6feHD+D9HQUzEIYxA=,tag:oiFgecFMsstSLolpe6XTsg==,type:str]
    version: 3.13.3
