---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &appname smokeping
  namespace: utilities

spec:
  releaseName: *appname
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 4
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        type: deployment
        strategy: Recreate
        pod:
          nodeSelector:
            node-role.kubernetes.io/worker: "true"
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/smokeping
              tag: version-2.7.3-r5
              pullPolicy: Always
            env:
              TZ: ${TIMEZONE}

    persistence:
      config:
        type: emptyDir
        mountPath: /config
      data:
        existingClaim: smokeping-data-volume
        mountPath: /data

    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/address-pool: dev-infra
        ports:
          http:
            port: 80
        primary: true

    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: 'true'
          hajimari.io/visible-groups: 'administrators'
          hajimari.io/icon: wan
          hajimari.io/group: Utilities
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares:
            networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri ping.${SECRET_DEV_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: http
        tls:
          - hosts:
              - *uri
            secretName: *uri
