apiVersion: v1
kind: Secret
metadata:
    name: litellm-db
    namespace: home
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:H5KqrW8F+2Gtkk1eA5JBJeEVHt/tIwbcktRbr/4yE69YZ7mqSBckKaRoBVoB8BTfKx9BQgF7U5S8Nyfl1psKDyE6DdymPPbGSD/xSQ9ORaMGVA3k2okdFSdufuNbaQ==,iv:lqDdzXhdS8FAfUc/NscWW9A6NV/4t8nUU9IVjBhLP3E=,tag:S+8KebZj9UzqeXO9y61L4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OVZlV0FRNkRxaER4TWFy
            b0tKV2R0MHhUcnRXdTZKeDRnVFV4RjZZS1dVCjk5emh3aU9ydEJEenFxL0k0Y3lw
            VnhHZDAvNjF2TldoVnMySXVVREdYU1kKLS0tIEwyajc2L1ZPU2tMSXMzQ2FJUW5E
            amxkR1c2VGEzM1RlTERHWHJIeHhDS0UKpZz4Sa5CHy6yOthUoJ6v+kgqQI4RfDxd
            awPii511J2tdIXH6yVoM7lUUSsKSS79S1BHpktGz1bTIgEsMM6HEIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T18:46:03Z"
    mac: ENC[AES256_GCM,data:CXtIsRlIAzo847yNAlgTLlvTXrXRITp18c28xBNJYKYFP0tL46PS6+6a/l3pGufgq70lP6XH704oVWcdYjlHcGvs53hmFSCR5z35m0yRJgcXA0UF5IRgEM/kv/MhRk69F28ba3Cna/IbHrF3X2b617noCo9Dp+ui/4FlG5naTTk=,iv:cTMmvMaBiST22jkFQClp1A9anZJHIdsrQvMsUpcEvpg=,tag:1EvhJq/lcAEYb1ekwtgd5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
