apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    PROXY_ADMIN_ID: ENC[AES256_GCM,data:Q7JRt1M=,iv:thj3j8pCpJxyBb8jtIZON3JutPk6vUxC3GTHwmNAMBc=,tag:jYJ35Z+GhispFP53IjnpTg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:EUcp01R7hA==,iv:YZIyjhQfzwt54bZwyEnwObcAZVjab4XMB4FHvxeiI+s=,tag:cxM0Fb/SwUinUJ2SSkxbfw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:su2GjXqNUg==,iv:PgJWjO6k8J1NP3dc3tPUs37hHXrPRlWxtGhMQQZwtyc=,tag:4qLwnpjPa60Jtox3Xbn7Nw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:YMAzZuzfxtk1e/4DpVQkgRAePw==,iv:EFEEHKFv6xOALyx+CB2ejjjKpsIxyFCYMSeWIvD+EzY=,tag:dcKid4aOEQVDjtYRBDQ4lg==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:thD4usLwwUcd813TJslg0NFretavOwJCnfVsee8a7GS96CXmcEWXYU2YhyyVtb2jieIby4mKWYydbP4GYMcOWKnh/g==,iv:fzzmf5gQ/Y0ShCoVwo6ppyhnNtgKt6I8qs7+N/Vxoik=,tag:hPmfK77kwcLSR3KX1rUirQ==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:MS/2YQvTWZFWdBjdVkejmFhr2aKPFoFVHyznGSEzzkV/7FxzIJLPb4QBi8ORLqbadQWpUxcjH3kgAofUtARCNUMFSw==,iv:A4XVlnAaP7i/QnHtAytkC3LRp2ACA28l4RU9lckuh9Y=,tag:ou5ls7WNv65v5ABxPCkAwQ==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:VltiHhDbHg==,iv:OgWNFoqdItACITSJdsgTAY8lF1Ko7Gh9mrIgaE0xhCU=,tag:tJ/ssFUJF8tmJqkenVjXfg==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:wQh3RRaqDsks,iv:74EsxaEsbhFQg8mNwUlLwFTg5frbYmI1LoFHjZSqxBo=,tag:rc02EHfI8pIMfdVt3zjv0g==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:X89J/JOfjsHcUJoT4rlZWHC274bCwvxQGhkH/ERdKD66rSEDGiqcE3HOi2pr4RrIZXviyHi7X2zYLrtefdKdju9t2EbTr1afPkAFUu7eR6KKms3x6gpAKZZvV2yFKCYSeRmWH1LuJeYUaIJOkBQ9mTkyCRk8MCJXO8VXANco46yzPEbcrMOY6d64diJpodfQL5fN0NRl8DXAS92OahNOdHIpLRw=,iv:dP4lpt0Yz7iYLj0YfcqsXv6JVxcgTiMU9x/8aTGLD+M=,tag:YzTrJaWqxY7uWoaVkBbyWw==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:o5hxXEILn3WjpgVsTAnPzn6bUrEJxZ+7LC/DpVQ5HSq1Lcs=,iv:4SskVe27w9WhE1ElBmzTJNNB4HAD33vGBQJPb2DY9xk=,tag:yBK9JcK19CoPtTXuiTUlbA==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:PLaZtVNLbD5RtUB9uJpz34M6EYa9M3xUpNDfk6Ujd5c2Yi+xL0Rq,iv:m8vjSR8Ul9S2ri76nn9QCLPlMw7urYsaEIkfKUvyqyI=,tag:UZsE0a9SIZzwMVe/PM9eeA==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:hI4uWQKRGZyRyYngPQu3MZU=,iv:VPpVGUWGcFFbWF1RweGzKm3P0S88OuW2oq/urj7UdH0=,tag:UNOG7mxhT4ju6pLYXPcpCg==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:migNOXCvYgFJ586Z5sxXZ5/tLYE=,iv:dkXszjeulQ0mBrqOOqOozGGnK7u0SeElfGOhZAKeZmI=,tag:aHJ6ka9UACyDtH38gHn/cg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iqQ7JInHGt6hn3L1z4KIAEqQsZ6xrbnz4ah85wKcDX5+oObwRDntrA==,iv:enBge0sy/M9+4tMGfzpUVWC19JClvWcZ7uWItIQ83ns=,tag:XpwFlrZX7aleN6qWOlXDsQ==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:fgIrJRAq6dRS,iv:VX0934j0OlvwcbzNgFcc1oggRZSgq1ZSrvEDM8Hchgo=,tag:Af61GwS/lem1Z5+YNnXHYg==,type:str]
    drop_params: ENC[AES256_GCM,data:JWOOaQ==,iv:WjQVTdSySniksAnKWlxWIq+UT2/JnTBQtNFWZaTDEcw=,tag:rzFyVMjPXUbLWNibRVUCjg==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:SMEZvx8VxXrtvWWA6GxbP7Kl+fvjPAxxBFOnMaQF1Q==,iv:YTEYBpUXJbmVSCqeP/EwkNLKZHiabTHotBgQYm0RZ8M=,tag:hY3j1um417ci+swSjvNmtA==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:NYQbjVN/aqfg/5Glm4LLB1q2tkrrxOWQ1SVV7FvP4KW/Y0zx9PhYfc0ViXTQlFxLLA==,iv:L+7Cegf4wY8X4kRyim2e+gpYJmsXHlUK1d6iXRDtVR4=,tag:gCRSAWTxgiE87coBmTPGCg==,type:str]
    #ENC[AES256_GCM,data:+83zMqfkOpjGS7NHapVMajDybGkRIdLg/Ns=,iv:fgrvA7eCvKvxT3X+rTEtrV4ecRaPVs3KyDUUBhUT2jY=,tag:9J+MkL/4UNYcdqhacnPMow==,type:comment]
    #ENC[AES256_GCM,data:qRIgGvLk8CO482KDs3v1SF0tU6QIS/Se0pNjhginc7NvulmJbUMaoK7TRjV2HRI=,iv:MUa7r82iZL1x5SBwUcfusEoBYIDmZZrlFXOZPkG6QkY=,tag:TpIaEEyyldL8O6JQJ4k8sg==,type:comment]
    #ENC[AES256_GCM,data:s3qYCllUmbamg1NRCzNcuV5vIrXnaqt4CI6V+YaSdF8QBODJSD4rSvICt/NbkzeUpEngnUA=,iv:NzPQm38qurwgt4FB9qOhgsqPDCX9GB4U8pGqRzCb/Jw=,tag:ACwXG3J19AvpRr7Xszd2oQ==,type:comment]
    #ENC[AES256_GCM,data:DWMN1HvtF7+N6buYzHExbCZM14zi77XloLM=,iv:2Q0k05bjeYdcfJDOu22VrY7t77faYSgZfziEOw0/nFM=,tag:pKrBBS15N/c5tZYxNZGk1Q==,type:comment]
    #ENC[AES256_GCM,data:rO/3bXSzgxAKfMd/J9eZc700s6hOdQewsQbbCVkA/Dz/lYhklg6/yE5m9sfX2oSlblXwQ3d68DjaqBnm,iv:TxBm1+L8D81xtusGeTOlbLN4M5FYFtju8nKjIkplSXM=,tag:GxUwyyQlavQLTR8mTQiO6w==,type:comment]
    #ENC[AES256_GCM,data:NnuI/LwthtnV0/ncO7XFudQr2n6nZFxDK/54zVvYw+6vaS0ptz/BHkFEtzOTsNhAO/h6ly3lI6MLq85FyfeX5hni1UFKm7vtomc/LYWKZGlBQ2aBMAizpgdlFTo=,iv:/T8jNMKgmkNr4DTh4OiVgdce/MCJ7AvMJLkPCRKE2Wc=,tag:fA7uSTHj2xWH8c5a4NnsaQ==,type:comment]
    #ENC[AES256_GCM,data:ikus0ItZ5X5wD72Pc1lwrDtqUMbMtD+J037mmNmCLZRKyFIBizVpoAqJvTLDg+JUyodmLOY7HPduGAPmMi/SN4d74IzG5LI7jGX38g==,iv:xP46sbxOtx0u0uqW10dN50GwEWwPPOeSfAjFYWwoo4w=,tag:2AS4GKS1QQrzxU741yUOBg==,type:comment]
    #ENC[AES256_GCM,data:tO5RqDHhuJKw22ijoe54dcbl/BHIBfAe+8PCo3H+ofGjcKxyQ4Lz8/DTMdLpKdEG7YrkDW1MCUSjiq83K8zAPF/tLKus1g9sWUrT8IsyVXS1vw==,iv:QdMr7dZWLZLebIoAce8+i+S80gT1BkRY1FCQTPxrIAk=,tag:voZSEdbROuLbb85UcRsz0w==,type:comment]
    #ENC[AES256_GCM,data:Nz6SA7V6uvcD03EwdMWEPZ76FfsC5akf73DlUbV0BiSL,iv:OdDQCjC7aWi8UOzAtu0iAOSZkM5soUMlz+h2vRTIxic=,tag:JIAlPgLB2mrs1SDQwzGwNA==,type:comment]
    #ENC[AES256_GCM,data:eYVwvQqn77n6WYhNTWztkYuk5DZHcX/GTL4NAJs8LBVKU5zDuCi2gWV/wdpO8u+sjeanGDak2cQbHXZUl+rHXPGQXgkwn8NfAb1r3NfSJU7bUfDkEEY=,iv:rTqIqTVlzEUCa0KnKiurMZeKGfQ0EyuikLlqyiHszQg=,tag:1gucmX15BnhCmezph6XauA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZ0FaQUU0c2lJbU1mcVlG
            VWpTVFg1WnQvLy9BaDVFMENxNWsrVGs2aWlzCjZPUUYwUWIwa040aThLWVllNVJ2
            SGRySFJFQnR6TkNvRm9FUEdqQXhtbGsKLS0tIE5ZQkROUmlOSUkxN25KV0FRQnNF
            dkphMDhnVFF1VTd4ZmxjeTZ4aXJVaHcKEzwwKT9Wy0s96PqEWjP4GMHfOLPgHkDi
            mMcVIhChwU67+cYB03cTIaixww0P5s6RvPVT40F+VhLHAyWAQZVSSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T05:52:47Z"
    mac: ENC[AES256_GCM,data:Kw/xV3TIoQ02p6Soh75WYG2sLQRVlk/CgN7jW9KIw8jya8xB4HiNGv40sNlLVK9xL6A82JOUeocl6x0hI9RfuPAPJWU43rWEjOb5aHZmLv6J4cdpjdO6LRad1rGGOf4h5v6npm4JpTpzX/7lHX/a0yg46GZ31i/GY0Fl4xnQzi4=,iv:yKNF/tYmKrYVDADiwaGyQtbAzY5bTjx87+eJe9RLcjA=,tag:fAFOEr3nNnMeqOxSD3cdaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
