apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: home
stringData:
    PROXY_ADMIN_ID: ENC[AES256_GCM,data:GjEbbEw=,iv:9tp/fEsj44aVDo/TD5JB7rylgDxxyCFf7KLcX7zd8dw=,tag:M/nrHB4XG5onZEqsznc4xw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Os25x9TsmQ==,iv:BYk9/xMolNV9o74pwkS5KGf/+dts2DNLZDMY3NW2W2g=,tag:Y8xoe5T+E/BT3hgZhmbSAA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Wr459LZhVQ==,iv:lfplOMcYu8pP2HqAiGr4Jy2FKzzmHL5QutXIwS7Whso=,tag:QS3g15NDti2A4VHoddHtWA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dF0meJ0iDEsTrDVBtvXd72uGvg==,iv:okizmSkPHnC8bhp82Oyyt+why2p3tMVi5JL4+sZ36K0=,tag:W0pjRrHrN2rJEwWeLYYtdQ==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:1Ltbvmeoqud9PDLqAldASSUMMIZ2uZV0M/MuzlnEiE0VBHIJeUuROsQfMli7gA63jycL7w7ZUEaljHzrMKX2e4h6Mw==,iv:hXCXezdJ3QYBU3bJqfeKvMrLGLZpfdh+xRXvACxMUqE=,tag:9ul+do/Q1wpO/ENx3R3V9g==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:0M5mVx3Fn1JZlwIsVzaB4ErRuKIFbru/Sch1+0nZiFW7YZauAEAMJQoDCG2C9YAGs/Ql+HqP/v8VPsNGF6HDAGctsQ==,iv:cZ1xrxtJGk2te4ycq2LapdtZ2JNr9U7pmfBBea/fEKM=,tag:U7tYyGKIKC2+zFnfiXrVuQ==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:QMRoZahysg==,iv:XJWb41BBnX/AfkX2VldNlck7jLiHP+Zi2+UVU27suA8=,tag:BqnhZ3y1qX2dR7CrBQceQQ==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:96gJmNI3hkVG,iv:NNv0rsWhDFNapwj7frYz9pmWGShIlNd0Y/qFrZ08vcM=,tag:dWDK7sG32Lozu4M5yaQU8g==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:hJKgyXjmwXU7xzkbLr9l7w4dRu5iOG2YP5QDfVYlo0J3qTa2E3+d4uy9/s4fo9eD3X1Rl3YNbuAMC1foEBpCEYwq4N0ZwJJ5pORq0EIR3HTn6Irv8VP4K6vhujH81gFmvy8wc+aaofyScxTfsPQLpYfRDle7AuQLofFI6ErwDbIh9dc5tUZNFR6kY9eHVBen3kBX48dtaJqYIY4lHAUe/M1HI3I=,iv:14rIJEQQtzE3mBswCFT2U/mdJkxGSrP4AzgaSw4RLqk=,tag:3L0LJPOvmhNAo7zWG60Ylw==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:w7NzoEhh4I4vWGk3UfeHEsEoFq3Pi7plI1eI25ApDpGxiC8=,iv:WuJkLvVSuNhcs/mVFMGxQw/y7eZHuKRNqFKVLEyc+FE=,tag:hQCVB+OMN30nRYDX1hqUPg==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:7i8CSNU2fju8wLQIvNScB4waArmU/0ePRs3pYSy4eCQsO8RShjhP,iv:TDxP0VZcwPfAywmBlZZcKS+6RPla5iYXJoU4ie0+3xQ=,tag:PIaW1IXPC/RIH+tWL0q1pQ==,type:str]
    GOOGLE_CSE_ID: ENC[AES256_GCM,data:GAvQfWxHJV/k4k0fcbyYtaQ=,iv:WmCGDXucXFsn02gwg+LfYIE0Aa8ig1Los95cGPwFUi0=,tag:C9xeRAV4x8Nbol6FFPP7cQ==,type:str]
    LOCALAI_API_KEY: null
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:uvOUrz9ugkTLFOFZRUaAezChEKU=,iv:kF93mb78VYtPZBSf9JlETE54o8K8cXFsKLWoTjz9Dws=,tag:OUk8EWNOZ37GNWiCsI8nHA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AiCcDW4RnrOWtura9Q+uOVioKWz0+0BcveL0gkzXjKrJulUbDiUiBQ==,iv:sW4Tj7cnZgcgzkpVLCPMsJP/bimEp7vNMvHAd94Alkk=,tag:1Svau6AurnRwPfVXAxnadA==,type:str]
    AWS_REGION_NAME: ENC[AES256_GCM,data:CMX63RtW8PIh,iv:ZsOf4implu40yDJu1lINLmbeG1l1870IAdSqQsKhwm8=,tag:KmjrqyimYSTxXcjjlyyS4w==,type:str]
    drop_params: ENC[AES256_GCM,data:/dDfDA==,iv:SP97fJR+NKGlUyP12rmDeutQ+UIW4ggguX7UrsxAKD4=,tag:lJOfBVFecsNMXELm+fIieg==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:whJwYAtTv9wKT5vDR0mFvNz54Xi4YRAb4hRrGFSStg==,iv:4rEi6evNXQFX1gTWof5cMC+utrd9Hx39af431199qaI=,tag:MudR91uMh4QzDGntInVoVg==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:j5dIqsdhDVCW5zR9Dc5RhV6qguajZYOnNY0jGWtqK0UOeObmx0KaEl1DMEQb+QWZEw==,iv:o7K3w9F83jPAYUWMZscKjzk3iksb4T6KgUNtpZCMWig=,tag:JnXZC/VjhYPQv0zYoA6KxQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:DrgVsFdQnE9D1G6mnNDmXPun+wRKTzokmo5yIh7xwxBj4TKvy+vPu+4OXgAKb1Rd969gg+41Nliu8BDUcqu3BJY1mnaxOYbYeZ8h79helLEw9Z1Ifbl8a4jMqsBRnw==,iv:2p6QyJG9QMRjihOMJz6/acL0rTbN4zNvLYkpH4JiABA=,tag:4ByRagKN2fqVo6KTT+8yYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUFQ3UVlWQTIzdW5zL29B
            NEw3K0FaMjZic0FWZkRUZjVkeCtrM01rdTFNCkdDVlFlWlFIYm5PMlMycXlld0hT
            WmMwOFZiTmdBKytmeGhFVzBueWNWMTQKLS0tIDFwUnJLcktpUStOSVoxNnR0Z2ZH
            NlFLL01UeXlBVzlIb1F1cS9vVElzUUkKMj/Pt65PkU7Vq9YjEvTbc3op3B8ysE/n
            aGOa2gSfG635N8XN9CqTClkRpexixyYtCGWWczYYFTP9zTsEbcOhGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T18:53:45Z"
    mac: ENC[AES256_GCM,data:aw8UuXkAvR3azLhFjRnm0mfbalL6aVKIx8ifwdhgscDub3fxZH809ZI7ZaoG0qwEcTMpT4vGWIu/bbNrJ6YQNI4y4E/ITLtdxDCrhaO3c3MJrSLU9ONHM+C0GokdLQ7aNtFfyLD5ly12FnTUc6JOMYaOx/Z7tkEVmNHpwGIj+pg=,iv:BtHEV1cB7Z2qifltfQv7CCEHaTQCJRf+gr4mRFv/L24=,tag:TxWjSCGoR1mKiVajlT6KMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
