---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./kubelet-csr-approver/ks.yaml
  - ./spegel/ks.yaml


  ## My services
  #- ./intel-device-plugin/ks.yaml
  #- ./node-feature-discovery/ks.yaml
  #- ./nvidia-gpu-operator/ks.yaml
  - ./nvidia-device-plugin/ks.yaml
