apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: redis-secret
    namespace: databases
stringData:
    host: ENC[AES256_GCM,data:pvP9P8HYZLvMT/5GDEU15cRoN8l54+iB4OddBsvXp5x75MPwfuzlqTk=,iv:B1MrPV1Rr/MBJnufKhdXIBil41CsHV6wQq5xFfoGTyA=,tag:c9hIcADetXmRxUOjsVoEOA==,type:str]
    port: ENC[AES256_GCM,data:7ITfbQ==,iv:6+lemjQVint/dZZ3LS7ZpZ6fc/a//X+3NKLPU0OayF8=,tag:E+ELwqFhyOBcf/uPEMxW1A==,type:str]
    password: ENC[AES256_GCM,data:THSFtiKzfkhKCKOGPU1E5F9rcAgP8Ze9,iv:khVGP/BedGeUzgtUp4qBu7tc/3jUs8n1fS0RNDJhK4I=,tag:VJf1GXjjmtGXHwJbhnRYhg==,type:str]
    connstr: ENC[AES256_GCM,data:uFfU/+Nz6XdLAAdvKnC5DpTjSIGKxXm+yKMPOCgi1Vf7b0AFZakW/l5uRWNuViEtwja05zU5sbagn37cMrvr+nEFNWw9aimc,iv:KZYd7HpDIrW4uqaCWv2SivydZIpAlMDCS45KvXdSNhg=,tag:cbwpQw+ujhXwEQE7Y2ZwaA==,type:str]
    #ENC[AES256_GCM,data:6HCxobxxxsbwlkk1q3Ixdv1SnvGEZd3T6FndsN7evYPDqLo7WKQzLCYxnOR4MB2Gj4f/nPjMvXktYG41CFvhbagrJeEFMo8s5PEwAMkD9Xva3XAHNA+nh/2SonIpudN6z5VtYRSkPI7mNE0vjbBtI1p/+WvsbM99IhCu8MH7LAYfK647kcePDZUG0T2hpUzJJ1NafvEh2aFQdC6CmTKodpKXthBOZg9aSV4pipEsMkXZ8XFnhUzE5NC1pZjtmPlHV5TkYWiZDlwT9cGTT6SgFXcKNvFS9KiavSLYOyXxqGru4hvNILiBM5LZ1HLWQgemyYNuNdibfGNKSbFtOVtQ/g==,iv:fo12rPWR28gtdWKqxKZKTOtih5lxO8SekI2BOaCh86k=,tag:SLejnYrdnlhT4jFyOUju3Q==,type:comment]
    #ENC[AES256_GCM,data:eJUJUryVP1yCN+CfcfVK1fCDD6rdTH7Y/xXiGLvTmtYSKDnHsiLBQYamCJn1pm5FB6axm/QlSSF+SY6XKEtxgbBo8tyFGZIAIag8GFzjmMAKDzHU9MIARrffP8/GKN9xp3e1hIhJQqCx0SS9qfJ4k47Yby6v3N14T9Q6A7xXhIe8LSYkQscMcPUVh+e2DitV0+jJoxo6muU6A0AuukSfopocsIAq/SbCAR16+5y8R/qD2QVeTsIODg==,iv:cdBI3x9W8bWS3Lse2eJKdV17d49Y4obT8uP8Sj8S3nw=,tag:qZN7rQUA/z9VanWrBbIOPQ==,type:comment]
    ioredis_sentinel: ENC[AES256_GCM,data:w5DS72p3HUXDpYVTrY7CIzs/GfMiY/3+cm4Yv25t+ah6fFALrJPEAclDsP2CG0oXtWfCBXjz2kIAO4YlwnoEMivb8FSBkCE4K4Q3xFlCxwiiC6Y9uLvhh50fQOhazqMnNP/VViSo6FAeOI+tvo4cR1g11fsDo2FrmXT97kuOgS6EBVrs+COhzPfW,iv:aoD0POHEQpq13FtlE7SqDUf5cwc7o6Y+Ji7DUGseujc=,tag:2cBkOOSplIxf0oE5gNv+Yw==,type:str]
    #ENC[AES256_GCM,data:/HkbFeMkBFURyteUsPgICAtu/IwQcoZo0hPKVVDOZxIUhlFFedwMVLu4UmDxBuqyn2tPj0P0pD8aW3zZzhiqxemozzapb5UmLuamitBR7fwD16FSE+p7uGdEMIQEMwRmPFhyci9Ng60XRzA7GrNk,iv:NSmRM3354YOE9YkFKr+Acub8ZrTijZFR8+Osu1HOb5c=,tag:PQOesN/T5fk43VNHFi25XA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbE9nRThSenhJald0NFdZ
            OWRoSlg1bFhteEZKa0VnQkhLclRxY25yVlJZCmlFeGVBWGFDU0ZxODFTWkdyUVFz
            UkRvV1FDSHVkY3ZneEk4d0JoR291c0kKLS0tIEJqYUpabHJuaGRTSHJQVmJVSktL
            bkN6UlR0bWZoVzFlUXN5ZGtWSU9ObTAKsvCkmlEVI2t+Iv0/fW7g1TJcL+1M5uCN
            0MtedZ72KIQFOOvUf057Z0IxDBR2xXz/yFgPw1JE9+BIapyLCKri6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-29T19:36:26Z"
    mac: ENC[AES256_GCM,data:d+9g+/ScXWUYHG2PkW20ZLaZhdH7y+XTL9mjoz+ZX6EPtvlgQYNNCiBzQRGuZvqiHheJlY8ji+Gn0N02x22bjjvIwfSjN9cacHRGF1lIVexPtXNHEM9THGvf/0An/iR7c+67u2RPsiFa4FwLceyPtTW43S5+46NAJQdM6zG9RhY=,iv:/hH1Z5ATHq3COty4FHLtUnbuQXF5eJVaJrsBBAx+zD4=,tag:TObuMEBEgya13XP9kFgxcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
