apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: redis-secret
    namespace: databases
stringData:
    host: ENC[AES256_GCM,data:zUs/l+hI/F9GQrDnhFeTaAuEkK9WxjWwsuBq8Pce/MSZ2YHHGpdI0Eg=,iv:ry/m0aXTvoHOBsgXMC4EP/2K6Rv6zQzZxQ7Ikg1zwvM=,tag:hqfaV850AxTLz5OK8jA9bw==,type:str]
    port: ENC[AES256_GCM,data:jjEYXw==,iv:xod2b88Mxtb9GjSX/MHY5R21q1QkyCthyv6dECBafNA=,tag:MbLerU5WAyrhDBOaNwn2Gg==,type:str]
    password: ENC[AES256_GCM,data:WxYelbPU+zauW54WvVaejR9MVxHzHL6k,iv:ft6LpHJgAQsHkAvYNvqZLJBzng5pIzmkRN+nzotld1k=,tag:1veTkF3PyNXhEekLfSwHew==,type:str]
    connstr: ENC[AES256_GCM,data:drT+NJCumoN9tm0wNWfwln8JWR24IrfFyxpsOKCh/U5XKRwi1rFjuqKxmEnIjbWvaqybq/aglkVbph9/kyQ8UKjmWTHGfeqL,iv:TWfVeDdbF6hqeYcrGd2dJe2f4erg7rU1cnHlneUkoUo=,tag:ljV/bBZF2RQSfQKH9xeouA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdlp2UVdQMjJnNWVwNU90
            N2t6VHZ0NW9LNnZlQ3B4anYvREp0WE5xdXhBCndNcjh3R3ErcDcrdGNoK21QWGNU
            bHBKMVpmTjgvUFh1TmdyVlNHaVZwVjQKLS0tIEVMaGpZbzd3Q2lYMU00dE5PbTZ5
            ajZDSE9yU3BjbkE3L2JKTWNnSTIwclUKvFkbuT6c6FzUmYBYm69ExYLZJERYpMMT
            5kCmKwCRh0VHJAZZ7gnDiUBIFrL/32w+yItKIK+kQmWy8BzRjzqvCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T16:59:31Z"
    mac: ENC[AES256_GCM,data:7ULL6W7VxzXtHKkNk2MlYSag4UjOOV93iQktYiARI5e3+Ld2sliC7PpT5D7rlyspDs4rvLO/Qtupts7GX0WYHbVwK0R0QsGCfPFL8kUeKPAAbJF8Kf4qqoBC3Ssv8x0pMjwZzI6TaUrpWJhZpcs/uT9xnapP/7EPPUhxHg399Iw=,iv:qwZ6xucNPbGDZufRhoq2SFbiE6Q/WZmX6hI9h2u478M=,tag:IhxZF/uBfu8DxEAI+jj09A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
