apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: redis-secret
    namespace: databases
stringData:
    host: ENC[AES256_GCM,data:naZoZpyNwuxWdYilWUBJcfw0bs5Wrub3G2PUpiG1scobHkWxtdKWhio=,iv:Ow5G5FKVNjF54LuUL/dS+hDFU0WzfwcHuUIw/E7Flbw=,tag:CZ/wdA4P7fR4Xc4Ytsg8aw==,type:str]
    port: ENC[AES256_GCM,data:5vo3+Q==,iv:hY01k/wBROI3W3CZhAZauc/o+f++iXD8SPnbZsxMyCY=,tag:2KJnGccZZRHFwye/CVw4Lg==,type:str]
    password: ENC[AES256_GCM,data:uh6dtuu4yAhneBKCAOf/P46za2CG2X+s,iv:M2XvtrK8yqNs8j715X3hcFFZVUGK/ut6r5p5qlOr4mk=,tag:NX4y7zHynVmzD82ML3x59w==,type:str]
    connstr: ENC[AES256_GCM,data:KeG4cDF6fWAWdpeRcHLm7DtjzEd1M8ZyYlVSA+vjIc2S6N57oyM0IJZKWYoQUof/reAbdGIrLI2f/M9O5d2ycmWKq3UozfMm,iv:vmMaHiWDOzCXHUdSAGMiw7dFZgKqcb7dbY7NLDYmLwM=,tag:/YKDZ09LP6tb+THB70AQyw==,type:str]
    ioredis_sentinel: ENC[AES256_GCM,data:BbKRWkBfHgn+D4SWYX3+R83ARPTNhIcZulcofvRZ/TzLz1PGFaxNp9Gz8m5rLkE1P5U6/MaT75zYu6lRFiBl/KNnujPs18YXzlqMZjMiPtG7hjHd5+ROZCdNUcHXD/Q90dhh14BjQUuEaR5AtOKaCbazmsK6/gdTt+YYm/M6Sj81/1u5pfZc2Hup72qyP9HNjtl3ui8dd5ZFjzmK7V9FIQ1pi/ZAUFOQRjw5Q1tvm9SSgXGd5tt1gdoco135C1hBLgjV8ZrhYV6xUmH0wirP/qeMsHU3b3rJ3rz5jxYe9TMaJi03PRtOnuYQwS91/R0732skRtpOD50iCHurO9APvw3Sx7LchsRH4BntN0IGe7OOUfKxwhAPbduIwi5yDrmywHJmWpnlcseQoAQ0oTvxEk/fxPHLG5DdT7VZ/N8VFgJzlDxXgMTwGy03yAqGbhDWsPrAqeQglk4Uat4wjlN/gzLqS5+2iKcTaZ26N9ASZSiXR3qFMu61Uv+W5gvRXy+s1NHIB57ZX0D5+ufrb7lKR/puCC0kMw==,iv:KF+SlAoXmuKCQ2juRQts1ZAR0RfnINnrpUCoykjzFu8=,tag:ILbWelDDCDXuOpCa6rWL/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZjVQSVE5WUREb21mWEVW
            WGlNTm9kbEF4elFhMDBuY0tYakYzZGd6WUFzCldJR0pvWFJuTXRzbVV4K2hQOHhl
            eW91UE5iak01MEpwa3hFU05SRXFZazgKLS0tIGpPczZhakVaUmwyUHJNbU1wOFFw
            aEFVcDFkQWJKdWY5TGk3WEVMS0VTU0kKUdjFzjsr5bzKIIz5lUc/e2nOMdbhVO++
            yljTv/Kr9g7wezfIQxcC4IycTzuPSwAumzOfUExPzvxPs+ggmd138A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T06:34:52Z"
    mac: ENC[AES256_GCM,data:onA2GBZfv6qfJVhSFYozKSzV+gwkTuOXUnHrNqSvkygHdp7xaLRXOfiDPM/xvGvSuLrrEyp6gIlgtrsHYUsGjbcgMcr9um7dYPX74wXWk6m9JwLSejkrBsY1agSTDe4D/VhVobeggIQM9WTz6ac5A9dzp1oMhvl6dVqinORtQ84=,iv:6H4yejIYVvECQ6omkQxfWmXiqgRhNqP38Q/9+tebHy0=,tag:ODC78IrYwa7eJ6GlQhO6lA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
