---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: databases
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
    - name: sentinel
      port: 26379
      targetPort: 26379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  namespace: databases
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
spec:
  type: ExternalName
  externalName: redis-0.redis-headless.databases.svc.cluster.local
