---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-broken-image
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      test-broken-image:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/library/nginx
              tag: latest
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
    service:
      app:
        controller: test-broken-image
        ports:
          http:
            port: 80
