apiVersion: v1
kind: Pod
metadata:
  name: test-broken-image
  namespace: default
  labels:
    run: test-broken-image
spec:
  containers:
  - name: test-broken-image
    image: alpine:latest
    args:
    - /bin/sh
    - -c
    - sleep 3600
  restartPolicy: Never
