apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: frigate-secret
    namespace: home
stringData:
    FRIGATE_MQTT_USER: ENC[AES256_GCM,data:Xch00A==,iv:JQRu6Mqfcg5+u8hYHVpaeepLNsGrc3N036kED2pT91U=,tag:2US/BSrmZpbMzaF0RwDmFA==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:AVn9Lplq,iv:OvBsIjOlx+7jKT5Ak37RqTD8ZqdEKsx2bkDUV8l0AwA=,tag:c+3ndkv2WrWnefaZ4V0LpA==,type:str]
    FRIGATE_FRONTDOOR_PASSWORRD: ENC[AES256_GCM,data:BcajL7PlOHkF4zXizFQC,iv:sL5LHnTIHA0fpO3o51Thh2opWIVWSan1xiHZV5xpQo8=,tag:oT0tOogE2wSx2dCT8f4qEA==,type:str]
    FRIGATE_REOLINK_E1_PRO_PASSWORRD: ENC[AES256_GCM,data:zzGN4bGjfABKPi/VLZv1,iv:uFNJ7DbVPhdhwNFs4Gfz0Zqa0lGZEQwan9vlVZXBcKY=,tag:946LCwPc5RhFozWPu2bjgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaFlqRGdiaWZVQm1JckJi
            a1l6MDhRRFE4K09LMENOaFlUb2xUcnRHSEFRCmxpMWpqc1RpdWdSWU9yYlNHaVp3
            NS9kY1JTOXZwVDRrQi9Ba1EwQ0VUSzgKLS0tIEdkaTVhakRwclRyZ0lDd1FVZDlh
            bU5aL002d0pldUFGeW9CSHZpUVNMMmMKazZqizM9Ct7RXvSjl/lMjR5Zpx6OM1bB
            scv6RRSE7ZN1v1W/wqBo51+62cpd0YV3QygFzxn3DVhZtslFkLqrFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T05:11:13Z"
    mac: ENC[AES256_GCM,data:vJ1vRDt7/22xmsQCDkfFYuYeo6CbQbSIK5FiNkq/D344H148Tfp9hFXWbD/2N4cKTc6p5OuXVbH5jsm66dFGpFl0tvaMVcXFnxe1VMoA6VNpjnGi9W3jd2xQWz05Qivl51ieuUxv8bp3M+Xro1xSexN3t8cNS4hKW4dhoTyOkU0=,iv:YPFyTSMRindMYyHQEcd3smbNHy8FTMaTB7IKuvwgRUw=,tag:ihpbZv8z2tFep6UsWWE5QQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
