---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1q03s8dzt0u9tqw0vzy7a3etx5dfzxqql74fg2lfunkj235hn43wsutkm98"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1q03s8dzt0u9tqw0vzy7a3etx5dfzxqql74fg2lfunkj235hn43wsutkm98"
