extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    min-spaces-from-content: 1
  trailing-spaces: enable
  key-duplicates: enable
  empty-lines:
    max: 2
  comments-indentation: enable
