apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: may-i-please
    namespace: fission
stringData:
    SERIES_NAME: ENC[AES256_GCM,data:8oxNftTAB1t377NljrM3lYQL52Z1Z83rx+t3B0GvUWKfJ52xTaTiiA==,iv:8AM3C4JZ2drUWeUNZMW4IRysmrCNz8X5cr3SpvoWPH0=,tag:k1Q19Wt4F/sIMORKPPXMzg==,type:str]
    VIOLET_URL: ENC[AES256_GCM,data:IgqJtXmVYjRwbSifjeKm/L5RD5Ou24nMLJ6o2/mjqQA8jpJezVs/ZXVPPtxECbpCqWSa7bZESh7308P4HqX68eijpdlbiti+,iv:+rA0laD7bOgneN16/M5uOFSP+hmpbQlwy9nW2frrE/E=,tag:t8qwb/b1cv+hL6r8umKDuQ==,type:str]
    KOMGA_API_URL: ENC[AES256_GCM,data:8BlCPZF7l4kris8H37xuMMStb/tTMOvmKEVZbAoNn+iqOqeQTqHAlIc=,iv:Qvcx+zy2YcKG7MO0vGzpOcLtr8+XFjTJfbTax5sLzBg=,tag:e7pro8lnKG979kIA7ToGxg==,type:str]
    KOMGA_API_KEY: ENC[AES256_GCM,data:K1Y2W9G39fS6mizqe+pfsGA1XpfdMdYPebyFLl2rsO0=,iv:p8Bk9Rw+9mNafouWLkoAo3jECKjZBI1TgOJsQPJu7qw=,tag:bOVJWg6YPT8cWvXEEwaTNQ==,type:str]
    KOMGA_LIBRARY_ID: ENC[AES256_GCM,data:igwGPum9EzDCF4LEcw==,iv:U3gC+rLVGluIK2TfrSBRi9nOqM4O419OaAfPxNnoxvs=,tag:IUX6mpWUTmsLg5ephULvWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4c0ZGM3VQaXN6d2Qydktj
            R2dCcXFBNVBmU0kyY29yckdlOWlLZDNaaGlNCldzaWIxOE0wb1JlSFYvQUx4Yy9l
            NHdMSjFQUkJUekNQQlkyL1dIU2ZNV0kKLS0tIEIyenNGWndNOTkvcFlIV1ZmUDZI
            TTRWLzJjTmE1dkJid05IaFJPOGw2NzAKetNqKV9VwlYthYf/FcINjY1sZzwGzBtR
            gv1fTBBMGfOZLDg4KL0qOmiFXgIQuHLAceKaS6P4i2rwxWxct7uMDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T08:41:24Z"
    mac: ENC[AES256_GCM,data:8IYY1hX71a2fgSdjhl6GICQaHX8uhnawckGNKApc88hjb396VVkgiL1e58n/HqRYeVn6jevlSA3jzb4+CkWCjya6sQLidvAoqi0oSg2+ZiEjWTwBOY/BW2JGjbHhiwT/zP4gscHkVqMq6EW2l7BeyrnvJu2q/xq/gGYcswNryJw=,iv:znLD30RypXzDtkjPNjRJbOp9zFh81RlhtqMwi9snA/A=,tag:3t+aGKQwooCJYdtIFkijEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
