apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/instance: home-assistant
  app.kubernetes.io/name: home-assistant
kind: Kustomization
namespace: home
resources:
- helm-release.yaml
- secret.sops.yaml
configMapGenerator:
  - name: ldap-auth-py
    files:
      - config/ldap-auth.py
  - name: openai-conversation-overrides
    files:
      - openai/
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: enabled
