apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: home
stringData:
    #ENC[AES256_GCM,data:NkIzK2DqkWnUfhV6ncMvh4k6/J75HHFSx0UA5TeC9mM8e1Ssr2HSdW+S5XcFUwpuYSSYtyKPQQ==,iv:zykvmgwL7GdB3xygTLMoD6I5Szm7nu46VU5EfQ679Ic=,tag:1HU+ExFWwU5+cKgTSQENdQ==,type:comment]
    #ENC[AES256_GCM,data:my4vMVHabu02f8GAA4aRLyay69LMYes07fwMUiUwh2zvZP4QD3+B/spVGVoE6pBWhcMrgg4=,iv:KQT+Sfo736q3F4Xrip+U12K4oSTolcmeLaJCi68zGjk=,tag:euuI+DUtXx57FAZw8hMArg==,type:comment]
    #ENC[AES256_GCM,data:9RnygFQunMoizMeeYEA3TKqJpZ6A2v0doUxG6cM6GUE=,iv:+tGIm1ROcLZ2q/idjoppeUJ4YL95CFEkoatXCueMz60=,tag:7tKaZuwtN1B15TWolj05cg==,type:comment]
    #ENC[AES256_GCM,data:oOco30DJi+y8ibXNxI7kYzLhujXbEz38jYPe7RKL7TxMTzgrEMeeQYHwqgf3j8jsURSn5VAVlYQ4Lkw=,iv:Ipdqime8fHZhNRniFIJfr4xwbTEVkfvw+La7bltavIw=,tag:1qmZRoiYIbKGklfWsJiE9w==,type:comment]
    #ENC[AES256_GCM,data:Wv9lagxtVi/n2JqyaTp+v7khWEGC/wowCU2qb0iYdFZS9+ZE4sSjF56I2wDH7ZixnFqqJ8apxdaIdS+hHnpfSsaJyy4x9MC6BhSQ,iv:mu9g61Odb2KhWRDcvi6W+dGUtoAnZQ6oZKr5MkWe3kE=,tag:i+AzD+Mstmd5KBQVt24DXA==,type:comment]
    #ENC[AES256_GCM,data:IZCvATkBOqV8QS/OjcLvbwJx0E6zXvMrEPY=,iv:3vo3QWoPXjoWdvSOzTuqhl5x6pDsGnTGq98Bjn47jPc=,tag:SmySaEYX6yPIXD9asJzm5w==,type:comment]
    #ENC[AES256_GCM,data:OYizPdTzQeI9UxcDq8Bf9pJ/HBTe8wfkfAvr+A==,iv:1KrCyCmTcuE+x61MCketqCzW92cW582IbRkK8Zn+cqQ=,tag:N5Zp/ff5u1uG63C0XvG4pw==,type:comment]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:Us5dQlZElBun9+18DRcGkuuZa5NP9+SdpWe8+hQ68yIN+TPAHD0aPh0ihMIhiOpI8qMbtBFr7hhmcy4nUjDCtRMpEKZ8UHWfIM2bjPG2v1DZ6JwB9x1Sz6B59a4C,iv:XB0thSrX1SOMYcjbC6zXL8vDV0DJergk+r6utLKA2gE=,tag:fJvZfvZJ81RBS9sLKw2P/Q==,type:str]
    #ENC[AES256_GCM,data:CvF41mItdjmq3fHkWk8=,iv:GfCMUXs0LUQX1EzMQArFMsybtgI7M6r+0958XwvFdQ4=,tag:93eDVOVeZQk+SkqqvxKKLg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:oe/3/U2tuICVzgUOmAc=,iv:s931aSpGEO6ZLuxtcj6gZEoLSlVtyLCQLrrdeeWRi/A=,tag:vK9zvrqE8u3H23UNmxcJFg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:YESi8EEEjco4u6b0Nreo,iv:F2eI/3rNQIcCajT7RAUCmzfn4kbk+in9kQbUDzfGwcQ=,tag:pxN8Na1K3jsHwuBnU7RMuA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:KhrSiA==,iv:jI+/7h9MC7kXzNRIo+n9AYP2AsiS+j+5sszS1NqHAjs=,tag:yrXhzKvbsA+h2RV7piRMZw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:xD7+fAjNrcDJFCtudknjde00DQ==,iv:Ghv1S7TbVGTKwBFsfMYwAJpLaPFVeJvuldGlFEvWNaw=,tag:or3z4bxgDQFSu9O3oJchBQ==,type:str]
    #ENC[AES256_GCM,data:bcZp4GGPdowZ1cGm5mc2NLA=,iv:Y1kU4vZNhOoQG+ASy7f0VEuBh63kZWaZbqDiP4E4G+s=,tag:PkUUx9083lnwM5JKMlAvVg==,type:comment]
    LDAP_SERVER: ENC[AES256_GCM,data:tYHf8mKLaO9UWLE=,iv:HkW7P7NqZeyb+l457AJe5n+CRKWJF7l/2Ju+YlE7vvM=,tag:HbTr+8dVerEK8lagTTm9AQ==,type:str]
    LDAP_BASEDN: ENC[AES256_GCM,data:dJ1Ny/NrJBc2vjWg5ycLEQ==,iv:K0hKWNw6BNYpV/UxWDVOgEzV6wAF7ycwyzKty3WDqfY=,tag:W8Cu6fKdgubhCEWih/dgqg==,type:str]
    LDAP_USERSCN: ENC[AES256_GCM,data:fzrDImY=,iv:tRdfPUWa01UQo5RzFLcXmc/nk9s/cHa8D61Jchr2FeA=,tag:LAZgb2oE0CieqbEwNdA9Sg==,type:str]
    LDAP_GROUPCN: ENC[AES256_GCM,data:3jV+LiX8,iv:d0yqGkpO98USTKL5mDFRBXI+qXy/gwMvmt8BM6zSHNM=,tag:Bcra/FKTIi+xTgPzmqLYwg==,type:str]
    LDAP_GROUP: ENC[AES256_GCM,data:BOz4fg/eTX0MXn/kvQ==,iv:mtg6h/D/NRL3XUqRKfSXKsccgjSBakhZ2xsZFXbHwno=,tag:0UZMAstTyyK/P/RK0OTGCw==,type:str]
    LDAP_ADMINGROUP: ENC[AES256_GCM,data:g8Clka1acShWG8/v/D0=,iv:G05DYsb1IkdxkkAgztian8zytHn3la7H7AOKoPnMFTc=,tag:aX5j8hohPwOAm5KmxkWV0g==,type:str]
    LDAP_HELPERUSER: ENC[AES256_GCM,data:YTfYE0FaH5Y=,iv:vE9kcW5pyvAussFeebesu5XpFJv5/cLN7cFV8i27+j0=,tag:24FcqQNvvjJTzGX1/KZmmQ==,type:str]
    LDAP_HELPERPASS: ENC[AES256_GCM,data:IQBzt7KKPPtWxLveQyqjWNrUoyTz1FI0tBv77zI=,iv:pPZ248rgQFCFU6dYmQt8nwP55gc53ei+d3vHYQpo30Y=,tag:y/LGpVzIiA1UUKrpoPgGlA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWkNHWHAxV3l3R1BiTXg0
            M09MRkdDNWVmaFJhM1dIanJabFhJdVVRamtRCmo0MWpKcDZkakQ5YWxwdjBMRXlH
            SFFxZWRBOUsvSkVXSTJxeU9YaTBrN2sKLS0tIHJ5WmtORlNjRFZmMjNJem92Ryt3
            WkJZQ3V1K1oyY2VxWnB5cDlFMGVHOHMKIqeOcuJeppSL5ntRejIwEJmHnXFn5YnG
            p22Fpy31Vo5MPncrmmMxnhHHBtnGtCTkZx+7EkHq3ChbgbzOkqp2cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T17:35:29Z"
    mac: ENC[AES256_GCM,data:aJzGsyC15FbupH1C+zbYjpTgBlSLn5g3ZqDNZBtWQU2EV1BsoYaUz44s1BVDQ8ZU0v1OXx7GzvbFzbEjmPKOUEnThmiIVHbRnFw2fWcCbL2hwuxOM1WopWlVNxn0i6/oPCHZEp3F23hctT95bBRL9DcbmKAK67PhmvcRsiotyLA=,iv:3WxL/usNmIdsvwsEevhaS3KA7Yarn7ZF3H903MyR5GM=,tag:enVg57lkcpz8Y70REZBjrg==,type:str]
    version: 3.13.3
