apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: lenaxia-dind-runner
    namespace: actions-runner-system
stringData:
    #ENC[AES256_GCM,data:gviSkTWNXwaLhLO8jUfsa6rpRd7MfYHic6ENBeQtEXWgAaRohFNasDphmY65QtAHZLT2taiD2xtVKk0V6mOI,iv:fDo337EJV6I7UdTjTGoOpK/Oxy17E/RaPrU2YkN9Cs0=,tag:XlslTIc2n25ypi77gArNIg==,type:comment]
    #ENC[AES256_GCM,data:MJBnBCkJ7xcBQAcCyN/9BA0wobRouYkHwaF5JwEH1zBqGBmMoFkyXFIlC1RvoaOjw+s73DuniUtrXQwUNW0s9I4=,iv:o5K7q10DQchz+kgHhuTz2rJBD5LKG0as1GFvapv9xb4=,tag:6p9h1C+rNXAeUD4gqvzR4w==,type:comment]
    #ENC[AES256_GCM,data:DdROEL6+FxDj50RNLXx0R1GPpZx0J9UPnw5Cg0NS9HR2wt2gv6dijghTnSw=,iv:bKxDnp+Jpe+n/mAEpA0NI+T3wKCw7PnAGn3BRYpLrLg=,tag:G7rpnNoVx0A4gFc363J79A==,type:comment]
    #ENC[AES256_GCM,data:hsf9eeBcU6rcECr0MgP2NDeRy4HIx6QH3INHmZvkHail5oFWAZXkARIgHVsZgNFxrJRHhpzXHEFl0e/2/DJ9QFE86ORHY9ehZDfIVMbanngRCt3l3Nties9nmzE0dL4rBmG6JUSPqEcCireyLgWga2Ad,iv:faTHaTgNqnvLqf4Gp+G7rZZVw/+jtpZWHnysCJn/WSg=,tag:48Zk46pogONiFPbOxUEg1w==,type:comment]
    github_app_id: ENC[AES256_GCM,data:Sx4xLY06Fg==,iv:mP3qRGD4bNx6X9eOGqvIa7dFXCcEPGBB2knkR2P8MwE=,tag:X1rZy93kQbOc88MYfDcqtA==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:/zvNEf/yFQ==,iv:nUIn4AGytqAcOE6StLfn/QOZU4YTGNeucLorlpt/+FU=,tag:93Vorkv+Li85lz6Um3ftiA==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:oIOqBOAG3w==,iv:bhZ+c6Ie3Q6MDGh0IngfZ8aCICrnZJSviEru9C5bkp0=,tag:JcRIVR44VLXnS76E5k2Hag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVEZscjNpN2QwR2ZweFN5
            WlAyTE1jSUZMWGhaZWgyZ3Y5aG52Q2hUa0RvCmh3VXJsMUhLc1RSYkFRMnVEY1Rv
            TmFOM1dyYlR1N25FL0hidjdYZm9RSkUKLS0tIGw5czh5d2Yya2FHOXZsd2NrR1hI
            V1cwRGQ4UXFlcWE5bGhOSDQwSUROUjQKuZgdlb+Veu3k+lqWas1ES6ChS6RkoO1w
            lGhbpXDP4WKHMzNszohX0VYlYSftYcHY+ft4TcCkysYSZrPPrrVwGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-01T22:29:03Z"
    mac: ENC[AES256_GCM,data:rzOnAEwm2SUOrL070O+tICZpJDB5Bsga7iFMESzlpdfoEuY8PN+TB01k23VWkKfTxgxAvD9Ik2fIvM90/mmLa6ED5yqXucydPBpU6tVgqL+u50yQUhZvebWDtzKC3BkTwGcFvPg6vR97K4d9ov9TB33w7wcs83e2Z1XaBvQw8vY=,iv:kpHmQyQEnZwGs67wGdvzN9tNX1L5xld+86APzadohow=,tag:3iugGMipzt9YkeVl+p4X2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
