apiVersion: v1
kind: Secret
type: Opaque
metadata:
    # MUST be `llmsafespaces-credentials` — this matches the chart's expected
    # externalSecret.existingSecret reference in helm-release.yaml.
    name: llmsafespaces-credentials
    namespace: llmsafespaces
stringData:
    #ENC[AES256_GCM,data:BqzKMwNY2szD6ylCRFTFq1i7JRF8/I9iR8dRzx9ePt+Bjf8PEMQRCwvH0cFSN2sZD81YVQgoCZakq6AX3Wv1UKVrs/sldAVUNT5luKw3kdNv1vcsTgU2bL/u/rx9B6w7IW8oayw+FEJb3uEi5ILv+sngVM6wi65iHg/nIaxyLGhagzWUBfHUDQjAd4Ccv4l1G/Qr7BdXw1LKz8v6ATPMRYWCcC1Q,iv:KODdUMwR+t6qFXT21woJvH/zYCwgr8eDn2U6rp0skRM=,tag:8DD2p2KbZ6RHVxBYL/SvSQ==,type:comment]
    #ENC[AES256_GCM,data:MAVjjwRnzIoOxamImVuPAGTzDlsrh5vjVUyxnyM4ccT99Juu/6k/6+Af+jygBayfw6dYc/HEOgl7r0Xl+Hfxls3ihM8/Ng==,iv:JAVp8C952mb4S4ZgqKK/Q+HhAjbmhBXbyEubDgsm+/Y=,tag:L8MvU8Y3hsGUdSL9WjZpig==,type:comment]
    #ENC[AES256_GCM,data:7e2EvrPBvc/p3cQZ2CdAhHmhe3jAircJYPMvZWhyUXoNDjbIpEgTlyRtRVl3hO3SZIbrOncJq+mFCuajOf2brpp6,iv:/1blzG7rY/6UKeHNJUPn7NpPQXBHTvkefuyPTbymziE=,tag:aMTTOacF7EeQlT0iJZq8yQ==,type:comment]
    #ENC[AES256_GCM,data:Cmvq9NRhPuoPiiyvGtynQ+7EsyciEo1cW+ANYUZ/zu5PtG3EXtzs0KhF9G2Cq+qAYwW7zmVkaFWBuAmcjcy7RQT6TA==,iv:+kCycckkrjbkXgO2Lh1R42wf5uRspaifYwEWgEBb4IE=,tag:CcktrlG/ul8odfybGl0ANA==,type:comment]
    postgres-password: ENC[AES256_GCM,data:Hn1tbzHNAGK2zCdobGIovEpkg1QDB4Y/EWEh/3NhRM4GfrThttyRPV0e+LI=,iv:Fk7KBp79yVL3dFsR0DnYRa5zIdaoBGhN1F7LxbrGjJk=,tag:4OyiF8YURcjioCfifKgIaw==,type:str]
    #ENC[AES256_GCM,data:nlAP1fIF05mzNibVqMXXVWiQKly0IRc3zXrU4KYlZDHykCpYHGsOu3GMNgPM3j74ROMUq9mHSVo+GoWEyAwm0MqyWjvG,iv:4gDW2iOs/+suEs/MFg9shEevFQkYmwedRrucQFKXpH4=,tag:EPM/dHy2k10qD+bYoGszMw==,type:comment]
    #ENC[AES256_GCM,data:4NqSUbgLSeCrHy6Xms14eK20JrgEa6bOcahXLRwxxVRBz8b+5K8/qww50rd6cBqP707+fnvb+kZnj8A=,iv:uTYMGFDzQmU3d7h1YCYc8Iy4JT00B5WNiipjQouPZUs=,tag:frqF+ILtIVbmd9vZMlTShg==,type:comment]
    redis-password: ENC[AES256_GCM,data:u4ipcjU0nECPLo3kihwWwW6uNJpuXDZ1CdAKgCqS8m6MRjXBbdBPc6By,iv:7cvClfwdRxYiJFqcHLlvFESdVAj8m4QpbeoSU+vHhVk=,tag:p1jf5M6iT07gPInPxfo+yA==,type:str]
    #ENC[AES256_GCM,data:N6kzwQpEAvcq/9+z8+VjontUaa2pDnXEFc1NcLsb05Oez+A3jyEpelXU1Kkz30GYOqc1jAsCjHlRNrAhtMgD+Yoc1RZ5KeULmPHvnsoi94v0Xyprt58TFuK09yYvGaQnqCm4gVXAmpqGj8tzi735FzK1PqxrZDQgDUhqLvVZE1eacJGdbcwXoXVPyL1bGObrc/8+OoAE3AUpjOagY/xCibtm3TW0,iv:gWQJOtXib/OeI8BlWC73+2h/gZOfQ/wWSjcg/tL4cz4=,tag:l31FgrmkwLpXkeo2BvdWPQ==,type:comment]
    #ENC[AES256_GCM,data:RzT2HhmipmSeGESjWJa6pNdBKPxhTQd2sBt814B1R19hwxFOgEJSWbJCBNwsE000x4nMwxzSwFk=,iv:wRfu9HN8hAo78EkAa3jedWwkBZ+0XuKh5vUnueE/DAQ=,tag:V5cvxLd+O0ltmziBzlkadw==,type:comment]
    #ENC[AES256_GCM,data:hj9l5Zh+vnIScZnxpbR1hCZl8DWE2B8=,iv:mfcObeMuCvBzkEVGXLrE10iISCiYIHiitv8naTlQyTM=,tag:Npid38FU5Q6zXK3e4Jje8w==,type:comment]
    jwt-secret: ENC[AES256_GCM,data:gKSd2m1AQARCRPFEUMUPnP84WESayOtcxAfdi2JVTzTxI1W9eoTaCWTRRKo=,iv:rHyeWc1GnsRJXFiiEKKAqEdyiFJGfjK06EY4HP/1BPg=,tag:yzcF8UFRDeUhqyjlm9AAxg==,type:str]
    #ENC[AES256_GCM,data:Sy64lcGt/j0ksdNlw7GFjtYyOzK+ro4Se6cG7BZEGY0CGIrzoRuVFiemSU5w+zwO8relCa60tckKosNveNRogWULn4C917E=,iv:nRZeXl1+NLr9UCgxiVqW7tcsIIyP3/0kFIAFr7KRdxI=,tag:wi8Z3uuk1Oki0VkatHZ3hA==,type:comment]
    #ENC[AES256_GCM,data:WjcN/uzjT1L3Pe2thad2HOZHJkFk+ybEtC5wR8y/DM7zTgUVFTh1P+jYlsOrelQsPJHyCEk0zqV+TEdpoClnP4qkJuEfS0YX+g==,iv:VuL/a3rgwVYKjZpoeTvMrj9r5Ta+x9R/CwaC0ST5uJg=,tag:324VmtZKJE3HpLdNykREoQ==,type:comment]
    #ENC[AES256_GCM,data:360b3tjnFBZiaw6Ik4Y9xmGsSyaWAD4=,iv:2WAT3KywWwwuk5nagtbfyPawID4yePMRPRih5FwICnY=,tag:oTt4a/VsZgrAwbMT67ZuSg==,type:comment]
    master-secret: ENC[AES256_GCM,data:qgyfxq3Kyg6HfXAFAAI1v+5pcK1rpd263B9Rdo5YhDXgQWV350iLlR/cXTQ=,iv:ownuxkgunEWWkoog/Uzzisijd3n51JJxImNdE3prvtI=,tag:WZenAF6+zS9Yp6wZ7qg7VQ==,type:str]
    #ENC[AES256_GCM,data:rrZWTPqDou7RpiqlVQ1qjg3d1IzdF5c44j/Pi+x+r+cQXc+WaIXFw6rRysKtgU0zX3HmCtgDHZAiz/dzhwRtf17YMT9Q93OW,iv:4QMz5XHPPKzC7a5JU9XGlWGKKInJbx6yM8g2ktn0Fus=,tag:KhQ7mtXmqo0Qc/U7TNkXjQ==,type:comment]
    #ENC[AES256_GCM,data:xkdFYMMGGHzUBQlfh5t6vGWyJSRjdb7PWjmVmU76cwcZOriEB/frn+wUUAJKJoMl0cWFY36qyFX0VFrWxo63t3pvl/YT,iv:YaWI8WCHCPSkqy2yZmtydTco6jGmbUw4ixsN4xzz/XY=,tag:zcMePXkhZFjYlfEQX7mQsQ==,type:comment]
    #ENC[AES256_GCM,data:VEWt5Ugq1vIVV79afeKanwgtfOSkAY4=,iv:PrHUhhzw4Iwt6yYKYx3kXZpWJjaPEFhfspiD2+omLKs=,tag:a7D1YOMz66ruiglQzBjyZQ==,type:comment]
    internal-token: ENC[AES256_GCM,data:Yir8SYBOSytFR/u6MPxE+9NYpQ2apFo0iB6B+9T0miMSlidb8Uc4nLuySQs=,iv:ZvAmFvmulsk7KKAw8FomMW/id4uC2bCp5GHWI1bOKCQ=,tag:kpPpJF4mOEcw5ob57qC4XA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVTVKZWdYenlaOHU3NlVw
            R29EQW1YM2MvV25Pa0FiMVpkM3h3eXR2dTFjClFTNlI3SFZJa0N2WG9YRUFrZk5i
            NFNNUm5HQ0lFNktoaS85VFphbzU1NHcKLS0tIEFnZTVQQ2w0eTd3Mnc2TmZheFFX
            M0dGaGVsN0YrdnB1SlkvOW9yMkF5bHcKo//DzGLRJWt5cWNlQimcFZrrBAwuRc5y
            NJp5dFoCfx8sQeVZYp+N4AtXNSJICdq6wwSk5n+YBd9uNS+mlBaLjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T22:18:14Z"
    mac: ENC[AES256_GCM,data:X0V9Z9ntLE4qyxadR4eMFHsuDiaOGVsStXMiS7FV9UzFNx4Nm3pqRCCN2sOvMSuQfbx6BEmicOzY9I2STOpeKj1yoZWy8xF/W45wf99s8GqZx2jCZnsxUQUYG6zqtCGkogfUstGW+/P1tji31dxyXZY4Eqsc2ipGBVeacGaqD5U=,iv:hu1Jgl25g/ZRK2J/iZuX062NqnwZZdgeX7l0gu20bdw=,tag:jgCE0DrLSo+r0cdh5YQyeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
