apiVersion: v1
kind: Secret
type: Opaque
metadata:
    # MUST be `llmsafespaces-credentials` — this matches the chart's expected
    # externalSecret.existingSecret reference in helm-release.yaml.
    name: llmsafespaces-credentials
    namespace: llmsafespaces
stringData:
    #ENC[AES256_GCM,data:o4I19RzQxLV4jh4ZE60/MIoDPQI0NaPskNp5n1K+lq44RKJJFDXxkU5mgzlJHKfk6O3F6Q0BRhW3SXtOKPlDGIbG+ShsFA4JbEGCET3lu4BL8bGweGPyoNacpbOcBexSGQi3EstPcJdc3tNcI5fgrmoD0LlW8PyKoemUaCw8V0/3jcdmf+wRf+jTRWatLTd7OquBJM4VQ+0HF0ae/d7/qVuj1aES,iv:mbh0PLYwgJG8Zz1gbPQg8t7Jfa+L9B9ieJjCQRxcVAA=,tag:M/i4bUjqFKyR7le8uwc6xw==,type:comment]
    #ENC[AES256_GCM,data:9GRNTghJWVlg9444R1un2DfeCQffQLSPUdPwszyXBzl9+47HfJ+cJ9J4l39lz3vRqC3lcs0BPyVszcdb7mAA61goEYrKuA==,iv:N+Ls57pnweqFstI92SW8S8GOFQUhiITLV2+PLNVw4I0=,tag:8/9QZ3TtUjq1ZMdr+/tUzw==,type:comment]
    #ENC[AES256_GCM,data:8tr9TbiwMclynzxfjnQCmfiZ2g1gLB3JEO6GhgR0CzATYO7z2fBCbFNAzq6tldjSnmY6s/M/lzcObw2pCgdLfa2I,iv:7gm4dPUscECLmAWOz6O/SuQNIrfVxQI6ozrZYZnTuvA=,tag:hl4DJBm/eBdUiMdLEoxQag==,type:comment]
    #ENC[AES256_GCM,data:3L9iE3lysypBNxeL4mCd2W56hbxYnRkmqCr9PTwFZdBg0vA4ugDrCDyvZOJmyVLVf4YSlQCn0KMc5bh7DQM/xTkWCg==,iv:nfV3BAGEZX8lHeFdnjPlnLITI5ZmJ1ABqJIOjj9+zfc=,tag:sZHXT2RaJQdNqElhAF5yLg==,type:comment]
    postgres-password: ENC[AES256_GCM,data:GHwTbzUgxqsaDS+KIDMSgq+S4OGg5CR7X9KiUewk+oO+j/6DNuo17kjxKGk=,iv:HvXpGrmjXCmT4PHmUBUaH0q08hoDqi6Y6Fcwb3sgFFg=,tag:A6B6fBmXWBudq5O4+xVbVg==,type:str]
    #ENC[AES256_GCM,data:k9v8n9IcW+szQZBtDUFOZ0bW7ZdpvMjCaH8cqQ7RTuVbr0Wi3O1pLm173QUC0P4d7/CpLplsia6ySm2N65MR1f/r07wl,iv:4F5bgbGyxtrIx3mV4VuVDOB/IcJTPncZPYTqKIPyUZM=,tag:dIKOHGtB5zJ7jWulTFttzQ==,type:comment]
    #ENC[AES256_GCM,data:aCDHG65u1kDWX7JLizRZM3sH6KeT2W3AY35ZoloWbpVuJMR6p+PX/fpXoCnHIQqtOUlsIhKTwK/ykzo=,iv:2+aknMkTkVBZ0/8wMC9noMAAbMUyNh/NmK1ldA27mKs=,tag:3MxEmnhMjSbOxlLSTFf16g==,type:comment]
    redis-password: ENC[AES256_GCM,data:kgr+9kuLxJha89uVyXarOYy2oDMZop16ZEYSaIoF1btHbf6m8wwmwLRH,iv:FbO1RsHahwRmLydv/iktAQQNgpkWgbR0ey/uLjREk/4=,tag:z3WMMaj9PAdplNrjXjaNWA==,type:str]
    #ENC[AES256_GCM,data:ZaZBs8+9vjHx6unAjYm0XXjR0bHTzJiK0Wa7AOD1UCHN+qxVDpsbfpNWtT8XWAON2jcLcI1CJ/UtW6pfxqHfbNUJmF/0rgCJEJigH7MuEJHm+vKTnJmSyvhy+q3CsHmjM4uwL1uKr7AnM4HD9RN18CvbqCVrXVPCTenf61cma+0QVrTE64H7VWsABLDeJzV0IYQ268QPsmROMzPKF27lUNtF8n9s,iv:kWxeuyc0JNDI43Q9SlZo4/4Xm5r1flAgGRU4FkmuAl4=,tag:VA1PaQ3rpp0N+qAB0gJ0sQ==,type:comment]
    #ENC[AES256_GCM,data:LxqR3oFL7NLoio3Q0MNKTFtAGSn2KlD3AK7Z9nJL8xPvFOkJvI9YRtxHLbDvUm1MemFZ5562Xi8=,iv:mHchq1GreDAgWK2/Nb7GzUqOi8HEBpY018FXxZ437zA=,tag:azuwESZ5Q87uKaFmCEEc+w==,type:comment]
    #ENC[AES256_GCM,data:hLBrHC/Cp5I4g2mp88+EkUQm68EdlNQ=,iv:O5ZJ8TTPXTlZFLFcfMRWgbty2At5z88RRY306YOdHME=,tag:CnZjsv1PuX6ez5lNq4qU9g==,type:comment]
    jwt-secret: ENC[AES256_GCM,data:zqRPv2ADdyRuvltJGExbHiNZzwz9mT+8lArsyn0ikAMGzFpDA5ua2Y2EgPU=,iv:3N0WvTcnBvMhGmGRfi4aOzNC8dQpjMjqJKKB4llA9OE=,tag:QUwjLolWy0WTNDCXpbN4iQ==,type:str]
    #ENC[AES256_GCM,data:cQxXLoyFEo5j1EysqQd4lcLr76hNBlBT7oTOqLNmCPGGp2gMuuorlkM/bj3E3UDoJozYa7jgJBpDXjCuvbpV7F/D0otf9os=,iv:5z8ogEeNBIwocGgJ0zU24DCkOgDHfHyX5IvHht/XOLk=,tag:j9aHQgoDlxwy9zJew/9ynA==,type:comment]
    #ENC[AES256_GCM,data:oWI7KFMhvlXrD8lMoAvKnnsHZadHwJ513UhTZ+ngAFoUyW6w9PzMVKLdCwVmdm8LYCUKQJmDiX0RTNdv5AbiG3vtEjc/j3AxMQ==,iv:g1FeVFPVPUU0Z3f75y6ExoHP9zCDG4/fjyy3U0m+8Us=,tag:LrNhxfpMO1XU1slBPZpvhA==,type:comment]
    #ENC[AES256_GCM,data:tLnva3eu/6Mr0e/Ca2kAwVSP1YnX28s=,iv:vzQBp57XoVl3DPlQrVqzvS5w6ldu42JdXsQUQ0WDBuc=,tag:guI4i0lv7RGIo4pA35xLzA==,type:comment]
    master-secret: ENC[AES256_GCM,data:2AQEFlAta3JWHXewuPT+Q33IkpYNDCLtmiBRpQ1Rlweihorx544rWTxXa10=,iv:ZXLVpzDiZK7ULR+vIQPKscPeL4+JBDI1K6ro9hlQIoY=,tag:XUy8OD8Oqgs8dnxGnVnMBw==,type:str]
    #ENC[AES256_GCM,data:pD09eR2fQ3+Ro55hbcoK1usg5OHKfKL/E0G9pzI9QonojlnRL5pOiUmWRhRL9K/wTVOW/gUhPeLy0Kw2BjwTsUwlSWNGBH8Q,iv:GXyqB1ntuNlSiP405aK8ZKISvdyALwp35Dk3OVV9v2I=,tag:D1PSVLDRPJYQd1NDnBAEag==,type:comment]
    #ENC[AES256_GCM,data:32Ct3rvrz3m869DsZ2lAaDqb+h0GrziYZZ4r4gG6ZAaucjVVtnyPjE8D9CefcFl/9u5Uit97vgsgvOj5zLVKaqua63Sh,iv:SqAApdmpydWoyTLyS9yhJK9egaBbMAylgIJby/rb2Jk=,tag:AtxpOkeLDZpJ3ZPemUpqYw==,type:comment]
    #ENC[AES256_GCM,data:Up4X8My+Vx3NYbwgV0CLcYX7Fpgq4L0=,iv:ZC0aS4/qZ6DFWRdPO3Xa7PTdtMVyLPllGE0vMK47WtE=,tag:sQqZuCgnk7hhJGQX6wrwfQ==,type:comment]
    internal-token: ENC[AES256_GCM,data:h9vELJxRFUAQ0G+vcq1V3hvjEZgid2/ykAshZYfyHstlPqNfXGFG8DEthss=,iv:hOeNHf6VmCSznC9b6yR/0gKXqplqPnZiq3StZjFOGQw=,tag:bWofgGw4OUQEwDqHKd/gTw==,type:str]
    preview-origin-token-secret: ENC[AES256_GCM,data:meujLo2KV02MmJxD4S2dZQP8E1muXFQhoWJGPdKMILsD/YXD7137y4Xs3a0fCNIx6hkBry7CRue04aV7gctGYg==,iv:89Y8u45oy8ZxQy36I1IN3VjzIewvMqzh2sD5ON5/rzY=,tag:OqFVHatkhc/IooqOIc3ekg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWWpEbERoVytMVlZYaDlZ
            R1ZoUm1CODNFQy9IOHlzMWhDU3d3ck95RjAwCkljMVEvWUhUWmZ4b09xdmhEc3No
            MU91S2tMYmNQSkxJdVpjQWtmVm5aaTQKLS0tIFlZMUNybWtJVXNWT1pNelJuWGdQ
            ODhjM2ZsTnlZTTUwODdCMjEzL2dUcGsK5SnwRHK/MurUJ5rMMUyxPD8idt+6cquK
            fpfxToSuvJiZhm9TL6xZDebi5185rYuyfurKZ67l+BjNavr2/mDOCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T08:02:15Z"
    mac: ENC[AES256_GCM,data:8iN5LcDM4vCbb05M6lULFXBpmmj2CSWsqfjR3PKcgWjsx0hpkevmWH4hA8Xjx0c5STfbSUlejBgn7trp9/RosYWL+pVuuE6WrdUDNKBv12J08T4RduE/XUtGzsPH7oJEAmElB1xdwVsHn2WeWkeTsR7MEdhUU7gAi5+8SsX8oko=,iv:eXhkUdsoN4Rqxjq6n3ugK2RjdV633VHxqxo6afMTEqk=,tag:X4RojNTWViI1H37WfY3frw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
