apiVersion: v1
kind: Secret
type: Opaque
metadata:
    # MUST be `llmsafespaces-credentials` — this matches the chart's expected
    # externalSecret.existingSecret reference in helm-release.yaml.
    name: llmsafespaces-credentials
    namespace: llmsafespaces
stringData:
    #ENC[AES256_GCM,data:1r4xxilE+3RZGhaPD2M1UtYrunmo3BfXjphej8LRSDI+e5MoGNMcgUR5Nipinql8ATxTfGNS1hrNtoy1wA+5kVvMdFm8pXFHvAY9Y5rSWHdqd16LxW1WHlTYF5VDhRT+EndBrRJJek93BlnTrY7a3n1J0HhxaG+48pLtqdN9bY9N+STqzvSc7yima2XMSmMs2Y8hI2Ia7XYiUTEIhelWAE0rSwoX,iv:yZNCupbGbVWjVOeJRnbALx7CXZHXGIPKk3ZRD7bsiY4=,tag:rhBVv4WXCHbRowotfusRrw==,type:comment]
    #ENC[AES256_GCM,data:ghIXknI6Vp0VCHigjg47/Oeg2/wHwk16EPmbZSGbTzFlDRCuWFzdFwoSC6SAo6o9xZ5BFy6Pn21Ii2sdb0XRACAlCxf2Aw==,iv:Ng0wEjW9sSx2Aj7ZMCVrAlEBW1ayswSYI6uY4iShelE=,tag:i6z8Ngf3WKWo7dL8cG6o1g==,type:comment]
    #ENC[AES256_GCM,data:s6W6qmya6QcyqZKJOqVUGr5nDPssyUzP1jcENdyFqFqHgz0+c6a/lpObnmsjKrBU67m2/h3lp46M9226rTtTzR49,iv:SW9+zmOp0/U/SNcranIi3zriSbiMIIAwRAH7aZpmZ5w=,tag:awFbM1YP4i+dhUupku0MAw==,type:comment]
    #ENC[AES256_GCM,data:6xQnqTjm2hfyyDb4h96fiSAQLHXHmY6y35KkMXCCaPKSoVyT/rGnKx8GdLkC8P6i8AStJmJPBZILEamgNy2oJSOuvw==,iv:4BpIjX/itNi05363pauVGFZs6UM/6baD+Oef90O1wKE=,tag:nGrPY5DDKJBaUQikBaoSZw==,type:comment]
    postgres-password: ENC[AES256_GCM,data:hquuv5TtDN0oepDPAiMKAjCRicI6NJv877zYjhpz01lzhphS/AfI3XZnWyo=,iv:1m7JtsTnQmQ8sk0dhMCtOQgiFRm4gg96cyO5OrKlWuE=,tag:QYBX5plfBnkykevTDwW3nQ==,type:str]
    #ENC[AES256_GCM,data:jbWwawV/mKUBlinVvd/jTLoFYUafFPhXVuAyEKn+5b0P1pFOulpKMCbp+2P6iK2DHSa5uMFKEBj2/7oABZHvPwMZQ1Pc,iv:EQcT8kdKWpZLzxPfRdqi6mjoPqKfXQYICEHmbeuyVds=,tag:2jjddjszBoXAxNUa0g1/nQ==,type:comment]
    #ENC[AES256_GCM,data:Y9KvPSCWHEXWbUPy7mgXtkBYxHY9fLFdRCiAKmc0EmfDnyW6Z+jM7uporORm34KUO12iu/TikfaHtNs=,iv:XBDDMqaHwd2lG+Y8XrLtmnJXYEBNFBO4s/SR4d7dUAY=,tag:1vDVPj4+xw9lY/8hTwZLng==,type:comment]
    redis-password: ENC[AES256_GCM,data:HeV4PVSAy2V1asRQd0SWvkFTQYL+tPmeklE0+Bh8EuiOzYxVLcuPbl1N,iv:GSWmbwkdyQCWqyREXMUqFarC5jPWfCOvsemuMKpcDz0=,tag:wIpSzpPPMpm3PXfR2jHoUg==,type:str]
    #ENC[AES256_GCM,data:uk/VTrA2hpa5MyMS3q3h1jNhocwn3qbQCETGgbtrUwA6fUXl/NvpSe2yERzCXsjp7Vz9dNX2sgRLojUbk08mZiw2IJcTheJXB7/t5wlht0hUkVT7KPuX7yK4eLWSTFNtwGM6+vVEhMh24HLFwWKqGjDFx3Oy8BJZZi0zDw8sLaNXMMwzcl1OP1sCmfL5YsziiCQoZFL0+da8vfcy0C0MTVlrW3P+,iv:j/t7FNAJ2U9UxBzAXG4tIpy6PBn0SA3UaD6EdnCB8ko=,tag:TXJW/WqDyCIgdz/xtel9qw==,type:comment]
    #ENC[AES256_GCM,data:n+8V2uotYAef6Tminy5jXbCtEpP4fVvcXHR/btF7zA0ZZLcXSz0VE7YrqI9zeJgpOORYB6fJuhA=,iv:r0mNb+nPOf4GFwnHL+ATKFqYoNWN+gb8yv/67I6FybQ=,tag:GObBAJDlzy2+RthBjB4PZQ==,type:comment]
    #ENC[AES256_GCM,data:sNG3TKc8rZXbL8eWhk2pqE0Lx+n4d20=,iv:V23+EWe2l+ZMsmjwlg2qlKHyEt/KVpJzExO5Cl9c0ps=,tag:eNV/Bs5yN0if9lj8j+SEjA==,type:comment]
    jwt-secret: ENC[AES256_GCM,data:Vt7B1a15rHJRV1OtEJSNhA4AuYtOaFfgXSfuJtFK+FBNuzmljiS/yigb0ps=,iv:+8q7T4Hd1kWoTCZdu5RLqpOAnUWdnyFj59a4NwWi0CM=,tag:Mlmt3XRAIKx5KI3xJJTaXg==,type:str]
    #ENC[AES256_GCM,data:Yt8jUvHpMTkupYWCCgZeV30SiakB9zFaDxh/9MA27cK17cEafLVbd+0cWxQvGqHJoxvH515F5vrCNuDnYK9bg0AewyrFqX8=,iv:XZiDkMtHfSVkWPw8tF4wG2pWYivSTTFcWHusRlHV4sY=,tag:g8WMVu0GZAD3OGD4sZwqYA==,type:comment]
    #ENC[AES256_GCM,data:uSxN9o5nDPPwBMHMnJoXYkuHxr2oY7jdlqafk71/ZIdPOCCcgSXYzQK0QyER4ACb6/u6vcm+iwctcEUyuPFU/SkhTOkArs6Ssw==,iv:G4DePYgsproGRchWwxmwEhAU6tJtI2rq7tPZYMsYCSE=,tag:PDbp3N7X8PjqlKh6G2Tg4Q==,type:comment]
    #ENC[AES256_GCM,data:Tccu81CJ1s+ba4AuIkibOtHQ6QUXHS4=,iv:tmllKxd2Va5U23xJs4LYmibfDJOPrnkOR84iUnF24pY=,tag:R4I62c/ScEqGHld0FMH1ew==,type:comment]
    master-secret: ENC[AES256_GCM,data:VgAXcDwAyxvV60o4FbCD0m+6X5QYXfqfMXa8jzharBCYfeM8O6XmnKPN3f0=,iv:pau+DvsIuOju9iIGUB1/tISi5baw7zCFjA8JC2mvv00=,tag:ir7tvOOK57iGxAoGQ3uWqg==,type:str]
    #ENC[AES256_GCM,data:dFAE+AMxZ87xyHazcMzFLi9e8hq/AFkQS5bafu/rMKZMdsjdu2m+OCofvUPPNlNrwJbjt7FQItFC1Xz6WTOv23gxFGOPa9nF,iv:HLrU7y0Zb6pS0+RhmioAJkMRGVNIUAKvEaojauIYISY=,tag:buXRLWDengwaOah/qKgvcw==,type:comment]
    #ENC[AES256_GCM,data:lp0bMACE4F6SoUcBbagvCLgythwbINPe1+lw1UM6nZwm8nXH4cAky158qiwgFKaHIkVrFJIIU//FXG5Xs3goZnXLrar3,iv:IGQdHuwrfXfAgp2UsjcL/XV8H5U1CsaSWZv20RHopkY=,tag:cya7ZJIs6CmjdadB4GbowQ==,type:comment]
    #ENC[AES256_GCM,data:Zz2/AOfRMdnqG6ScNIdLC1seq+wsgmI=,iv:s3jIsIrahrfEQp3Kr5Rlz8YS2JoZpfNsdkthX4S06uo=,tag:bQwdni8agxp1jF4CrXSR/A==,type:comment]
    internal-token: ENC[AES256_GCM,data:CbHpp2ihySadMUfHNrigbhvwki8QUAQ2+y4iiumX0If9N2M+TaXh5bS9QpQ=,iv:yBWBidU8r7wpjlJ6v43+WF4HKpo5aG88ZLxSpkPaQCY=,tag:8ATjZ7GmtKrCEtFwbMKE7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdmIrck9MaFB2N1ptSU1R
            RXhSRnlaRXZabWFUWVJ1NkNuMFpubkNZZmlFCnloR29kZjlwcHlWV2VraUw5bjEv
            NXJUcXBVcDFQcWltNkZOb1RMZnkzSUEKLS0tIHJJZU14ZDgyeEcyUG0zVi9LbVhZ
            YjBoRG9nNmlZSWxzVEVKaDcyWXdnYjgKp0pMhDGR9qnCVZqdGkaqeIvedgMWgjPY
            AkXcDhKyqhwbyJaiHhFuIcGMMUhmXVcBpzwso82C0GulmkZPf90PfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T19:42:04Z"
    mac: ENC[AES256_GCM,data:4gV4RiIBHUfDfLy6n+TNChOrIBn3ZgRGJlQcA3kQpm+Z6QUSTV4ZPYLqGDZvyU0+QWZCfy8sbV+MTioSzQFGh/S8I9sBk+axu8v5F9n+90u3lQpJwfiWMTF+S2ReSctSAf5PLqWo093Mu5E0C05VcrM+YwqDdHjKlSNflhQWpJc=,iv:7fqpjL6Jr1O7mTezeYqNnOoAB9/slMHlTINL34j0UqQ=,tag:hsMxUQBRleQvyATcSGotLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
