---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-gpu-exporter
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: 'true'
    controllers:
      main:
        type: daemonset
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/intel-gpu-exporter
              tag: rolling@sha256:90a95483bf5d3752f4db2ab2e1663f19bba307fd832bf53557cbdc38c3701f84
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 100m
                memory: 100Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 500Mi
            securityContext:
              privileged: true
    service:
      main:
        ports:
          http:
            port: 8080
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
            relabelings:
              - sourceLabels:
                  - __meta_kubernetes_pod_node_name
                targetLabel: node
