---
apiVersion: fission.io/v1
kind: Package
metadata:
  name: matriarch
  namespace: fission
spec:
  environment:
    name: python3-manga-updater
    namespace: fission
  deployment:
    type: url
    url: https://github.com/lenaxia/functions/releases/latest/download/matriarch-1.1.0.zip
---
apiVersion: fission.io/v1
kind: Function
metadata:
  name: matriarch
  namespace: fission
spec:
  environment:
    name: python3-manga-updater
    namespace: fission
  package:
    packageref:
      name: matriarch
      namespace: fission
    functionName: main
  secrets:
    - name: matriarch
      namespace: fission
  InvokeStrategy:
    StrategyType: execution
    ExecutionStrategy:
      ExecutorType: poolmgr
      MinScale: 1
      MaxScale: 1
