---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scratch-matriarch
  namespace: fission
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeName: pvc-ef74068c-15b1-4151-b64f-7fc8e946fde0
