apiVersion: v1
kind: Secret
metadata:
    name: matriarch
    namespace: fission
stringData:
    KOMGA_API_KEY: ENC[AES256_GCM,data:etJG5UDY9f9x2x3PGcyAQE0viSYRF6Rjqy06fiE6zJ4=,iv:eSD5yup3y8sGSgOuVDGy6RKhwuFatlnrvesNsTQ46iw=,tag:DMujb9UVxBzFdOGfimTGMQ==,type:str]
    KOMGA_API_URL: ENC[AES256_GCM,data:NVYIQY1tGukhANZz8Yuh6PhedSCaycQteDS07b6P+uXHV5nCf94knJ8=,iv:BjyPs+DbnAvkBnHjjA3Q/3+m3yu0Zmmmn1xcDqtsmVs=,tag:4h/NQdpozEHgJtZ7C31zuw==,type:str]
    KOMGA_LIBRARY_ID: ENC[AES256_GCM,data:Xd/Tu9sBKUDNJyXn8Q==,iv:7s8v6ihL1R+Fc3NNRpHdgL6sdz4/JsRFKqKdXSYKvFw=,tag:PtssMOQyCV+8YSSfgE+zZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OUpwcVpwNVZSdTlQYmJW
            L1NFN1BweDl1ZlNoQ3hmNXhCVUFLeUxuTENvCi81cHlrOTF2V3VUK1cwOTZ4T1Qw
            dXVNUyt6dzlHbGoyNlVFNzRNckVteUEKLS0tIHFXYmsxZlNIcnhLVG9FaE5BMTlh
            YXd5YjY4VzRkSXFlaC9wc3BDaVdnRE0KCOR0RXDk4K2K8FHQBRpPe7YTjQrTJQAO
            Sya3DjZWMBtVhvdelLgKv3jLV2agr0rIIBHt4PqjeLUpfY1D9LiUTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T23:24:17Z"
    mac: ENC[AES256_GCM,data:xPudA67MRLCFyQ5aDCvmot1blTbYYcxZ3fFxerGbov337HfGPzk6mHAZyLxLqpwSjnh8uN/pOI+3elAbsn5AwZatuHKnfZtwxbu1Cvx1wLiCjoePQvIMQTDRHaNiASqcZ3obs8t2wMy6Dt6ZiAP0ezR7Nvai2uooufVbAZjWePw=,iv:PMJjjl/hA2Ch3j0vJG1MlNPmXRuye6EW7Y1wA3pz7YQ=,tag:RRWKDcvFcFoZHqaDZirVvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
