apiVersion: v1
kind: Secret
metadata:
    name: matriarch-vy
    namespace: fission
stringData:
    KOMGA_API_KEY: ENC[AES256_GCM,data:FVdnBXiROyW8j+Bu24fBIHK2jk0XvSFU05xZqrtquJc=,iv:+U3llJgGnpXATRm7T5Nk0J8BGVL8n68mQqhrSBYLB2g=,tag:Jwvipy9Dv/Rlp4bJXrRlHw==,type:str]
    KOMGA_API_URL: ENC[AES256_GCM,data:IZrOKRphlYwSLkOVIhB0Ll3cKBIO+wUPce2lRhIXOOhyU/1yzAneHZE=,iv:7Kqp4SjMgZu9TbX19ixt/kqn1jWb58ReYTatGbUk+C8=,tag:7DrTEMS/NSCXdd0IZMXJ0A==,type:str]
    KOMGA_LIBRARY_ID: ENC[AES256_GCM,data:DL6nGEj3MkXcaGj89Q==,iv:i1mh5b76r/1jY1CsfBsDPIGTfEtPdWIVR0WN/95FSzA=,tag:OZQ20k4GURhxDY0piqLqfQ==,type:str]
    SERIES_NAME: ENC[AES256_GCM,data:TdUjE0YqoGwmhiKFQNwkGbmurhUE4XeQXRXjezBql5ZZh8Cx1GnQVIRof38=,iv:p7B5Ug84VnGaNWHEVP00imBGQo/BtTUQ8RZP3Siz0UE=,tag:5tV/W+AsOwPiUen4+WhnCw==,type:str]
    VYMANGA_URL: ENC[AES256_GCM,data:35YoGHIygjEhODHT/IMYzt6uQcMHmsDoKNWkQSX4NdvigWJufQ4z8MHldvPD1TL7pOBYAdKBrcZIZ7w/EG5lxHAPYT4=,iv:Gi+eN9xQ+mXoP9/0xskbt5QWRwmqyvlvwTkasWoG9C8=,tag:W7YN1sl6M0KojPFw7cF9qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXY0dIdXNEaHJFQ29YeTlC
            NDU5ZFpzQlN0WVpxWWVKYnpxQUo2TlQzYm0wClRDdHFLZ1BHc3U5ckV6RjZENks1
            OUFpNFF0K3pWYWsrcFRZYUdyUGJyZnMKLS0tIEJuNjBQcmtYUVN0ZFhlb2s2Tk1i
            SERiR0s2VklIQ2lGUHBUeFdSQVo5U0EKZt/Kpuyd6OEr7skbaUsV1m4S0V46Anyq
            4yAEgx+Tj/p3Kz5d7YwVYecg5y2oExcfiAoobJfgAdeRRvMf+mCGZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T06:38:58Z"
    mac: ENC[AES256_GCM,data:1cc5tQ0tlKwDi44+q1lpd1xQXoRXHzdzsKLTjkk3n+WgsC9nm7n+WtzuTidCPbZp8tLZc901mfEHZ6A0oFaiMrb1QHXXOCF3OibkENPzvbReP9wVdebxVARlQHfeQ2eiDLGM67606tejo4C5Zso4iM0DYK3vrgoCncOZK8HFHik=,iv:hvesiwjjeR7mxFXCqR6gV89E4ZF+NV2egWi8ZiuaFJE=,tag:mt6UpwNkz2gHg52jLFloVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
