apiVersion: v1
kind: Secret
metadata:
    name: imaizumi
    namespace: fission
stringData:
    KOMGA_API_KEY: ENC[AES256_GCM,data:fkUB0epkypPNGYFbtmaeXvwhi+qcFqOtT9Dxstwnw1M=,iv:d3WB8OS/1+9hg3FqDux6mjAUQhK/tq2RtVtFmUGACJ8=,tag:65W/GBD9TVmyxfzqGDBLvA==,type:str]
    KOMGA_API_URL: ENC[AES256_GCM,data:STk6BdicDijag6XoDrSsUVhxwFdDZWMewmSRBvZtQG/+jQkTId7dT70=,iv:QHqdaqtsB7deodIPUkNXy2M96l6QsfsW8AWGZKTBmfs=,tag:fyxWbyeBCQeHRDM02VQzOw==,type:str]
    KOMGA_LIBRARY_ID: ENC[AES256_GCM,data:wKK0PBwiHA6PyBuc+Q==,iv:lEemdmeuCrwTlNgWVSxhUf50vD4X4Mj/+TJz72pdr1k=,tag:YBmwFqPODFpyExxavec4Kg==,type:str]
    SERIES_NAME: ENC[AES256_GCM,data:nS37opBuFbddBBxm8g3LYokMvBa9kvJT5AqBigWjYJrELDUiHpx4o69heSvo/IfhNo7PIgAyOuQEZX1UIs0=,iv:T8RIjqSyC6bcvOBcdT4UNiy0MsiP/HPEu4isWl6LKy8=,tag:IzsnjcbQBuLHhjhHeRpTQg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNmZoQmZSWFJESzlJZDhL
            UitWV0I1RlVxajZSYXVkRExEMm9sbUdDY2xrCk9rVXdZUXZMbG5ZZW9pdTNOcHVj
            azJydzd4VEZkRUs0ZmozTWZjU2o0ZFkKLS0tIGZsWS8wTG5KT2ZOZXUxVFlCU2gz
            WnZEalEzbld6bkRPdXNJbE03Z1VmSVkKXm+FaqJppxDsoZiQgHLTPypJ1ukTwCMW
            knaMZT0S+dMpJ+A5bHrgj+iS/ov+OxMzHxEQ9ZkA3b+hqIPz5vMcPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T07:05:23Z"
    mac: ENC[AES256_GCM,data:ATN1qd2/5BANEF1w7Lbsy9JgHcPJj97vchlcvJ9o6qzW/IvfeGEfC22P2lSBZLJwi2/CSlkQZq8SKFTykOPT4WTMbjtW71cB0Ivi57pnu2hQog4Nb6d9JwGWzStfkUFgd71Xw0jax5J4/6XCvmd1c+3J6uvH1BWx33tpG4R9RkM=,iv:zZatARPcgLC2YWJpNJ5Nmlvs3py/L6sev790GPSVBU0=,tag:UJBO82c/3w/TdCxn/PB5tg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
