apiVersion: v1
kind: Secret
metadata:
    name: mamahuhu
    namespace: home
stringData:
    litellm-api-key: ENC[AES256_GCM,data:+yGh1VJGr3LI/YtJuh0MOUvf2yziK98Pkw==,iv:9eFbkcsNGpJ4Ympf4aSyhfed1YAUDPXN7X0ol5wVycw=,tag:WdcpuZFhmHJYU+59Jnrtfg==,type:str]
sops:
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM1BPQlJZTzZGdDg0RXFJ
            azJ5ZFI3ZURoYXFVSzlwOGZCUzh2bTNCQ2xnCjhqa01sd0dWT0tMbTBsWmlpd2FM
            ZGtXbEsvMUxtLzJPSktVSUZVWmtKZmsKLS0tIEFaanlQRU12UzRpbjFESlA0bHBG
            N3VyZXoyYkJBWldiVTF1a1V0S3dhYmcK36EBidOetmFA+K3n8hM+hng2wfhDCqv3
            Ra/6CD43dQ95S+Nx6Vhvg3m1wYgK9RN8QSIzZEa9dHH7Lf4RNzvBhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T07:58:11Z"
    mac: ENC[AES256_GCM,data:lh8zAXuFqzMAwFYd4POrGN6ipKoVAnIk+tpNt5lV0iLymEwdfz7TOG6OHyhCKVyYWb71fEjYdYeu3ps4CLPXZCdZ8udwYUNEYIMlwZLGs6mGZrpPV9RIqbZxQrDQq3pUQN3JCz4O18DX/Wa7oBW23tUa8V5SR4ULmdselmEr+Os=,iv:+dMSuhyrAzJVioCo0j6eJN4LpZ6VT11Xv3AhvDFrpAA=,tag:+smV+gVShX8fY9Fh7BvQHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
