---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-net
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "enp0s20f0u3",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.0.0/20",
        "rangeStart": "192.168.6.1",
        "rangeEnd": "192.168.6.50",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.0.1"
      }
    }'
# # The below are commented out until we move all nodes to eno1 interfaces
# # Until then we should limit pods that need multihoming to just worker00 and worker01
#---
#apiVersion: "k8s.cni.cncf.io/v1"
#kind: NetworkAttachmentDefinition
#metadata:
#  name: multus-net-25b
#spec:
#  config: '{
#      "cniVersion": "0.3.0",
#      "type": "macvlan",
#      "master": "enp0s20f0u2",
#      "mode": "bridge",
#      "ipam": {
#        "type": "host-local",
#        "subnet": "192.168.0.0/20",
#        "rangeStart": "192.168.6.51",
#        "rangeEnd": "192.168.6.100",
#        "routes": [
#          { "dst": "0.0.0.0/0" }
#        ],
#        "gateway": "192.168.0.1"
#      }
#    }'
#---
#apiVersion: "k8s.cni.cncf.io/v1"
#kind: NetworkAttachmentDefinition
#metadata:
#  name: multus-net
#spec:
#  config: '{
#      "cniVersion": "0.3.0",
#      "type": "macvlan",
#      "master": "eno1",
#      "mode": "bridge",
#      "ipam": {
#        "type": "host-local",
#        "subnet": "192.168.0.0/20",
#        "rangeStart": "192.168.6.101",
#        "rangeEnd": "192.168.6.150",
#        "routes": [
#          { "dst": "0.0.0.0/0" }
#        ],
#        "gateway": "192.168.0.1"
#      }
#    }'
#
