---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nessie
  namespace: flux-system
spec:
  targetNamespace: jobhunt
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/jobhunt/nessie/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 15m
  retryInterval: 1m
  timeout: 5m
