apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:+iIa3N1C/YI=,iv:E4fe8D9YL5WETN+5kJ+9uQ5+bUzXZX0ZzjUg8ItnXco=,tag:b+/ZHyB7mMDlKdPH3XwzPw==,type:str]
    password: ENC[AES256_GCM,data:LgDDa0SHhNz10liKFA==,iv:qLUHYtqH/Xz9MXV5UmxpZoX7286S38FeXh97mlwujYg=,tag:AKGriiDsvCmMFOgdu0rRtA==,type:str]
    host: ENC[AES256_GCM,data:waRygrapIaFkIVEpSitTnpxLjgI9yCtTvJobuVDzvF9hgIgGZ+3VCw==,iv:YWTmSjeHJMlEsOgcgL/zXATfzxZah45uTyTwst58w1Y=,tag:SQFeG2jJib5/zD/Ih/c51w==,type:str]
    port: ENC[AES256_GCM,data:rKCZDA==,iv:Bsn8o7W/7SHXjjINYGoiGQYhsIVz4t4fBGM3Fr40XIw=,tag:YkuOr3Pbqg3XBsCJW4x8uA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WFRJV0hGTEtaeE1TZVcy
            RzVVWjMxMFhQQWxhZFFJV2xpNDQ4blhCTlFZCk1qRzZtQXpCeWtDc0ExVEZaRUVU
            NkhSY2xlN2VsUW44Qlo1a0ZtY3FPRGsKLS0tIG5YSnRlVkl4UEtQTFo1V2w5ekVh
            eitJZXd2UEE3YnZBZ25PODFTWmxNazAKg11VxQervy2mF8o9bNn7gbfaEpws0TU9
            GX5vEG+XZrce2fcM+NLdqe589vJZWbFgIx1ormkTXjtHV7NdaDGnXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T23:19:10Z"
    mac: ENC[AES256_GCM,data:6BlwKIUN7lypXXVhwhOVLTl5iK6aW5e4TUxB2WdpjnKYVOHham17s2XyMhS5U8rwLtQ+WaW/WKHKXDQgD/ZzMqvUHQJg0BcAXkzVwuNUG0NlBUDFgzkAYOauedmMmsJ9en7z+c8YzpFWZtba1MkwWiwVblgxoft1i2toDNxW6xg=,iv:yNQNyXuw9qJKkn4ubfUZkxep0joiMDXTCq6gBuKJE68=,tag:gh9fwFQU56A+YHjVT+rVKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:IOieslyzAh1m2+GAmg==,iv:1ek5SjtNmiC6l8Yjr804KAZwn83I74fciU2WBGg4kAk=,tag:+gyxIaUeFUhG4XAMcaIUfQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:a0w6noUyHYRmYALQMb3dKy+Cnxg=,iv:hqqYemC0ul8bgkoPLbZ+vPY3nkilrePBnikhz12+cvc=,tag:lKfwnDljIGfX/x96u+Me+Q==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:/UwhBKc=,iv:atYGbWHynbse30S8o7VXolJSdV43VIzQRfOySZzC7iA=,tag:dzbRoycj5HG+O49+kI/gGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WFRJV0hGTEtaeE1TZVcy
            RzVVWjMxMFhQQWxhZFFJV2xpNDQ4blhCTlFZCk1qRzZtQXpCeWtDc0ExVEZaRUVU
            NkhSY2xlN2VsUW44Qlo1a0ZtY3FPRGsKLS0tIG5YSnRlVkl4UEtQTFo1V2w5ekVh
            eitJZXd2UEE3YnZBZ25PODFTWmxNazAKg11VxQervy2mF8o9bNn7gbfaEpws0TU9
            GX5vEG+XZrce2fcM+NLdqe589vJZWbFgIx1ormkTXjtHV7NdaDGnXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T23:19:10Z"
    mac: ENC[AES256_GCM,data:6BlwKIUN7lypXXVhwhOVLTl5iK6aW5e4TUxB2WdpjnKYVOHham17s2XyMhS5U8rwLtQ+WaW/WKHKXDQgD/ZzMqvUHQJg0BcAXkzVwuNUG0NlBUDFgzkAYOauedmMmsJ9en7z+c8YzpFWZtba1MkwWiwVblgxoft1i2toDNxW6xg=,iv:yNQNyXuw9qJKkn4ubfUZkxep0joiMDXTCq6gBuKJE68=,tag:gh9fwFQU56A+YHjVT+rVKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
