# Password Secret consumed by the MongoDBCommunity user definition.
# The operator reads `password` from this Secret and provisions a SCRAM user.
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: librechat-mongodb-password
    namespace: databases
stringData:
    password: ENC[AES256_GCM,data:bUeszUCj74mczTt7c5MlI3rm/eft2bdHpEl8WKPi9AOQFED3xG1Gqk58/D7fDzZ0,iv:FCOtYdPUErwBJeh81g70ldelfxPY4ODwLOtb39ZxX1M=,tag:ZfrWybrpnzovDGBZ7Un5aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQT0VaaUR4U1lsNldGaVBa
            RFk2YkFoWmVFQmgwWXRMZm1obCtTUGkxTkdvCnF2V0dpUHEzRE9JOTlocmlQMWla
            MHRXSGRqM1BYWCtROVBvM1pUbHhqZkUKLS0tIGhFYWVDbW5Wa2Z0cDRRZ3B0MS9o
            UEs4Qzl2MjdxNzdPaHI4b1Zrcjh1UTQKgywqQvSV8P6y5fHqqsfZMHfdaHnNqPW1
            XWDEo4HURoltHdVBnwFuHxBAsNPyEiwbfjtM1KR+BPH9gsJ/wxMT4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-16T07:39:57Z"
    mac: ENC[AES256_GCM,data:p6xM17qfMfb3n4KE48g7RRUzhjdzPBN0oKzvsUKMTUD7RITihSBfInDXH0jQypvNDZVzVBMf03cIeN5UrdzizZS5og64MRDv45cnztt84lTr69XSAgL88TRGnTb8i5R5ZaWIai+9AHryw+v1o7a/MQNCvcEWoF6H9wdCmqwixtg=,iv:thUta6OLBnM1T0NvwMJkQUYI/Q7i//pjw6zND6G+eqM=,tag:6d75Ke8YPdymxPGdkZLs/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
