 ---
 apiVersion: "k8s.cni.cncf.io/v1"
 kind: NetworkAttachmentDefinition
 metadata:
   name: multus-net
 spec:
   config: |-
     {
       "cniVersion": "0.3.1",
       "name": "multus-net",
       "plugins": [
         {
           "type": "macvlan",
           "master": "br0",  # Default interface, can be adjusted
           "mode": "bridge",
           "capabilities": {
             "ips": true
           },
           "ipam": {
             "type": "host-local",
             "subnet": "192.168.0.0/20",  # Your /20 subnet
             "rangeStart": "192.168.6.100",  # Start of the IP range
             "rangeEnd": "192.168.6.254",  # End of the IP range
             "routes": [
               { "dst": "0.0.0.0/0", "gw": "192.168.0.1" }  # Default route via your UniFi Dream Machine Pro
             ],
             "gateway": "192.168.0.1"  # Gateway IP
           }
         },
         {
           "capabilities": { "mac": true },
           "type": "tuning"
         }
       ]
     }
