apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: trino
    namespace: jobhunt
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:es/UWC3RdA==,iv:MAno/P/7XuwSQcI6xasGwik87EUj0yK7diw5eBxmgQ0=,tag:bmm/drWFVxlGY5+gNGm6UA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:2HpAjQEzPxEOvoXRKPsW1ELkBbw=,iv:trnZaGFm4NF5OBciYMW9ic/gYn+CS0aK4Dfpa+yhMQ4=,tag:WrDObWEPy3wtFSLdTVNgZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbEtGelFnYWZpSTdMUzdK
            WnZXY05WZkE4aGlQWWFrK1N0ZUpvMXFsVUJJCjFQS3VFdzhJSnFyRTBaN0hMa25B
            dXN1K09OckhKYUdFN3Z6cVdNQWh3K1UKLS0tIExlV3VMaVliWnV0VjZzM3gzTGV0
            QjRjUTdqSzR1N3BLazdxNmgrZ3RiTzQKOp+89gZfYzqpsMeSCD/uJvjSXEKD260W
            oAJd7BbA11L02Xwwa6wpMbdR2wBeBR40NBghNyZpq53VM3lq3Nt0vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T01:21:25Z"
    mac: ENC[AES256_GCM,data:Dr+iXnXeLgr440CjD9+HkjsbnbYCBKQxnqrdNARS0AvwM/C1mf1Ty1dqedfO6CQncHDYUvZTXtDDegBG6UEwcg+wXL7jC39UxhHxkKvs24qwwkREHSHpP+huWlMN5IknIDK1MpMGDJ2wMw/2wtUcmaAiKdALsXiJYNUejiA61Ro=,iv:1cXEocPHoYWMfbSScsr9wPs5fH0rvl63AAv+3vHM/2c=,tag:AALEkp3RMX+3dpEREmqzDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
