apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: trino
    namespace: jobhunt
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:2XuyPK4PTg==,iv:eFvmbqO3fOJfChAkvKLXR3KOJwRfoyjO5Qjdg/zovS8=,tag:uB6kYnFY8A9lTXQhDJnx/w==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:mBzkealnB9ZxvwEY9BSLm81f1jI=,iv:T+6G271dT3CjrrbzGzc/aqzQUfTP/pcQ/KvdCJ+cc5I=,tag:Pf2vOxbR1PMVTP6zErWc5Q==,type:str]
    iceberg.properties: ENC[AES256_GCM,data:wwk7xTmwa2Vozy9QA5ChVA949EwSWFAqRAJwkYRGWv3ZEVZeOcANjeMBzy/aNEbl1wDxl75fE3qbgER+b9Xhn4d1vXeH7NfxwxRFHiqKgRCYGSDg/ol6moLkFgXuBRHNok05F7Ug+0fv33H7OVrBebZ+6ZUXlVOAORyyU8HPMj0GLD+W1aYQmwMP+AdN0SP/DgcxK6T8npNaBxKE6rGPfjJhKTGxb4HWy7HM1Coigs1R8A49QdH6KvZRTITrrI3QWeR7NxMxrtA6YEcycrcLzzeuGvcM4nP6iwVARPruHHRK1epoGbT8PiwXixsInsc0DRi+Qi3F/etx3FWLKy2uOdpC7mLKHrWRqtXLCijvsbVPlvjBWweS2+y5osXbbYqH98RqmEl0asppq1Rt9LNutkapjMmmC2/6xdkPqjSFSBfYs8wjXeQqKziDhiQFGs0haLGMxXl+UrBRUdyztovs0H4sgGwR+EUI,iv:ligH3nnrsJkpXgy6wgSeVdijTuuswLh8Blpq6VVH8+c=,tag:PJ84Sf/OYqsC/VFocPL7LQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWmRxZ1hPSDJDMWV0TVI4
            NTA5bkc1M045ck1McjJZZmdacmtEeVR2bXkwCmtBU0ZpS2tFQ0VUNWRTRHJITG1X
            TlpVQWNPVHUwV3pFOHRHMzZyUVYvQU0KLS0tIExIUCtXVGtGZlN5MmJPK28zaVhx
            cWpPOXJUT2xQNWswdUhDSTA4MGJjeFkK2ZAwi1k4hMyimtc1yGKHOQf+slth+Odt
            MpIdOXpqPRyNeVXu6wphDzt40LQW8R5Tb7LJwV9q/BRVfyg19bXtsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T01:37:02Z"
    mac: ENC[AES256_GCM,data:++FzDqtpqi5BztZ5BRD0e4izKXVZW2ChOHyjEXVaa6QbULhSmg0AdnQ1hk5uNas9Ekq3nVf/2tqVyXJsftERh0iTeO/z7UzaemTL9e661h43FzCcNYZ4m3/viluxkNhhru21Alen5kFZUFbRYC8K9phCo610ODMZzd1Ouj7Dgus=,iv:WJEGNd861g1pSzTriSGX9IvS+cuQfC3pKfkBgPPzEGY=,tag:0iFsUGBMPkDQsR7007Qwlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
