apiVersion: v1
kind: Secret
metadata:
    name: kicad
    namespace: home
type: Opaque
stringData:
    SELKIES_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:6YJYKbuTZh7b1PswJrpd8/9oSbsgNCBbGLn9tABC9+8=,iv:MNvv6wHgkhyxpZ0OwCVzLMwS9gGB4SkF3NjDIEEeYkY=,tag:wzUtPS8ZuMv062HHIPjMhQ==,type:str]
    SUNSHINE_USER: ENC[AES256_GCM,data:gNqfJ6N1EGdjWnI=,iv:jv0wLD5z+gUHaSYBmNLhmRT5t0DfkI2DK82rrLzcNdE=,tag:vufwQCQ0fFqr4oWp5UhkCw==,type:str]
    SUNSHINE_PASS: ENC[AES256_GCM,data:3Lv+F9FqETlGZn0F8GG5zMAULKcjOiSaVG67aIwR0gQ=,iv:ji5cKiNxf90oWQsAB336AebcnoQJJtKAZ2wm25tIR1g=,tag:DyqxNmfe2n3dBmrYy5CAwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VjFqYWc0Z3UxVHR5czdl
            cE9ZTGZOMmEycDNtTXhCejEvZHR0bGhvbDJzCkxNRWdKM2xuMkMwWkhyZm5IcG9S
            YzdLMHQ5TU0zL2xrT2V6MS8rQ0RneEEKLS0tIFlaNDJVM2VvWFFFZXZBdGIrbk1i
            aEZadlhiTEFGQlNQSDQ2MVVLZVNBRncKnjLS4h4gd71PVyDqc2VbFTQQRW0NGRdf
            q5/02lbUtVj5lYeolOuu/Dk8H+rRnGrAOAKLf5aelklAuQhDsS3W1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T17:32:15Z"
    mac: ENC[AES256_GCM,data:DVQcc2nJz9FLiQLPux+3GWRRDS1MXV6u95zo9eNrRWXKz54SSXpiQtoEoAOfEYXNjdgpdDKs3PtuKltZG9P54NOr0bWkMmw5E5GbrjNBW5Fu3V0q4jb1b7Qsbiy4m9ljE/gRPJiHvV6MpfnViKWdBzQg5STTq2u2ax28JyC+ifk=,iv:oQELPzDFkefoAoCzndFazmfco/nK8I2fByWitwGkzro=,tag:EKeKjt2XaX3ugKNVtGrrOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
