apiVersion: v1
kind: Secret
metadata:
    name: rathena-renewal
    namespace: home
stringData:
    #ENC[AES256_GCM,data:6wXSYVO19D6zlHZ289dv1bx5sliSscvIoXvGFFhfEgogWPVUjuR30qeE4HmE4klRLMR1rh1TkiWMmr0xtnM=,iv:aPRDWfIFR3v1qxk9zZcIYuZtbHLPOu98G1xpi0A/IZw=,tag:Fb0lFQ434puu40sBWjivmQ==,type:comment]
    MYSQL_USERNAME: ENC[AES256_GCM,data:/zJynElCDNI=,iv:KoJX4nMUg/OBlwh73eZS0h0uoY2wQ61OBuojvPrCFvE=,tag:gQ41HV0yeAh3JUaYujXsvw==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:IyGkb2FQTSqkcVEREEk0erQ=,iv:gRaEtJoT2Kn3ziA7diBFYvQOXB5sGZ2D0WhJfHX/TkA=,tag:tMSOvyPms+7DeY+3sFwWkw==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:H9enuKfXm8Wbp0t36VYC,iv:MF6k1evKWu9IhOwXDwjGuNlF29OcwBNynfqm6PptwA4=,tag:tVbWoSZSInmCA4DA/7NRqA==,type:str]
    #ENC[AES256_GCM,data:mDFXnSZzjIy58gYiSoCKLK6zxzvu8wVP3Z+tzS5nbpzD/kZfncb2y5+t+sLK5hvIUmT3zro9OnI8RHvkc6s=,iv:53ENaI7/6YteAZwIEqGf6qHjy/jKrCx6W85SfS3dXZA=,tag:5HS6Q0NV+wvAP+Otw2f7wQ==,type:comment]
    #ENC[AES256_GCM,data:2XXSAHyh4Lny,iv:TmA1DFMQVqf3xTeCbIpV3p+CEowVCjbYSAJ0LvfS1G0=,tag:X2oeIlL/269clczXRSz89A==,type:comment]
    SET_INTERSRV_USERID: ENC[AES256_GCM,data:jAU=,iv:BBZPM66bVZNMxNiT7VUZVJlL1sfItuJ10PP57e2XKDg=,tag:8hpt/XlfhjSgDJ9KZqJtgg==,type:str]
    SET_INTERSRV_PASSWD: ENC[AES256_GCM,data:lFQ=,iv:qyk22IzkLVKIZ8OpkmuUw2Jn3kLixlZirxWPXvXxfZ0=,tag:BLus7rD3Oz94MZpHC93Zwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbTFIY0R1NWpwRDFkS3ht
            R0pVUnFKQ2o0MFdaTUh5R2JxNCtQUjFGWVdFCmo2SHVTQjlmeEpXdzdiU3lHQ1A2
            VFY4QnptS3FxTHV4T2k0dENiWG1VckEKLS0tIDdWbWp5N1FmTkE3L2V6R0FYcE5P
            SHBMb2liN2U3RTcyQnNWNU9zNEVMaHMKKJSnOeLJ4Ob6rq0voI6YCRXENZunYwEb
            btCxoHiQnWpOmtBsIbw2MBvGofFV4gryiw4J60v5AEeQtEqmlk1CeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T20:27:05Z"
    mac: ENC[AES256_GCM,data:jY5cxpqKsf69epl9ZVYEE0bfnfmEmaaAwj8bHZ5FHcnJTEZneFvFTZZzEDU86iueuPNAIB5kuAtK/eUV/HTMBATh/yD8LutZpb1O50D9BTCamSOkIBHWxg8w8uvh2xOeohQegEUnB+WhzM8R6Knh66cqwAxcBtat/l1Ir7OOxb4=,iv:nPuxY6WJZ2VAnuve8XzMuSy4ad3MyfivaY4nFxUxo1Q=,tag:WkyZXv91WNvPACnomusnuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
