apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: openldap
    namespace: networking
stringData:
    #ENC[AES256_GCM,data:fRjZeffbfcB9jfja6PBXu9DZkN1dj2eRJnZ833hfK9tV1NIVzyIAZlSJC/7gmaoAJx2YUMDRdhnlmyrvtVJCJZt/ltBZ2G6DBxM9,iv:LQEM9R+VRpHBi90FoN2RsOq3Av8KssYnyTtjfyEYY7w=,tag:c3MZNNfnzV6vBBBEtdRVJA==,type:comment]
    #ENC[AES256_GCM,data:9ylfyZ9+BXmwPeiyUqSguKnc5TKwYkRlLiglUp3sFiuskVUwdAl9wDH5bpSyKkJW8KcAL3iBI0st40dwDEB8xhfD3pSIkr+LCUunCtTFYg==,iv:2L2uEefouERkWzvC4QdyRI7/f/61GawpeGIKKgful/E=,tag:i1oXKIXXhASk2x1Mon7Kqg==,type:comment]
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:bl7pUbjtIUzJLpKaupMD7rUG,iv:/aX3s7EtkdsPJ4J18Wr4rxgwaqRrbTc8eUJCtFmv+9U=,tag:Wi6Gi7ULfUzEEdgeQDUcZA==,type:str]
    #ENC[AES256_GCM,data:MnNn8E+GjDWH3wcdZFJTNAHHuNbQDttNwZ/hLNYGY7Pa8kVSE6zyfdqAZfsOxYfKCphWgEs5IYdnVUvhXnH16g14fg==,iv:aqRO+0zvws0R3B3RDy4Qo1fkY4E93MoWhRFzyiJRpA0=,tag:mHosHCAKfIfKkL38VEbAgA==,type:comment]
    LDAP_CONFIG_ADMIN_PASSWORD: ENC[AES256_GCM,data:wgcXqbZwibtz/eSNeNt3w/NLG9bJ,iv:622fm96ZZFNi32VjNV4q8WqI32PESgPoOGQ9KSN72ic=,tag:/AP5xHNt3F9xkME0OJJiJw==,type:str]
    #ENC[AES256_GCM,data:xd+Qej1yyq6JbJbyFJv4LzebQ832GHq0PWk8zzGx/ruxDgUNXjmlg0g1r7NwWIRgfOq9slX6yn3e9u4j6tW1MvEX+LhPqOY=,iv:ca2r58T2AE5aoYk8/Y9l8zzwdyuzAE6NINQNLDwmlnc=,tag:qTmEboj6fRP8Eta6ks7igg==,type:comment]
    #ENC[AES256_GCM,data:qRwe30nrpAz8Hmu8ciPYw4GsfOpCaHrAOe2QLwPCAXUZSLEez61YGuN1GaKdBqJb2KeGLXqHNGYA/d566qpxZOo=,iv:VFue4fD5wRLurC7XRPOHdku2gVOMaDN3dzJrn1OxEB0=,tag:4eR9bs2DOIWya2irv9Lr+w==,type:comment]
    #ENC[AES256_GCM,data:suOgJQECfb7nTnD1lJXwUm5jnZPCws4aBQU5Sn9RWrUs6SklmioZl/4TjjniCIiYE0hjVYeTyIivDV/hkX6f7csHYqjzF5zmFyA=,iv:iepzlCBWkxQ9rvolG9onlYOnPnhkfqhs9LlNRvix+x4=,tag:679p4Hq0MFyjYrPlsL+zyw==,type:comment]
    #ENC[AES256_GCM,data:/h10M25kCJM0B99ckclLwlzH2xjCQwNnIRgMprxlrsx6gf67ae5aaFwJOjk7K0l8+nwopnzkJWpewihskg9SFE20XVwNmA==,iv:DWMdJ0V6uzP3UaOvk4NsXIsS8bnCYMhNFwfHVsluTLo=,tag:IDPAI989NmpJUlXVo60fCw==,type:comment]
    LDAP_REPLICATOR_PASSWORD: ENC[AES256_GCM,data:Zw1biaYWYJUr2Ike/fe/U7kn8yMtCrxtSiS3lA7+CuN+4MXSI932t/GmbgIe8E9sBB/h+SFeSB8QnImBl7fmfA==,iv:iNPrb9GLzQ8u5kHV8BK8/X75HeJG1XS1Ube2SIyH1UI=,tag:4D6FjEUoDGL8r0IGErKfFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNXpTd2UvdkRtQndobW5X
            UHJKaUJPYldnQUlrQ1FuVmJDeUpycUxLd0FVClN5bTdmMVpTbTFOMkFrcGMvcTBT
            QmZxVm1XNGRoUkRkNXFTU01yV09rYUEKLS0tIGdmZjNINzBhYUR3aWlHdkNPdVZy
            QTJCNCsreEdvU2JYQmU1R0g5VmVKMmsKuVCLGKZXy7Us7gkH4VVebBOegUVvtcgn
            eb5WHTSy07XVur8QHFEQH3qmGpvggB1L6AYpaFMU/x+pJdIkFhTQ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T23:32:47Z"
    mac: ENC[AES256_GCM,data:EL8gxYxZorXIdPuboInz9/F2X5YKVQn70ZJBruOO36cJcTUakbJGSsekkLwklu401KPC9LWSFgTOMtSAYI9lODYBQUZHFr/vBVOwTd8kgv6gGP0yp/eRh+T2lTQqCde8booOVTp0wol6VCgNhTUrZ0PnF9azIZpabIQD5hN/K8k=,iv:MR8nNfQj1VP0Cav0iuK6qQ62Kgll0/gPdYfJ6d7k7XU=,tag:9Y6p5vQmX4eF2dKZxj5GoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
