---
apiVersion: v1
kind: Namespace
metadata:
  name: ragnarok 
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: openkore
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
