apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: aiornot
    namespace: home
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dmkoekn6UZiO,iv:FFZQ5OpOKLA8OzLDzMXPPUuP5JK6PzBgVKuvc2r4Ybs=,tag:5s3c9X+zS5F4s0c2vaHhbA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7LknE08Hcty67M5i+Pyl/mwu,iv:EbiIJ/V8iRfnvbcVfqVC7AbYLR5JRnKEuCb6uCDaD3Q=,tag:iYL5F77fONJmLMmxqYio3g==,type:str]
    ROA_ADMIN_PASSWORD: ENC[AES256_GCM,data:9OTVTA==,iv:Zdw9SdWA8w/qpU6ksHbJau+3sY1IOCV4aihFciXE/ZA=,tag:FCJo4Quj+w9q6BqjDnc+bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdnJIRnFWWGxLc2lZeXRq
            VDBaM2NMTTFIMjNrdjR2SE4xT2ZKYk1VL1gwClhna2VDZ3RVeStWdnl1eDFwRzM3
            czBONnZGR0NIVU42Ylk5bVRkblF6TjQKLS0tIENOZTAzOVhBNVlPMVJ6K3k5MjR2
            M0RzaFZkT3UrQlRZM1VNRDZhY0lPMzQKFv/I8HAUo1AW9o7XA4Je8cr6m3VzBTxT
            PSUuyWWNRdXHWFowjqxFVchPdDTbJRTRuUwrIIgvrolQBxhiarYq7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T07:09:54Z"
    mac: ENC[AES256_GCM,data:pG9BZTiT6TYcmcVjRzVGFPj9DJMjcmWRTzq46g1bXSm4YAryi3axVGjDxZ+qezyLKVvtfo84Q5n3+yrO/LYvO1z0V4ND9ebYSQwame3T5xskDWWKewVPKE4QTLaCNT3Yy0MW64T2zbfW05D6IJj/hOKWnZIicV4buHv7XPPSrjM=,iv:SpPJlMAu0xXb8HPv0hM7mMtu+1k0p+Sw1u5LgUPLNc8=,tag:veW/oozq4IqzQzlvK6ZcKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
