---
data_dir: /vector-data-dir

sources:
  kubernetes_logs:
    type: kubernetes_logs
  host:
    type: journald

sinks:
  kubernetes:
    type: vector
    version: "2"
    address: vector-aggregator.monitoring.svc.cluster.local:6010
    inputs:
      - kubernetes_logs
  journald:
    type: vector
    version: "2"
    address: vector-aggregator.monitoring.svc.cluster.local:6000
    inputs:
      - host
