apiVersion: v1
kind: Secret
metadata:
  name: restic-config
  namespace: volsync
type: Opaque
stringData:
  RESTIC_REPOSITORY: s3:https://s3.amazonaws.com/your-bucket-name/restic-repo
  RESTIC_PASSWORD: your-secure-restic-password
  AWS_ACCESS_KEY_ID: your-aws-access-key
  AWS_SECRET_ACCESS_KEY: your-aws-secret-key
