apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: tabbyapi-models
    labels:
      app: tabbyapi
      snapshot.home.arpa/enabled: "true"
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 100Gi

