apiVersion: v1
kind: Pod
metadata:
  name: debug-model-mount
  namespace: home # replace if needed
spec:
  containers:
  - name: debug
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep infinity"]
    volumeMounts:
    - name: models-volume
      mountPath: /models
  volumes:
  - name: models-volume
    persistentVolumeClaim:
      claimName: tabbyapi-models
  restartPolicy: Never

