apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: librechat
    namespace: home
stringData:
    MONGO_URI: ENC[AES256_GCM,data:5UC9FjbZC3AGrCjp+OeMbXhpf7I7GVrYW7QcsFHjL9OD0xRq8ATSjEBBqegmoXK5pZfz0vVaqTyeMKZ87YbxOXK4BifCtbxYg11XyWmaB+VNz6GRwJQoLGxHEzOlRT6dLP52z/LjKTXbb1hoPjkAjCJlHPDI5ZRdw4WUySdI/C5yBIlClPiP1eT/b3yCZBorIDQaH7SeDQhyeMnvI53RPRzLQ/GN/HkauXL6qBfN1n27Cg8G9mzgZoJfuhPfF0JtrnmaXT1YIpr/05Y9,iv:7gxI5YEgCI5QVq4lyrIH0U9bgCiY4mnxTLhF/b7/kzk=,tag:BDg951gVf1MiTDeCYA8aew==,type:str]
    CREDS_KEY: ENC[AES256_GCM,data:yAkNO6/7dqtvuVWyRx1ezbLA3PRXLBXFWTusx68FoiW/5UsCZVklAwv8ozfcj3rXU8zpJlT9bLI6imzEW5FFTA==,iv:MBK0ZXMMeqbkxOFjs0MEJbqQvU8BTYeLsU63nZ71FM4=,tag:LS5yCpvNWyds6m+dA1NiMQ==,type:str]
    CREDS_IV: ENC[AES256_GCM,data:SOYP9O4WOunC13Ev0xTCOKD3g2ktpsXnXxYNabSfk5k=,iv:CPbUBVx1VbIQH2AlB8ArsJs7xlmL4cInrolovUT2l7M=,tag:Ig9UlCyfvnS3osy3W4HOSQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:aw3m/lhaPbHo6R2QxMvsmDBCdiKXgxwyDE9PxMoL9pzrmFHOFkBjD+SSVIO/Qmk0pBHs9+84yIZGRc6suXkKVw==,iv:u9ig8AQGiaORF3yD/26v9LjtLRV/o1QpBg4ZDJzmmpw=,tag:23Oqci8D7DJyxsmRr19u7Q==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:BsL8E52jDqb06GdeYytbZYdHZYKKWRRmo5R8i93vuFxMlZkiHKNfLdr3XGKvzxtVIalONcYKUHP/5iQWMqXjyQ==,iv:JnLDKUok110J2jaxDYcxr+3hbhwNVFInVxz5fzXak3k=,tag:FtZCGdnntxLT+LLfSPtMcg==,type:str]
    OPENID_SESSION_SECRET: ENC[AES256_GCM,data:ztr2SpPo5IkKShfLdN1qK4WeQ/Rq4tZnVOYqyPB5Y5Pm2xUG99ehJT99Dq1+SON787ojyStUzdmjNMUTU+9jGQ==,iv:CX3tTcAt+7Awywhp++ZXPhpOtFYkc26L7QSwvRETpJo=,tag:GH41EOQWD9nG1A0oUt0YZQ==,type:str]
    THEKAO_AI_API_KEY: ENC[AES256_GCM,data:CJJ/M4CTXMxvcZ86BCpGjwjmqMD3yvjuvQ==,iv:xcB3/Te3HigoCPVkcOiPH3Hx84Sm84JDOD210k8EvVA=,tag:61tvs5O09aGua+MI8YH5oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZVNCN2k3UzVMRkVhMUY2
            c1Z2Ulg2TjBUanIycG9tOUhmQzFVZ2I1WDNzClVtR2hWcHBMckZMT0JvZTlBTFlo
            d0Z5cFpPdHBKWmNCd0tycVkxSWlSQkEKLS0tIFk5T0pkLzJORUZVQ1l2R3FFRmFt
            SDNoMllvVG5nT1hETzF0K3diQTI4eDAK1O3KFxZ/h1faQnhWWMNc7PoUoUqxWsRX
            b53PWKwDNHLoX08eAk7+iKmkMYAUQZlVU8hNeFQoQCZZN0DcB758HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-16T08:19:27Z"
    mac: ENC[AES256_GCM,data:YkHbZ1GzQuXcM1o6J/iHeBZJotf8MO6UZOn9ANoNgISSml7NeGoXzlJAkGIULfN0Djd0c0WcmXEP9jj241QjMxDjmCxY3pCwriSpKpuVPHpplR1h6Qj0Qk3+SBMmGDWin3LdMCjNd5RK1AjQ4K/QJGf3UwmYdl4d2fucXhsGAp0=,iv:yUnxuOGXgPEVUTjBmE8aJMZGQvf9YbgyvvvSDzGaKIc=,tag:VBj6JWcapMYY5+dfSjCHcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
