apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/instance: dawarich
  app.kubernetes.io/name: dawarich
kind: Kustomization
namespace: home
resources:
- helm-release.yaml
- secret.sops.yaml
