apiVersion: v1
kind: Secret
metadata:
    name: dawarich
    namespace: home
stringData:
    DB_ENGINE: postgresql
    DB_NAME: dawarich
    DB_USER: dawarich
    DB_PASSWORD: rJBC+sdBwl3a08+N+K0RLyICnSCleb9N
    DB_HOST: postgres-cluster-rw.databases.svc.cluster.local
    APPLICATION_HOSTS: dawarich.${SECRET_DEV_DOMAIN}
    APPLICATION_PROTOCOL: https
    SECRET_KEY_BASE: rQH2iRTFD5D+75VVYrPE9IR3ohCgqwCNMn3mNny1fHHmWAnxFEDbjnC/9gGYlFSE
