apiVersion: v1
kind: Secret
metadata:
    name: dawarich
    namespace: home
stringData:
    DB_ENGINE: ENC[AES256_GCM,data:zUW+8VpspxgPMA==,iv:AHdFSDYfvIpAFlOF+lGrnrFmaqME5GC4c5ChyWkwXMM=,tag:5klmL4kGktePaaz4Pq9R8w==,type:str]
    DB_NAME: ENC[AES256_GCM,data:XvXzPv5Cboo=,iv:c7LFCDBEAbIjDq8DCLfHSLyT9uGoPrdCcEH7gTow0T0=,tag:cr6pPWAZgLwN4WWX70w2NQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:nwhUJrcuzX4=,iv:hrGrnryiNhc4yc+VsvP0MsYwxUHh/vr30P1FHeRUEFM=,tag:SDLwhUaFMYlmlu7brWhBnw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:fcORL/pyeDJHx2jf4z+tXzGc31bNevzMFlYgRIgTwKWFD6TA0DJdTvuzkViHiBfATxKaHE0JbW7ZaLBTce6vMw==,iv:DRqqXQeK+jgoYXMZzhL7ttzB7N8CnX49HfXhyoX3MMM=,tag:zRW0QYWWTSMGMXlg2PX1jQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:nzUGOlvhUiGiAk4EF7Dthaf3Z0k27ysSJBOWvnvKSoTI/dtAO6bAElE00nt0fv4=,iv:WlWi0Gaq+iM0J0cYMH2gVoGwRQX/0tUCseSqcgaX7jY=,tag:N/h+kaPmxGSDGht1qL+nfQ==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:MiCq9yRE54fp/9khL1jva90QRf98hgcTz1ro67koMvg0vzNytxAa2ksMCxFvpH8=,iv:id8zbfFmDL0OW2aIiLfG3WoZ6fQsgy/HQsUyi5QQ+Vw=,tag:dvuZVp4M6bX/iDBexZHIFw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:tXhsoAPntmzvBeGcFvpYtMv3N4JtPiO7I9jacLK9vCGB7OO6cozzQuN1MtAZ07Hww2Gw7Q/LwL/3lFBEBBKwwI8EjA==,iv:bv55sHavN25j+H3KGr/e0WO6KhSE6ywge5yGVlLFjjA=,tag:FhDrU5NwGxnUtR66OmH5Gg==,type:str]
    APPLICATION_HOSTS: ENC[AES256_GCM,data:xKHSV1secZVpaIHy70xI9BFnl/payiCPxaDSVRKOH1coTkOoy8jHpg2imFBOJSKJ53BgkA==,iv:WLUXwbNHjeYO74knNcux234qRSCruQJxpF9f3DYiryw=,tag:jpdTzhuzs9THN03hkkIQTQ==,type:str]
    APPLICATION_PROTOCOL: ENC[AES256_GCM,data:bd0qs00=,iv:p5xNB7UMfNLt+vmVZWnT28uFoQ4zlWZBE7w06/Oqd7M=,tag:hsX6HOkqWp1OBr5qg48MNw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:uVVKU303IKs6IXCQnITpHXQjzp7303nKg4s0sSl1i67jo5c7TuWhnjBsKMwe5dUxBIDB16yfnX6NDBIGlKZR+A==,iv:Fq0wg18QjX9jyfptrAIkWpcGKB4X88Uq5hk/tStS9fE=,tag:1fWp8hMjQ+04byG2y2mj0Q==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:Ql26SZQI6AQ=,iv:MRyQ5MNfvA0b4FojQV6L6HDPcpfpl3TnZkvTQFSw4wc=,tag:AqXxYKrXYPvwwxD0VNyb/A==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:rdq/f5MaND873B4Rl/ogm0pF76qrFPwU40pf/NYOwbYfc17WxzU=,iv:L38x+s28NP58RlETy60YzcfW09ew05AtvwGXecS0SvE=,tag:SwYuQVL+bqetQasnpbH+Pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bnZ0THJCVnM4cWI1b3l6
            ZjZrT0hJSlkycnl1NXVVOWFLNTB4aE44RlFnCkwvVGhtZU5qek5UU09RUHg0SHNt
            SlRPWm1uWllCMlVFN1FlcFdTanJKWlUKLS0tIDhOc25uNnBocGZpOFBuVTlnZHgr
            bW9qc1Bna2hwODJiYmNzWUE3dGFGUUkKN9gwhoXq/BzGfoLe3gfT3PzUQUHSAeLo
            ZQFAGDN1lWh13lPgj6xvzOeI6ueH9+iYWWFYhOyvXR9fWpR5kMoXBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T06:36:36Z"
    mac: ENC[AES256_GCM,data:8pSh0q6OxRaYVptoW/Iz7m4tf4qYXzt3ce6t375+a2wVRfTtXxieemkiyU+V2LEpg/KKDnGd77UQ3GHKkTBPR5eF3YoLhqBumtRhsUnolHKNNvgIf3/6yH97/GwmHneeamUTMUIlzFvdc/jGtQN0oAubnlxAvi5w/luIydfErn0=,iv:eBeWb7gcIB9EPNgmlBWX+nzIsaVOntrXXRHXzAvUvnc=,tag:aO/cZAMC6vgy7vo0lmXiKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
