apiVersion: v1
kind: Secret
metadata:
    name: dawarich
    namespace: home
stringData:
    DB_ENGINE: ENC[AES256_GCM,data:VdA1OJ7x2SkH/A==,iv:Wfd1/DS36kpG0PDNqCxW6KZmaRjCt/XFd6H4z7nlv54=,tag:kEmI/Rl9iNwAB5wdKAM9Ig==,type:str]
    DB_NAME: ENC[AES256_GCM,data:1N2TztXENVU=,iv:ttOfZ5ueQKFnWWmR6nipgcMlVbK4vhl0XetM9/5WEYk=,tag:6gs4QMSCzr/BpTYoOupXfw==,type:str]
    DB_USER: ENC[AES256_GCM,data:bc7SDSSsKlA=,iv:Lx+QFMEl5et5L8TkC46rBZ6EiW8c5eBmHCH7qmaYt2U=,tag:+/Tux5o8FLb/QswXYIzJKA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:6c87J++q57H2xVcKj+RysREmtJUvjpHa2UECwE34r8S1anHXJOzQkfGUAohTlXRKXF8lZg0KJF1TiQpv3Q30IA==,iv:fGSy2QDPkGqpxkas6fF2N2m1IlIHDBfE0XzuFltjpB8=,tag:oi4062JhqgM9Hb0dIaAGWg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:B6Y0LXNB8m5KQDGLw+1Kv97rv0dF6d43qDXhNXPrdlkDmHJFfM4pjTMHFaiAxqA=,iv:G9kiHofwHS2loZppqtRxy8sL3TD2TIAryyCW4nD24OY=,tag:Y3xkG4T8HTtxemCYVF2eog==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:+D7Ajh/gIBCKWxp4ht6S2QK3R6Y1Tp5wFVvHxa6Nm+o3ZLKzWWLdNI3b7ZSD0WY=,iv:VFgszmwBzzsThxDvM0iw3+KOQdflWyhCgJ5L+6gu4E8=,tag:h2ik4dNe2yRdgAsqyxlCuA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:jE4qsyeWEitdYaFZT7UnfLX3CMFwIew3Em5IAD8hsk8lcryHM8Fnr1zsgSKwEz4TXeeobPpgeliUrpdC5q+Cl7w9HrK7hKk3,iv:5xM6/tjwnYR5aSqzMZvM+Rwfo7K9RMjzc1vIonxcjpg=,tag:LmuW1cLqLNILgds44lhnww==,type:str]
    APPLICATION_HOSTS: ENC[AES256_GCM,data:N9cXwahlaZC9Fy9Q8r6yQnPT41F2YRJ720di5f9UCI33syLszwroZDXH2H5FDGNXa386+w==,iv:oRv0R2n/J3X9ZY4U4d1n/nJH9CLLx6Bc6Is8zH7ggWA=,tag:KzPqnxTz+qMZc5CGqlUHbw==,type:str]
    APPLICATION_PROTOCOL: ENC[AES256_GCM,data:z2ceLHg=,iv:BVMbXMp26PAT5CQG8xGXgLk/AmmVASn0UDg67LXDSgg=,tag:p/ogT3FJ2DspxbyoKk+1hQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:ie9MRgqAD/NvIrfKechw4NZEsacg36y+T8TEmtbrJZs87CETFKo8C3i3fgAFMsMXvKMgWpVHcyJOD8UdDkOU2Q==,iv:bx/ptt9w3l2xlGj8i7Mw8c+XBIJTX9fz2QBFaO+XPeI=,tag:wl8nySGIoBK/ttS3kaisFw==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:OaHTYSOAx8k=,iv:ZCL65QYHtczuoOKfvuoumhar6anv1dLW49hjlXZXZp8=,tag:vOCUnzkRgg8u/3HEOmNKXA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:RG4pIzuXlbDb9DAGiQtkJcRXiKMjE0Z/0uBh9NfM11Ys7dPOtUQ=,iv:aHAbEtFbAWshSTxEbAYuMqUI+LR4pH3pa68ST0pko4Y=,tag:SyIRiEvFHI0Te3vYWetcJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK3g3bUFkaWkxMUhpdEJi
            dTFmMnpTWVlHWVpVL1EwbTNMVTNORHVOd0VVCk51aG1Yd2VsNGxTQ3dnSXhnYWJF
            RUdycmhGWW1WVlNTTDcxNlZBY0lwUEkKLS0tIHlMR09vT0RYRlVIN2poM2dlaUdq
            NVNCdDQ3R2dlZ3lNVC9tOVZMaCswZFEKB6gekK9sfn5RJ6P7IAeoKVvDfvVk7EOq
            S1RH2o0tNGuVOARnBJArF5GZ/oaKc5Ei8ol5qHiuQpvQKST4r+Pd7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T01:00:19Z"
    mac: ENC[AES256_GCM,data:XDZ+QiT7QoESeoiupt0JGcfRBcJ1KIGtFoKQK7LZmrUjzst299jYg5n/jnr2DrQM4NDvjO4jqe2I9SpbmbeE/53L8Rpwsa9v5Nqs16oY8/UoKWs+KJWDgkoTJkx60EKzj34m1OA5RxGAlwEC4WBAyc27d1dHKWTevtY/7vTo+NY=,iv:CkiZQzgcZPjNirnYIduddSuC4SsXHQIGXuAb9/AWFWI=,tag:EQCQM4Z+i4RzNgbZxCEosg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
