apiVersion: v1
kind: Secret
metadata:
  name: dawarich
  namespace: home
stringData:
  DB_ENGINE: postgresql
  DB_NAME: dawarich
  DB_USER: dawarich
  DB_PASSWORD: rJBC+sdBwl3a08+N+K0RLyICnSCleb9N
  DB_HOST: dawarich-postgis-rw.databases.svc.cluster.local
  DATABASE_HOST: dawarich-postgis-rw.databases.svc.cluster.local
  REDIS_URL: redis://:59DpYbAdjpXWvbmj@redis-lb.databases.svc.cluster.local:6379
  APPLICATION_HOSTS: dawarich.thekao.cloud,localhost,127.0.0.1,10.0.0.0/8
  APPLICATION_PROTOCOL: https
  SECRET_KEY_BASE: rQH2iRTFD5D+75VVYrPE9IR3ohCgqwCNMn3mNny1fHHmWAnxFEDbjnC/9gGYlFSE
