apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
commonLabels:
  app.kubernetes.io/name: &app openldap
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - secret.sops.yaml
  - config/schema.yaml
