apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
commonLabels:
  app.kubernetes.io/name: &app openldap
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: schemaldif
    files:
      - ./config/schema.ldif
generatorOptions:
  disableNameSuffixHash: true
spec: 
  postBuild:
    substituteFrom:
      - kind: Secret
        name: openldap
