apiVersion: v1
kind: Secret
metadata:
    name: openldap
    namespace: utilities
stringData:
    LDAP_PASSWORD: ENC[AES256_GCM,data:29XKQaHtHZguyXh98H6sVaQkAtQ1uEzQ,iv:c4oyh41+vcavW5QKBy4iYPSHjWmXa4AyPKIb+clEYLc=,tag:VvCZ+gOIHea3ODJfkPCwqw==,type:str]
    AP_SYNREPL_CONFIG: ENC[AES256_GCM,data:MqtPyMG08H9Tea7e2LeOzx+cj881PZZ+DuPz8Ll1YkYgyanzAcmUu1jaxZGPU8lLcTu8hPEIxlbjLfumGRvhkmQId4eBaw7QIVD/e16cJE5v17Q04k+kJXEaK9Zl64GuvoFzVLQWbzXPvRvW66SiaXKUkiw6SfXZ0WXjJEz1xcywKCRzS/IPI5Jdl7xp7RQguEjU4eEPFXp5nOjfbagVoEm2/slCkWM8r8NnpMfLAU0HRZeEymQFAFntuAv7+ZJQHDw7x5PaY0ZOU8m+uBSgXnzBSzWbQW4OWSjLkwwRVClUrhGC0Tj12VE6jvH1uX+Io9BaMn4UBF4WSOryjArvYl9tl7raaweq3mMSSxWS6x5KraSeokpcxU5gwVxwBmiVJ9zuziwC2eANX87AA+rKETxkTKF5qLFcq+vE4fvEXJxT631RkJNV/SLszPDiGkfu5rmU3m4XfW5y5mg6H6DJnq2+RSdIhDwQmYtXW0JbZffNx1UvDnuZTdLi5l1N6o12xrkJjuVqv70BYf+Oee65tkeZXosogdWw7MY4vWzv21cKAH0D7BCpA56vzKGGgJH+rbD62ZF28ympJYJPys2qNZBQC3s6vqTAJgADpnLg2eM9CypSjFT+3AW8t04iOTIwRTk1p5gdB4Dbs0hvgqgpyemJz5IXgMX+1DQFoWerzcBG+hpuPs19kqOIC3H6UbTg0mLYpqvJO0H6en5Mwx5Nt3a27RstSA87UgKlNlHqOR9XuxnZRVi8rhpkFZRmTAwBpWLcd7nEbguiAtxgEVq1wJV9F8sRzzaEqLPgvU7rDXoh6xQU,iv:GAdnud2medSb+MTKZCf+dwdLexJyjaWl0fIFLYC/xLo=,tag:H68KJQkWe+6nWP2Rndo2fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJY3ZzbDZGTG5OZVdFcFFz
            NGxyd2pnN3cwT1NDT3Z3SktZNllQci94djBvCjBOQ05zVlFYRXZSdmhjbGNHOXpp
            MFBVNTJzY2U4Si8yak91WHNZcjlaOWsKLS0tIHg2U0s2L1BZSi9wYXpkaHYrYnpY
            WnNFVnZxbEprNlQ1d2FJZnNYZWhrQ3cKZxbu3UvjGebvHjPIuyLwyQWf7OEjJKdW
            kAuxekJ6qeelr/brCq3qY2nqN6gTZCctiSjX4pXxq/49jAcZnTf5rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-12T14:53:46Z"
    mac: ENC[AES256_GCM,data:W34A7bmBBjHf5qjq0/JCfaAcMj1yJqqwjsJ80dN5CsvwJJvQccBJy8pnwF335Ih5hZui00K5696c2C8mQaPJqBoElhJ1j/8h2XZyaxuUjwuyFEYMRkgi8u56NWJ5aWemmNUbcqgq76gHEwqsYKbQZP6TlOzTewkW07OFJ9bhN7Q=,iv:2FXfk5vjU3BUfeDrbrM+eiyy1nrOMCh+Zq0H8bKLH6M=,tag:zhu5042T2ShVjUasnWJ6GQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
