apiVersion: v1
kind: Secret
metadata:
    name: openldap
    namespace: utilities
stringData:
    LDAP_PASSWORD: ENC[AES256_GCM,data:tuFkwLBBcEKAk/mnL7sTemknMaO/HARe,iv:5WEhSojBTEhG8UHEDUipw8OEVnvk6FbHkN0G0pgTM00=,tag:Ue7HUV1WhMnLHAY+dXOsyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZazBZZWVHRitiOGhuc0lL
            MDFwYzFwYjFTTkhHcWxKYWtUTU1aTVF4OFZBCmxDUjVpKzEzc0VkVG5LVlQ2aTNH
            bm9PVTJDeVZzQlZ2WGRuSnlhMG9wTFUKLS0tIFQ5OUxPRjhnaGhqV2F4ZDdGKzRs
            NTQvUGNySFF5UHBESjhiMldqZkdWeFUK9Fs4ogMzmqBTzFl3N8VfAeyDVWKSq4Ir
            SeGGaTqIYJsgic4lxG+SsAl6yBH6p7n0zJrq/WP8CrJ4bHm18Wy65w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T21:35:53Z"
    mac: ENC[AES256_GCM,data:b/olbZsoI1Iby9jcnHL/R8nn2B+VS7hNJwhMatb7KZB6H20Nynakew8w+HhMpnZOLhsWgGJaY+8TfLeN662/ooKqRojKLFcio/4kHEKZPpZ64sDRoMrFwsP+ZYSmqR1NnuBHLTdLVjew4RzCsQjiwGLPMs5zh0MwP1ncHVDAU+Y=,iv:8CY7EA8bO2IpCJJi7DvqMkVfPlb/0XPRc91EwxLihlg=,tag:FGva2xFmXrAKWzOtKuoh1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
