---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./hajimari/ks.yaml
  - ./babybuddy/ks.yaml
  - ./babybuddy-pandaria/ks.yaml
  - ./browserless/ks.yaml
  #- ./dawarich/ks.yaml
  #- ./langserver/ks.yaml
  - ./monica/ks.yaml
  #- ./gamevault/ks.yaml
  - ./stirling-pdf/ks.yaml
  - ./redlib/ks.yaml
  - ./dawarich/ks.yaml
  - ./localai/ks.yaml
    #- ./stablediffusion/ks.yaml
  - ./home-assistant/ks.yaml
  - ./esphome/ks.yaml
  #- ./magicmirror/ks.yaml
  - ./frigate/ks.yaml
  - ./zwavejs/ks.yaml
  - ./mosquitto/ks.yaml
  #- ./linkwarden/ks.yaml
  - ./vscode/ks.yaml
  - ./vllm-classifier/ks.yaml
  - ./kokoro/ks.yaml
  - ./watersmart-scraper/ks.yaml
  - ./f1replaytiming/ks.yaml
  - ./msedge/ks.yaml
  - ./oncall-sim/ks.yaml
