---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
  namespace: networking
  annotations:
    coredns.io/hostname: "unifi.${SECRET_DEV_DOMAIN}"
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: &host "unifi.${SECRET_DEV_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: unifi
                port:
                  number: 443
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - *host
      secretName: *host
---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: networking
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: unifi
  namespace: networking
subsets:
  - addresses:
      - ip: "192.168.0.1"
    ports:
      - port: 8443
