apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: wealthfolio
    namespace: utilities
stringData:
    #ENC[AES256_GCM,data:IXSVlcapOwCxMHAhmBFS+BsdLGUqazv1qhHgB9XxKdaM5OCNLUBtwE44EMPctQxq,iv:q/APEbh/DkPoOZ67IjlDtqYQtZEAgO7zfqvAEDHZF1k=,tag:udV0xYxBnEuB9xLSJR3FhQ==,type:comment]
    #ENC[AES256_GCM,data:voaHvxHdFQLJ169gN/RX3IC8JdogJ/nM1EAtZYA99zYpgfpWe8HzpbgcCShY74lflNQi,iv:FAumlCmCtVBfijoBE754uGtwN3JAC91qpZNzazThWoo=,tag:/fXslepQ3C1+mf2WaXUqdQ==,type:comment]
    #ENC[AES256_GCM,data:OyOGbrFloUnz/VCNz/EChl9rX2/do6Ty+4uCmdXtkkZsxen8qRlfMP4ZDKvqcb/QL7NPXYANrZl/YW1s/8HEFWTOioFWQ6UyapPJ12DQrEd7P/yDEZn6,iv:GtI1XFaGkJlJAgDhlKkR4zwf8Kw7oPiYvqWqun6sfUo=,tag:X7jlcLE7i0mKU3FajK5Blw==,type:comment]
    WF_SECRET_KEY: ENC[AES256_GCM,data:qFHyaLxk8/GKZ2p6TPg5+Hvw3fh5WkztD8ESvSbHN2O/C/7EJCXkg/a5aCQ=,iv:RzOd9qhXM8Unhgn8bwLkCVtG4JTff8WBjWC7/0P/7kU=,tag:mgIX2xSd4VWs+hmf/GAe3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaDk5VU53YWR5QzVDTGJh
            SXI5QXAyd2hpWTlMZHl4VC84dy9GK2E5NVFBCkJXalZ2U1BZMGpqdVhSenljVVZs
            VUZWRHZaM1VxWWh6bHNwSHFwZk0zcHcKLS0tIHN2MnRaRHBnaVZka2FiNjN3Y0l0
            bnpycnpVekNUVytuT3lGUjBhaHFvem8KJMqxcG0iSV9B/DbDVwo9E7W94bvaETHf
            5I2joMoNE8hVEt7zI3+PONkGZEIP4lZMAaprIWs9rklxNClQVbXSIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T06:25:11Z"
    mac: ENC[AES256_GCM,data:wQATYFUH774yXEYJ+hoI1iU1kCvMPah/6GJ5vCJAS2auORXRUVLA/rhnmhebPul3Md8xhYEXgnP46PJys8A6jaLQr4Y2rRq8DItX5JKcvuOqw9KftsynVFA54FsIOUewJfLkUs3bie/nO/MHO1UMj6gR1DlzISNVHqTCDVyGyHo=,iv:tvaoCjAZP8fvmqXZc73mzPG/0FukpL7k4PHMW1VNnwY=,tag:cvBARPzXt316yLApZOWQxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
