---
apiVersion: v1
kind: Pod
metadata:
  name: node-debugger-${NODE}-nvme
  namespace: home
spec:
  restartPolicy: Never
  automountServiceAccountToken: false
  nodeName: ${NODE}
  tolerations:
    - operator: Exists
  containers:
    - name: debugger
      image: nixery.dev/shell/smartmontools
      command:
        - sh
        - -c
        - smartctl -H -i /host/dev/nvme0n1; echo ====HEALTH====; smartctl -A /host/dev/nvme0n1
      volumeMounts:
        - name: host-root
          mountPath: /host
  volumes:
    - name: host-root
      hostPath:
        path: /
