---
apiVersion: batch/v1
kind: Job
metadata:
  name: plex-restore-snap
  namespace: media
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: restore
          image: kopia/kopia:20251215.0.232403@sha256:57a5f6dde2b8bb21362547e6a2e418be5585ea4ebf3e0bafc1d0a0a2f30a3fc1
          env:
            - name: KOPIA_PASSWORD
              value: "none"
            - name: KOPIA_CONFIG_PATH
              value: "/config/repository.config"
            - name: KOPIA_LOG_DIR
              value: "/config/logs"
            - name: KOPIA_CACHE_DIRECTORY
              value: "/config/cache"
            - name: KOPIA_PERSIST_CREDENTIALS_ON_CONNECT
              value: "false"
            - name: KOPIA_CHECK_FOR_UPDATES
              value: "false"
            - name: RCLONE_CONFIG
              value: "/config/rclone/rclone.conf"
          command:
            - /bin/bash
            - -c
            - |-
              shopt -s dotglob
              printf "\e[1;32m%-6s\e[m\n" "[01/04] Connect to repo ..."      && kopia repo connect filesystem --path=/snapshots --override-hostname=cluster --override-username=root
              printf "\e[1;32m%-6s\e[m\n" "[02/04] Remove previous data ..." && rm -rf /data/media/plex/*
              printf "\e[1;32m%-6s\e[m\n" "[03/04] Restore snapshot (${SNAPSHOT})..."     && kopia snap restore "${SNAPSHOT}" /data/media/plex/
              printf "\e[1;32m%-6s\e[m\n" "[04/04] Disconnect from repo ..." && kopia repo disconnect
          volumeMounts:
            - name: plex-data
              mountPath: /data/media/plex
            - name: snapshots
              mountPath: /snapshots
          securityContext:
            privileged: true
      volumes:
        - name: plex-data
          persistentVolumeClaim:
            claimName: ${VOLUME}
        - name: snapshots
          nfs:
            server: 192.168.0.120
            path: /volume1/backups/kopia
