apiVersion: v1
kind: Secret
metadata:
    name: opengist-mcp
    namespace: home
stringData:
    OPENGIST_TOKEN: ENC[AES256_GCM,data:Q97FlkPMvO44v/v4vajfYqgxIDGc/GlUXRCG4sNTCEr68FJWZAy7IOo0e3lldRWrgJwCbCkMLfeKHjURG7h3Lo8w5A==,iv:vb5qM0w2fBdBlnjHeG4ZDM+iquTanGxJVbCruB59SS0=,tag:awcAoTi/0IXxCTTvWauZ9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWUk0bkM1TDdZeGRaOWdz
            T1Bxb2IxSUZXcE1jOGZid1hwK2RaOHdHUkQ4CjVodE1DVytyclVmQzdMNkd4S1V0
            Z3VKVGhadU00WEVGUVo0QWwxN3dxZlEKLS0tIGJpTzdPc3Y4WFFVdkZsYS8vcGhw
            b2RBeDBpNW1GaEgzS3hZT2VLaFpmL2MKgeiHzQLkObmyQARR2rg7M+SJb2RzB//2
            LfXZ/4hfgbSZcdeH6OFDne2IlI+02p7Wfgx9rTm1v8MYbtR1tYuh7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T17:06:56Z"
    mac: ENC[AES256_GCM,data:nO9frraqnWLT7sdrNEt24gt3H6TDFEjAx+1smPrgDTfNxHpU62WJwRGPxF2nWJtINhOheZClKNIWi8rIGJMHMQvj21jQ3S++jmLLRrQEScy6d5H2rfoE1q//Xrd7nYk+IU5zfwR2Ih9rJSNzPwE2DPBEaWrpkELHuecaM9Xr+RE=,iv:bjrBbymiHbtFnunFMI1wBGJQiNtPzzPBi/mLmkmVZt0=,tag:w4Np6e2QWWQhAzLGGcUSqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
