apiVersion: v1
kind: Secret
metadata:
    name: opengist-mcp
    namespace: home
stringData:
    OPENGIST_TOKEN: ENC[AES256_GCM,data:tRqXaoHc6iUu8FbAO9IXEmHKqpZIKia/pCr4pgti8LtOIJ57+dc9aaYBj5WYbOmsQ8yx3A62CVtnbaiePnHw6kBNPA==,iv:5y/BFAQKzNHe7Llx5y4OV/ERkNoBFXKVJbpASFh78I8=,tag:b8c0+UkOsBi4CKiqN4glwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYWNQTzVqRjdyTzQ0cTkw
            TE8wbEdBbWU4RmNPNHltZUI2bC9Ib2Q2UHg4CmF6NlFoMDFTSmoyaW13a1JFUjVW
            NU5tL1J1UTdidzRXTDVOWlMwTENoTVkKLS0tIFovbTlYTVBqL3ZjeTM0WkRndkFV
            RVQ3bU9hV3gvUDdIU3RyNHFBajZucjQKtQJmEuoklYRRgUcL3evyfIfivlrpBQ1g
            xf9UXUrOqUGIo7BYpZFp/BxZBCwpvW27VfhcZigFfK9IkwOsCoxErw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T17:06:42Z"
    mac: ENC[AES256_GCM,data:6DWA0uK146uyjm+7eVFjRa3bmwgaRI3bm+bV3gHf1y63y8Wa9/mgto3ZQZyeXDzT13QI1E/K1ZXlX6zHRzIQ7nc/RHfwtRsmsJcxRbp9TSGY+Br7SyYP47kIP1ddCSoPDOZe1daiFsOiRi6XFKcwCcIWJf/v0HvLIfCOl06kLEY=,iv:zFnYyzf99wERD4ZlzuNA+ccrJqCRzzh5wQ2yNIjqJPE=,tag:9Vrs3iRhC2L0vNOoVZBBjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
