apiVersion: v1
kind: Secret
metadata:
    name: opengist-mcp
    namespace: home
data:
    #ENC[AES256_GCM,data:WAHBws6UP3wTUmepdy1YZdR4uArEBIMg1WwUSv9ikdKtOhZwQ8rwcSFnrz2075yZ2AmFYf8jd2sFZvIUQphw9F/frw==,iv:WN6+ue1P+iXFx6f6ENeaIhMILeB4+/LE3Yb2ZjIeGG4=,tag:isIgNqg8zm7FvOKcKuRfAQ==,type:comment]
    #ENC[AES256_GCM,data:tgmkSN+XYLeFS3JgWNkGeNXFnju7yPrz4ciFA6A80wvvvk/S54Ip6shfGTNgj7IxFA==,iv:7zWzM2fDhAJDF4lkpUNOV6/NWT2DyXgLXVJgj4K3XvY=,tag:njvpkYIfkMVPbtFe2Kkh+Q==,type:comment]
    #ENC[AES256_GCM,data:w0WgjeoAA6f+Zb+P61pfPudmdouswIXtH456eRJnyNUi,iv:2kz+DD2ChZ/PPUb550A2R37wDvhF5ZaLcBFcKuS2PGA=,tag:iPJvkDYW50CahAQ88Al/5Q==,type:comment]
    #
    #ENC[AES256_GCM,data:+tsk+sDxVv25eVVpJNR6+MDa6d3ngd+ZqqT9LXdAiJytsDxkXHlFMF3jPfsKuzfU4CqEA7/99aIEpWE5Wy15PWn3+MHvVM0=,iv:5Bm6l/7YCDj69cS8Szp0Dkk9lXC4NHiaz9Oc9vSQvFs=,tag:g9kqBMQa6cSnGWTAGBCeKQ==,type:comment]
    #ENC[AES256_GCM,data:RCBebF0SpZ6bh9HK0WSWXGkdFqtgPCwsEKbL6TGlgQkm3IvPwFLcWbdjGcujNGl/d2cgKSeAj9YVA+vatCPJ1IzOuAudDg==,iv:Oys0kK/nUDHheSot/yrrkO118rbn8IIoCmsoFMg7oR0=,tag:cGY8s6PI+tjwhEX3bwpAZA==,type:comment]
    #ENC[AES256_GCM,data:t/t+SEfwDMyHtXA3luvx2cNRZbybb9S2YnIRUuhj1iPJWfKLGoRTyB6RkGdri8T1c0sLcbQBJHt+,iv:Fuo/p8reVVtFeakMRmyIVqN26YLOX5scPaxtdzbb4/I=,tag:EqPotoOKIkHQ5I8VHvRvsg==,type:comment]
    #ENC[AES256_GCM,data:6FVsNpYF9wak9bk8Q3H42Ws5Eqxwav07i/CulCAfkB65dZF0WimOjmKICruMY8EJiFoUOfFHVEcM3TU3axPMg3gncQY=,iv:125XsHOec/H8eVutT4xJZ/fBgmmp75Jqt8zj7s/DsKs=,tag:DHMgyKndBmMg65z7l8zavw==,type:comment]
    OPENGIST_TOKEN: ENC[AES256_GCM,data:NYSutUC8M24suFexn4gOBccJ/Ygqwc62YDmAlzZXmDoscqan2URmGDb/JseCe9ufC4wZlrmOtqKSg+k1Adxjcu0IKg==,iv:GAF4EMSGUNpfgStNllPY9MJ0AUZ11GMuhjIyCMxssU4=,tag:iXYhYnfojGYWrjlEtCoyjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUjA4NkVhWHVMRWRHaFhq
            blA5MWFNQm41cHRhSy85SUFIdzZwV3JjZmlnCnZ0MVVUdG1oeU11WjVQOUhaZFJa
            WWt0U3NQL090V25Yb3hTY3Nrb0NadlUKLS0tIE1rM1cya2VmTjVIUjEyMVErcFIx
            R28vREtkTnpyQS9Uc1MrNG0vdUVvcnMKIJjkELh8julrTKdRvX+WZZKJrkNztMwR
            e6lDmG8j9Zom558uR3I5YEgRIiXzx5P2oY98/gv0SsqvJcf8mpQ4mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T04:30:29Z"
    mac: ENC[AES256_GCM,data:L0ZgRmPCH8TUMwn7RE68gb3ID+9qT5ncKCxvTqiLb5x4E20Ap2RkCA3wlZsA0ubQro/M/INa2ftvwtdfOZAb7orzB6U8mHFI44dcZ0tLBWij3AsW1pTdi2N/TkLT9fI66sYkUAr0C52TKU1GSvOxNUzMevTC1fpSLCP4UtsBqoY=,iv:aXx7xXaWtWZYfKDDKucAmSIztWaBrLBVJ/j7/cUCzqs=,tag:LLqq5ROdgdtNQ28qL3Sucg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
