apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: immich
    namespace: media
stringData:
    DB_HOSTNAME: ENC[AES256_GCM,data:UGsfHzpsv1kghYvGwr8fN3q2F4mi+8hLTm3dB4lVolyERSLnu7ye,iv:NziyW7/52QGHtuufjfOGXbGZzhWcqgX2/xGlSESOHjQ=,tag:qpw1CO5Pb4kTbbvXCROqcQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:oUd2KA==,iv:XYMQ5dSGHaOCzvZkvoP+eHOr9z+2JpoSHN6MJ4xXzCE=,tag:F4fBRjUGy0tgPdpnYPZChg==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:u61X2qjF,iv:RIWem2AyEla3uRBtyLokIc1PGdFqQRAoVvxZbXfavkE=,tag:X1pkwuTyKiqyIlCQWsj6lw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:Yqkuz7OM,iv:piEcIsIDzINkZOOXtsb+iX98THmScP0TPcxV8yS6LlI=,tag:uZ5QTC1dgcJXdzhZwAaXQg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ATl9FOmcfHByCpLtJIZ28lXGj4P7cgQ=,iv:BYkQNJNcRmgjA+xyAfNTjqLpuU9surk1kvAySQsp1cw=,tag:1n2pAty6/cBo9EHXcqxQsA==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:vNyGjmZ1ZHfbYM70gnPmDe8dm07jjAe6Y/bO32u4rw6c2jsu,iv:y5fR+S+UhvJ8KYwE+pfs/ULB8FRtZ2JTLuWgyOQbmYU=,tag:4OGI+HsF0GlLTmN9leX5RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuL3FybnFRdy9ZZmRjdXIz
            NSt0ekZkYXVhS2RrNUJJc2J5ZnZoMWJOZWtBCjcySkhWb0lrZHFqeVhnV0dKdjNE
            OXRuMTJzYWdHNkcvUVFyekJmRS9WbTQKLS0tIEk5TmFtQjIrejRFbWtlbHNjeWYy
            bGlja29na1M5ajlVQVo1anZFL3VTRDAKYedm0cRajGYHnLYtTY2s+3nrxin9BCBL
            9x2T9d6/aipYJtbirTgCRXtjID61v3pjPek2BE3dsAFNO9onWANkug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T06:35:22Z"
    mac: ENC[AES256_GCM,data:bafz/NheKvuzIsI6bNTXcuHdA3ivaZIaMidnJOquTvt2wCihvRdZtmXGTkaSNh3hO2s0+7bgxR9SWt5JAJhIkeSwt1hju4kxCg0wJkOHkamZuCIbEFKjJbV272DUNn+1bGy4uWLjnwsxRvSXv67JqqNldN1CepB8QCQc41rUkZM=,iv:TKj6TJ80f0u3jyOGCrm34STELPrrs98NKkRujUxZagM=,tag:h0FNeT5BJADd4ikz30Z50g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
