apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: immich
    namespace: media
stringData:
    DB_HOSTNAME: ENC[AES256_GCM,data:jxdebMN/aPcgJdj+CFtUmV7M8UJ4DThEqB8kYdXNIlzJou6fZts9,iv:aIUYwraKsQHXL/foN4Xph45CzD/g+jr/iU5S6wOT268=,tag:P1U5PktUl69V4lANY7eLdw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:q1cePw==,iv:wc+H4kYFmeVbQFECEgrCb0CjXwz0sHCftgCEWksk+bk=,tag:vWBSSIIv7KT1VTxmhkAw3g==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:FUGpiF4L,iv:cXvU6f1xAwuzBx+eowdXlk0qMAEmhhWK8sDhoiqHWWw=,tag:yKN7pxGKnwAcq3VcVWeTyQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:YwnBM1Cb,iv:2L/T4glZvDvv5cXoi/J2yyQe2+CbCHRzE6xBaAdtLts=,tag:G34xBxExYnxC5IM6Wk8Wig==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:PpMjL7+FWNgndM4M+UeEM4ww9Afp+ZM=,iv:o2uyLj276vUcB62EgVY0o8mxzi9uPPTO6AhqMNE7I4k=,tag:1G0IKZ5mn8lplleqVc0kkg==,type:str]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:XAjkLaBjmwpvXzOJeGjA+IUq9/py1WcJinvfrq/0eecjDuhH,iv:R5MnUQ8tMxwq7LTyGQ+qZDmOByBy141TmQo9RooX4XE=,tag:2pmr/DsQbZYgEGEjW0kSlQ==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:ACAPOw==,iv:Em5V+acjAzcvElLWrl+mOOEOvxhnTFtYi4dTYp7dM1U=,tag:/oXhyheds2hxHt1zxFy9/w==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:n+WObeCB4JUdf+Tj2foBPJSCIbUfBF/l7hmEgpFxPgvlYDLq,iv:gsBfJ1D+Egb8Gz1Fw0u826fuuP1LeoMTY+G52Q1V6cE=,tag:y4CrFIEXvZGoWHxVhctdyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ0t1VEVXWGRIQzJSVkNG
            djFSeGd4aW9wcDk5dkpUUDlCZUNuWGw5WDJZCkdzQm5ZUWpzYWMyZ2IrMmtJUkRY
            cnp3Rk5ZNTRlR1M0R3UyMSs3b3BTVXcKLS0tIGtKWW1EdjVleXZXRVZYVW5RK0ZR
            bkhyaVpwUUtZckl2RXhMNmsxUW5najgK4fKWKuN6zqJWtNkCHkF1Myj/ajbLqIpK
            ccJY+Xgq/pxNFrKaSMhWARs0nYZMQOcOIuMLC/3tYXAMRGXIom9waw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T07:55:07Z"
    mac: ENC[AES256_GCM,data:Q5eVaEFQcz2hzCeAWT5qo4/xN1ZUgbkHj4bvh9UkibZtnlZ05eBfoJopi/TLTJLJsiCsPU2sjiKzqYe2hAaSp8s0hweMl0K7CQ9Su1fpbbL606fyWbGrzWKTLbd9HOhXMm9O6d6ufQTfE6pKiwOSTuGL0nPHfxtXZc4MY77l3C4=,iv:AnJn2Sho4GRutpk33tHroMg1CtRlstV3uiZjjYP0Yv0=,tag:a0mzDo4HEvwpifPXLX28ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
