apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: immich
    namespace: media
stringData:
    DB_HOSTNAME: ENC[AES256_GCM,data:KLTogF3+at3+djynDuAR9Nx9vIXVQm52zXKbKbzed+k2rVYBmHVY,iv:9jvXrCHLQl6F7ecr/YrZ184pLHNay/K/0QgYDt4G9m0=,tag:9X7LFzpTxSBoqNzsE8Hpjg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:JN8MHw==,iv:Cu7PPr72MccErWHcxkpHTp1wX5sSDYpgDand0qerpAY=,tag:orAVi2hodt15AL3ZsBsG8A==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:qIVrZec7,iv:HBefbYJGp+mssfq87YSG4xrFTRovhnUmopOUBDeAqhU=,tag:1pXjMznpVJkOzslbz6hH2w==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:fc94a7Ok,iv:DVZIE+WoDK7Ic9EwxYFvvxsqO8eWMcmrRYK1cDA8xKk=,tag:5LplFsnC9/1ejSkC+vck8w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Os2ybav0v8z1Q0ZEdazfdTVixITg47k=,iv:yolCamRu1aG4LrIeQ0rT56SItevc3ZUasdTrMoxCp+Y=,tag:EppPa47aLOAvmq0Ayrk1rQ==,type:str]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:gSwzdZ169yq27+s60AoUa1q8njrwPvKdur4L6bh/AB/CJq2b,iv:XDEKL4dWpwMue70Y1BbIBN1V9RkXPYZ1YjRexyI+eWE=,tag:UHl0vJgBpV+2dMhPQiDa6Q==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:Y89V1A==,iv:CH/iDba9Tmxu8T3T8w1+DGc9IwiusRN++Z7xqGJ147U=,tag:Z7jbdJGxSrDTtv+dtX0e/g==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:b2cgMwbF/U5AUt9UykVjq+iy6pyVF5Sr+duEFljiPqWE9dSN,iv:4cCWk2zF/AO2n8DQie8QXYkDdmpx0pg03tjvkgMZee8=,tag:iV0+nk2Fpb/9jptpRzPNFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSmJNS0ErVmFuUEMzV0gv
            REx1SmIyMnlqeEdYell3OFdoRHJhNGZaa2c4Ci9OVEJPYkNJaTZVQ1B5dlN2ajN3
            QS9vUldNU3FKTG5VV3FGNzh2TWdwclUKLS0tIG55UWNBaDF4WkN5SnNKRVA4bFdR
            a2JERkxLYmVnRmJGdlRiR25jRElYaU0KF3zb80lwSXlN4wfsxLbRf4hLZ6UPGBdi
            6sbtM+kpekYAH0nsJRc7UsEO/NXnKK923XKKbY7Cg58DpVMqc+XsZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T07:36:53Z"
    mac: ENC[AES256_GCM,data:XqE38zsT0ZOguxLENzC74kEpszX8NS/FYJ6g6x/oHQ55JZN1i6d+6n4grLGnsPgL1Wqa9d4WrtUxpYbdHJC1KM9nfUw9hpjo7nZX5tbc+UkFhzGs5gRgfw83PRhqN5gLnhoPHmbJ+v9bPtRfiFOBw6h3xLYamu27gxTST0YUx1c=,iv:EQ7aB94SrGEzm8POiWPATnuQ6bnCHwefYuetdaGGFPw=,tag:hmtJXOEh+BmQ/87xUsUrzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
