apiVersion: v1
kind: Secret
metadata:
    name: external-dns
    namespace: networking
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:09EKjFaE+cWuGgbd4omDG/ol1h7vV89/8Bbtd2hEBloCFkDPccMpUg==,iv:SOTTGbqr3v6ADpVu13GdJ+2GAwksQi90aNkrnI9MR28=,tag:EEdpwC1R+eHbfy6Ro1ofGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOHdkV1pVNXVCK241WTYw
            SFp0SUJ2bWk3cW1XbXlTZUNCdDE3ZHFFendBClVCbHhPdVdvMG05NTlnVy9GbDUy
            L1BtS1Z1TUo2Umx6Y1B5RnM1eXJESnMKLS0tIFJ0bWM0R0E1NUx3WlBkd0RtbDBo
            RUE1MjdRditndGs5V2dBZlRIeHFCZHcK4/6URkjnvfib9Bbi4/2gP42tZ1EfivUq
            lPeTBCtDHxJhKSW/EJvYgpyeto1XQOCSrcAvfDCNV1J62RbmVqDQVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T15:59:45Z"
    mac: ENC[AES256_GCM,data:z3UZsE2nlR67SVBtA2nDqSqSzDG3C6zoi+lW4lC2z8V5WpM6H0feqxTbjMATfUaPH9x0jtZQPWgeQlZxm7mwHX8gmJxdnLKvKipdPShADfN/UYXjwcAD6o6YNB3Gj6/Fk7wt2yvYRjRvGwfeRTkeQWEIYz2bzos9CaxrGAeKYiA=,iv:4nfp1X26hR1U+ExwnvNpMjvH4Bg9iaBEa5iKeEVtjJQ=,tag:Gi486FqVeM5Mu7lGZRbJ0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
