---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
commonLabels:
  app.kubernetes.io/name: &app comfyui
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - secret.sops.yaml
  - nfs-pvc.yaml
configMapGenerator:
  - name: comfyui-configmap
    files:
      - config.ini=./resources/config.ini
generatorOptions:
  disableNameSuffixHash: true
