---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-custom-user
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-custom-nodes
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-models
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-pv
spec:
  storageClassName: comfyui-nfs
  accessModes: ["ReadWriteMany"]
  capacity:
    storage: 100Gi
  nfs:
    server: "${NAS_ADDR}"
    path: "/volume2/downloads/stablediffusion/output"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-output
  namespace: home
spec:
  storageClassName: comfyui-nfs
  accessModes: ["ReadWriteMany"]
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
