---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-crashloop
  namespace: default
  labels:
    app.kubernetes.io/name: test-crashloop
    app.kubernetes.io/instance: test-crashloop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-crashloop
  template:
    metadata:
      labels:
        app: test-crashloop
    spec:
      containers:
      - name: crasher
        image: alpine:latest
        command:
        - sh
        - -c
        - echo running && sleep infinity
        env:
        - name: CRASH
          value: "0"
