apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: rathena-classic-volume
    namespace: ragnarok
    labels:
      app: rathena-classic
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 3Gi

