---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scratch-matriarch
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeName: pvc-bda72dc7-8405-4e16-99a9-a88be18d5d97
