apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: komga-secret
    namespace: media
stringData:
    application.yml: ENC[AES256_GCM,data:uEhb61imvwF/h6BD9EDs/pV3GvKrlM8XiOoSAy9c+CvlIpGOG0zZvfaQZ/q82tBrg4AFrC61uoXeKc10J4H9/xlcNpPumtRtrQOys/oJIDNMifmlwm3/nV/LxQ2k1pbft3T8S/IJzjfUweTtDfESvg7wEVkJTZfJCdXKPKiqfh6O1b5YKhiALRGqKacnNgyS+mFv7AY9fCkwasmjwcUxjtTpELk+0LNhhQTrBbv0nXgUalsDiIqd3fzpMbuXzJhpOBXDskB6OMTesVhriVfRO5v2P4uWdsH3kPJjNN38E4Z4fHgmLT6aBadAiGyr6VhW1tNJJj7Btp90MNZPxHzPUS+BIVT4k5XfYVb5ZyVL8KfqgWteDBGJMbnG+Ll+J7GDNlnxy5Q0WbuK2ejMYD4K2GdNkwL36rS6xEE6Dy2dRgolV46pS5YG+7NL886Eb4nnqvCIu9RsZ1HAjVszvQ+UYAbQOo4pFI1toS8qAqjkB3iOjd6pYMtN8RAp+VjyoeIN55FUuz/ibmSArnEclREOW9oIlUYjrhvaOTTKJomV+rybQWNpzEaUiyhAj+MEo706zJqW9tbXokbZTKf/i1/3EWRM1cUH8fuKwekXVTIZwhqTXW6b0rRlHxN+rlVlM/uLutk/Ne0R0eg6GhI6oy72VGRwqL9Ei8b8WUJ04zdy/uhkPyn/JI7TBeaPcsirAjki2/zTqCZmuKobGaXD4xLIhm0Fv6/IbKwvXMBYCbHba4ReTZ4s7VLk2mMoOv+R5Yed68Tw+LS/4ab4QYgYt8T+arzUe77EIgoaj7nYPmj/c4UiYYqKR0PlaDfG+pV9D2dHFdZvPlQo7XVoEORQnbQNJjSrr3+QCmVcyZi3KRBfGxdbPUX+fkvKKlFdrQ/ztK+kiYVGXGkvAneWNIMNH0m3uYRn+eqtxQ6MjqSmCvvj3GDo3sRcYyGhG5ugM5xqgqcKacuoovYLhL0sme6s4DRZ2rym2CU3c5fkD1to/izZ6XkuM1aRU/qyqo8fZpIbY5AJixY8viT7AaQPSxcryUbdFaURZ2+Er3i2i9awQ61XELQVrTHFdl+1zcxbD+I5J4p6xwuwTMKJ6f35dgzq57HT39rggwNjOfKcMUnEYlW6iXLlfqNWi/o6vJMpQRndVGiFSJZLWWQwbe87+BjLnQRfVcEXNye9IvZ2156Pfs0R,iv:lUwF0BeeOdQqETzUX4BqxZ8RGjHlmVDyckHgYhN0A1I=,tag:wOeYIztnZI88vutNHB07Tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbDFZa3cyYVF3MmFwa3Ix
            dVJyMnhyQ2dvOVhIbTBxTFlWeHBsVHpnejFRCkxaTlNlT3cxOXY4bXJzM2FVNEtS
            TFhzSjBSQWVyR0hrelNMUWdodjNrWlkKLS0tIFhhYXdjeFdSeSswRUtyUGdWOW1W
            N1ZiMkt4bU1XczVlSHlSMmd0VjRtV0UKAEqDb8Aiu7VKYpxP5wh8Wvfv1oPRkfhF
            t7qo4Tpee3WxeRAED3Yx63tE2oLgNYeKSIRtIYzeTLBI4q/Gkdm0Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T05:55:13Z"
    mac: ENC[AES256_GCM,data:oxnpyWcupGDo9jVh2SdqCbkqmGhvrvwdakOiVCEsEsFGLASmE7L2OxBKNxaOr/xnIQ+5vuf29iiXZXz1m50G0Ry2yEG6cx/NHLHt6y0KVV/hkl6gpmehLyuwU3u+ddKWGlgP1y5BbjPka9Lowm+G4V2jkkL0ZT9xiDB64v/gdtQ=,iv:tmLWGpBHi1K3LrWGd2KMx284bivC2uJgAAXAnjtvPj4=,tag:m9dVPl7tddINJJBQ0VSzzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
