apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: komga-secret
    namespace: media
stringData:
    application.yml: ENC[AES256_GCM,data:lCnP1PeEgQMKxlVvi0bmEYflK69mC793Ufg9ycoxdXOguBuSbhV4ujB3CqvqBSFzMZsNG+EDbWYD27Z92HmLyFngUJija8uYKdg/woynXaPiIFIWFh2P3um13cghmPQ5DvVTf0Ssob734c684lkmtPKUp/V9V4SxnwvEXM7s1X+gPrP6eJsPvJzKuoNac4ajMV1jfwAW+A+jg/Zy32TVUZUSVwMJRV5Cm3xj/UDvdOXPOprBNHXlqPeEkCJvKCPCWixOBcnid11irtBuy9f5hk09UXOpK5Bz3x/hbAqFIyECjyMz+8y9qz3S5yvAZ2EvhGXqkAU+pEGJIQEJ9VaP/s+cMOdvZny5ZHRCqPvp8NHJV11ICADpq3Nk7zHVn0zF0u7EE6AbRKO4CZ965HHjeJSy4RyaGJWBVyPLUacgZv5fTXsvsQGTOKzBEj7e0c7Pj04ou+ZTIpOcabdYESOWAb/uoy/pt2TPiIbb8jHXWdj7857lfvZHNB4h2dadMr9udInFTaJJbRS6s4K9BC1djyJ6OlIh18OJ7DS4oKWwe0EOrw3ggrO+936XpcSq+CqftdXnP+kKB135lIZmsnw+zfAyR/rqAydcTZNCYVNVCNJTwVVw0v8AmPqMdCo8b34E8vlMffdF7HMjmZYGAHf81xd1Na83LcvBpPUZI2K9UqFBKOYuqK3fHSSPkqeNV059mvs8oZc2zQlqvdWTndayG6IF8NBLbFVsy1ZN0hVp95XPaoJsVKYwGdjp/+OVe0mKDX5sMCK1quvKT2nRrFTcPebHB3WqDvBFm/o07sLsZb4pHoHTE7AO8ZH45EaQNYIdebjeXk8uLfnTpmV+N5dyuty7/zbk2BlmG27gNpb8Hq+U1hMQq75oO9NN9NNguYqRx4JT0DumplmcZE0iRQDtxlkvjvHLRl9TP3eDTjUihQM7obH19fdCtjnmssnSY+jVYYIUGeB8hfdmOkVPB1EzyywYk6AC4RYaK0swi0ma9XdR9Qy0GwQs/0cfondO4nPaZa01b+jvDL+Bdr6Q8Zmxb1jXA6xA7smKRQQ6KK6whNMWc8et+fmENSYC9+/OupXwoc8vH4DDofjA+7BvgUpCgFTzOvaQULmF/O4eqk+/OvywlYLB2XdWJdGpGMhLMNK3BVGo3ZlHWIU3Mm8oK4srnLF5VNg7KUf8cxlPUI4DN/F2HbQ0rk2gYA==,iv:Y4QV0TFT6uvk34J9pqFzrIc4l8P3FpYXbN2y9XIFD9w=,tag:LLJXlm5PGocqzYL68ROlZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YXRLV1lrNjhGa1k5Wjg2
            dkdncWNZSkF4M1ZpQVJLcVVSU013cXhXQUZNClNPWGdvS29oYTFRRVhWdjVKeEov
            S3cxRml4emZHcElyWFhocXB5UnZzWjQKLS0tIGYyWjFFaXIwR1VRUi9rV2J3VFJP
            NHFKTkxmVEVnZVZiOFR0U3dEVElXaGMKvjKEtQJZ8ApyP8cdJ1dj5exFXOYUbQvh
            CIoflsFGANKhqJqF5AQa9WkmvtDtGkRAGahq1bZEkOpO3AOHbP5Qvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T05:55:59Z"
    mac: ENC[AES256_GCM,data:o5wLZasuu/Ywzrv3CGK63O2fia8Sb5I/jI+MtuAIA09YC2orwHWPaal3Gel1hcPQhcVXZ4DA9JpwUVP7gry8IQKSMGuIBjJ6qKT9Gw+pKoOwmL7EnbNmrIjoiU49VjAl3WjdKar/hAkNEAS/FuuorX3fYH9DaESkuq2kFMv5Z0U=,iv:2rZRrncfSQU4q7XmEVIeHQLW/BLiuUw6zAKCFoytxPk=,tag:STMj3aR8ojtic087YyMhsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
