# SECRET SKELETON
# FIREFLY_III_ACCESS_TOKEN is generated in-cluster (see deploy commands).
# SIMPLEFIN_TOKEN is your SimpleFIN Bridge URL/token from https://bridge.simplefin.org/
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: firefly-importer
    namespace: utilities
stringData:
    FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:lBreXzcdWguqu7QtmSm6juNmAqfWvnEMMrRP4ZsbW82T7guGzEf+AoZlzaWY/gAnGa1DB5KkzL9gu+EkQgkr6ejPn5rphLYzDCM9d4sB72DheBSBphGh0PvU9U2Q39qCJ+N3/+3lo7fHhU+gVQi5KB6a4ovmuz27uUZe5bHciWktrsHUTN+SxzMcxNmkm0yZ8Q7cw7RNv+s6UcOyZAWYwWb8NXj+LDBFkcWVD0NzyzKCHDbXWnFBmv+RU94RpDdRaaj+brZH3WSDvcFThDanFJ6wwcV/RhlW0QYnmteL8Uf6fUBZ2v1Fk4A+uJuXj17wNR033rrL16IhRYFYP8ZvFy1rixQ8MdzHVU4a25PZXT//1zPDkg9eKqWJlxctU7e9y6KUTDwoat3EPW7YE56tMl7B9m4OioF+inYam/o0l2cLxfpBY1QJtGRJ2hEW+lpuDRKmBRlYyzJVjl8zAjmyow1i/EzyZvj0d40I8Lyyw2zeTlNfijJn89+KzVSo4YOoY2CD/qwHtpjyaD/AYMQoU9tdSkOjm9BIKg0lr0LQrCYdaQMqWpBXK+LMcLkgcWJ4zsyE3xOIQD5nOJ87ql0ykNwL5KR4XiJ+KloenMg8ICwvVtW6jVPZfNDUS016mkrudvCgkzQt24LlBKUwSi1bIBO3VtsS63YgVghhdwV0QHWpAyz08QCX4ZQ1/yk7ohrjrcmRt8A2KQGe0X1FCX/awfYrtpIME1zKZr3w07OZRiEujCzSgD5gvCSxzXAKKcfDE619NY/wmIBPvkx0eygcpa0k/qXt2129vskmW9IeNRcB5BErHmjJTh574Ya7Kb7pt5+8WjujHdznvTsOTgx0kcXcJZY5R2zgl1f7Am02rHnSrk/7S9f/9qe8MPVFQirRaiwphjDPS/wZvJx4isvpsQI5QlkKUNTCqGmb8fjFf41gUQHi/O60IJhYB6yyz8jMWUFBMOe3VOFJKKfEELwWVMyxfzIIK3xFyIqfPU74MOcBvzD3oKCAbBKkhDyCWnPUD/2oJpyHAI5wG9V7Ug2w1YLEtuCUwKGdBzowJbXCf4OT/MI1bEeLDxr/UtJ995j4U9Diy11muLA8zHDd7dmqYCWZisX8OXUu8psygoQK/LO2d1C+5elSAmSCqLLQFeMk9SVrq0yfpAIzGIX3qFiXFY0h7Bi7xOzLY/uouE/qghXNiRksnrl+hoNbA9m2F7uChN1ACEzhcmQS/+xcaU+o5XH1IaMSp5XGGDHdUc2apEELynfuSDgk/y0G1AHO0ZmytA1TWAd32hcZbgrhjaGK4cvlSE596pfl8KAXuOaHL1LJjWpbU9upYWLilC0A2U8SxuToVqqWV5PdzNF8Ua5pHFC4OA==,iv:/BuA+1DkczIyWUSGhsx8fHw3Uxn3OsDQNX77otavfcY=,tag:zpmKqY//qFO5CzngYVxOmQ==,type:str]
    SIMPLEFIN_TOKEN: ENC[AES256_GCM,data:0D/h0SRFdxaKJnc=,iv:C7KQfpGeKQAwfjmS4lWAaNYqwJ8IoIfB4St6Qc4MiLw=,tag:pLixqJIjsbqOndecsKvk4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZ0tEbnljaTJpc1FTdzh5
            ZXZOMzc1c0NCck4xd0RKek1KZmhvUklQN1FVCmdiVnliSThVYWkxN3cvc2pLdUEr
            VjlCbkRmWlVsVjFIZE94bWRhQ3Z6Q00KLS0tIFZSZmdDVVZ0MjRBR2wwek1zb1pJ
            TENEM1hvbDExR3NZcnB1em9oUmNKbHcKEOqUmRJ35cAwa0RfZXfVVIGuv/DgENlC
            ZTQzyDTbRJzYLSMD/fF3VVJYP7Y1zJi87uK4kgTn92F+xJJo2HPuTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T07:22:16Z"
    mac: ENC[AES256_GCM,data:ItYmhpa6hvKhUh+zkbhbu4cbTVxvCKOMjKJgeVgDVepsW490PBA2fUOrUL25lLCTZZUqLNi2+GJvOBZ7Qw3iO5MDQ8FzU4DguDaRkAN6D2nC/5vyTKFHjzOdSzlLkzwbfnC5e5ivzXvY0BKe4ol36E3J2AkUmAfqP632+aF/BNA=,iv:Qd/uOXY2dLqQVxzVkfTMPx7ZgfGKe4PdfLGBK6rVz8c=,tag:nUrfoiyDSZZ7XgSUMPnGIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
