---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ./traefik-shadow/ks.yaml
    #- ./authelia-shadow/ks.yaml
  - ./echo-server-shadow/ks.yaml
  - ./tinyrsvp/ks.yaml
# Note: mechanic is not managed by Flux - see ./mechanic/README.md for manual fix
