apiVersion: v1
kind: Secret
metadata:
    name: openkore-botijo
    namespace: openkore
stringData:
    OK_IP: ENC[AES256_GCM,data:+YZngYkKh2uRIC2kqw==,iv:dc5LTfzhVf69g4qqFUqpKrUAjWX4mvLSUxaCOrhCWuI=,tag:Y/YE6EOwpNie1MpQGxOPsg==,type:str]
    OK_PWD: ENC[AES256_GCM,data:L/4otglYIsQ=,iv:tB4Ftr8CfdDgSgEOYs8ThNjNage6/2ShixiQJq0twCY=,tag:DqBEIRqa1UFfR+2jfON/UA==,type:str]
    MYSQL_HOST: ENC[AES256_GCM,data:jdcslNu0AO2CDHYi,iv:y9SkWDSMBGekIFSqB4SHzVbY82vRpJxeWbjocwNRutQ=,tag:+oiDAyJHiIbchVrJ0vzjZA==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:zS3IDrtTFfk=,iv:CkG3RqmFyjIO1ibAmW8HaK8FtyOOs498iXZvAxHbamE=,tag:j4+JLaJZMnbtpjOoKc07/Q==,type:str]
    MYSQL_PWD: ENC[AES256_GCM,data:ksrDbLuDff0=,iv:WgamPj9wGJwxLVDuh2OuLiNyfnWOMnXGxuTvyKXfhTo=,tag:+vVDRzxFTX39AcTOqanl3Q==,type:str]
    MYSQL_DB: ENC[AES256_GCM,data:3dn/Lcn47bduo6+MS6b4,iv:RKyqLyYj1waydpK09II2EdRABzZ8TwOxpO7qzhSio0s=,tag:plFFrcpcExvHK65h3+/n1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ2hrSWcveEs3Y2YzOXRx
            T2M1M2laTjFpdUVxRER0Q1FFQzJLOE9kQUVJCk1LRmpNS3F1eDFlTGZyeGEzSHRr
            YWJ0b2IrVkJ4QTBUU0h3cUJpdmxaSm8KLS0tIGlEeWt3T1VlTyt0UjZzUWtDbnRU
            WHY3VjlycTl4Zm53cmtNRGxlTUlmS2sKO9MTHTKLueFATNF9iDj0FTRC72qyVEhe
            R/USGYhUn6w1gn9JIxTZRt2fXdEaolfk/AmA5c39MZsDsG5hX2E9DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-08T08:07:28Z"
    mac: ENC[AES256_GCM,data:aTl7jqKcCrO03pmDpLLw3ut4aSoAmLGTxek2EYI8Oodb48Q07+EUqfzqmUXpYdXAsSN8PoUNC8aSxOZoOrGSrWerQrHvha4j7JBnoa4ZGyoIk6W/OFmqTkLmBg3Y0Sdpq/GAE0qOyYPhGiIDX5NLUnYyaA2Y0oDejCjnARJVnto=,iv:3wr+sKMhWgff1x3xJJmsC7RaLjSZprR51cP6LSVdHLQ=,tag:lLZUdx8p88ALaj8VCqtEEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
