apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: lenaxia-general-runner
    namespace: actions-runner-system
stringData:
    # TODO: org-level GitHub App credentials, then:
    #   sops --age age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k --encrypt --in-place secret.sops.yaml
    github_app_id: EDIT-ME
    github_app_installation_id: EDIT-ME
    github_app_private_key: EDIT-ME
