apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: lenaxia-general-runner
    namespace: actions-runner-system
stringData:
    #ENC[AES256_GCM,data:V1GLdwkE4af/K+O5CUKPtSAIFW4/kXzw09dlC7566PTbAW/EHfx5ZfsvhIbHsg==,iv:z6nXaywvigbP6MVOzYDUtPPx/MKudSfyFcGjcIPyvhY=,tag:Lbsg1Ca+fQ2kWHf3LOXweA==,type:comment]
    #ENC[AES256_GCM,data:ct7eMSgiK8mfp1Bu2A0AyeM8ZeuI3LeUofpipmQsQZasIvp536d1+VoJAqhj5pXYdmk9ZFNk6L/cevqR2rX6D7VqWl11aTc2ycP62NETELmId1ZLdG6VVuT2abJsIV4EjdpPWN03KwWSVC1ecpOOZGOB,iv:DSjgthCvShcU7PnBxIxUDYk58bHmSUJ0dkYr7dltTlo=,tag:EkC6LvmTf+Nx3qj9XtCM3Q==,type:comment]
    github_app_id: ENC[AES256_GCM,data:LOtBp0aKMA==,iv:iYWwMlNXpaLYZLvXDQzuYEVEHZpK0EN+akd4hLnuwHc=,tag:XXM54T6acvLe3PMOF47RPw==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:AdsqFyuC/Q==,iv:gLMZF8wX2Hzdp8ZdLo98lkhToBP1XFzb5TKmyKdCcoI=,tag:GuOXrwT2/yeOuvFrbSoUzw==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:vupO2zpPNg==,iv:UetpjSX0Cv0XLtMAJ1gDBKrn+F9Nx3LHoUR2lXOZFaQ=,tag:RJg1z31Fr9LOXh26hktLhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WWNuMTRleGpxRzVtUE1J
            OEdlWU9URGx3Y292ZXd3SEdLZmJsOHFGa2tJCktTN2sxMS8xT2ZCSi92aWVJOWNC
            aUNIZERUTElGUnQyRkVnOW5IZWVsQzgKLS0tIEpneEUxTUFNVCt3TDlucDBGYzcr
            NFovaERFcmJuTmVtT3U1Mldwb3dMQ28KtuF0eMuWY/tqwJNKgtmr3EhgBB+csyug
            vJ3h9LTKjra4wy9jCh07UTTnWZab0Q5aMdlgAqb3nWeUgaPfYqO31Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-01T22:29:03Z"
    mac: ENC[AES256_GCM,data:I99mFpwWxl2BN+ZyOA015xDlJzZRPmhCaT7zaaCusKEI1neW95hh9lRRdujJr48cV8iucrU65UWGhe/yToZc3oegu3tF9Vq3eXoAFV/1Q0dTlmXJIhktuOGjbSarVGsL/W/LGsW473vlu4tnc9A/N10sbUzod6Gov3Okq9FEKRw=,iv:JknTfqloNM+YZZ+W/oq1N1deCdGp0X1df3Pf7kC2klA=,tag:uJdXKq34SGB5MubuqUpEtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
