apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: watersmart-scraper
    namespace: home
stringData:
    WATERSMART_USERNAME: ENC[AES256_GCM,data:gyMNGPwoMwLSYGWM0cDvo0j2,iv:97dH5ocIEbnA6hlIixUXXI3A2i3Te5OGF8zeDmr6C1g=,tag:fnx8HOLJ10mqo6vVXhcKAg==,type:str]
    WATERSMART_PASSWORD: ENC[AES256_GCM,data:dGMzk5ReC8w3Zw==,iv:N4UYYW+2GBqbvIEb/KoMz4uXMwoC6irmZQtHPgQSYj0=,tag:dcrJ0Tq5kl3qPsGVPOWZEQ==,type:str]
    PHPSESSID: ""
    SESSION_COOKIE: ""
    MQTT_USERNAME: ""
    MQTT_PASSWORD: ""
    HA_TOKEN: ENC[AES256_GCM,data:3D+Ig+NQI9rpZmkeZuoo0Ep9VciNrnmCliyzNSOz3dVaMckBvAu1O97khCxnX0n23qpw+fe0MW90Ui0htkpOp7rKEarlDY3il7FojSceMcoZVoEjhqZrUHARkCNng8nX2xG849O1ZvVajVL5asc181ff9ikJY+DMaUB15PDR48++MnFZOqBXatnuuEw7SeyDwR6TYSf50t09zjdLuy6aRrZnz7I52Us/51k0Yr2+pldx+3AzQLUK,iv:4tNjjYzubocyJF8rdvsGX6oKIOmZIctMofdMqeZ8AwQ=,tag:hLSsdXY9ligA9qjkBg26VA==,type:str]
    HA_URL: ENC[AES256_GCM,data:BcJ0a0WNgg9Ft2VjZ4o6OQV4GTN8NQ/yAA==,iv:BFSJkYz9rkSWPazwt5RaFTJae9LMBJLGAA8i7CI1A14=,tag:DZwedTCBolzzQXLQmVhrPA==,type:str]
    HA_STATISTICS_ENTITY_ID: ENC[AES256_GCM,data:gPNAlIOQYjowFWU5UxT9+xjdOvFUXBop5RjxiAq7ooCY2tw=,iv:r6kM5OdC0vs1G51jikiarnV/v9e8QlMfWQS+tRCcfsg=,tag:CqfZv1RJ03kgasVcibXRsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTFhha3hYdFd3QWhxbXpu
            bVNiaGkrcWw1L3RkNW9OZkhPaDNtazZjb2xBCmY3c0hFSWgwQTYrQ3ZWVVI3Mk5x
            UUlPWEluYmYzcjB2V2Rza25MK1pOa1UKLS0tIFVUd2pSemZrZGxRNENGbW8xVzlH
            RW04YW9iUllSYWh5MXZTUFlSREVUT28KNiX3xqaFRgchXruC2luuQkCzLQimpjwe
            r1e8Dy1FlTXLy5IA/rE8xq7Y2vZ2GGL5tSsQwmFh3Nz59FkJRYyFeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T17:03:23Z"
    mac: ENC[AES256_GCM,data:OhEcaDKDuxKNTZ3K2IXn9klAZWWFloSm6ZWiPZy7K0QyGU8/krmfNkPYvLMdKZb7PnxngIf79oFmpPW3GHuehYsIq6dHD1lhMtopc2g3aOfnMpyrkR+QucKf2MiRuh1tw2fbuHDKf15L4oiOjgU++Y7YVLRYAp3BzlVIONnKIlQ=,iv:gKXW2/GwInk1xFx5rauhkKFTIrsXLSgJG8EnDFlGPbY=,tag:WGhwKxpQ9o909m5jJOG8VQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
