apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: watersmart-scraper
    namespace: home
stringData:
    WATERSMART_USERNAME: ENC[AES256_GCM,data:RzDn4cab6xLFgGqY+0wgr1gM,iv:JqMeneZexXQidyAA6d7fx6nrK6nOiaIQGi8z1YyoylA=,tag:/b7MKyb81203aFEHHbZ8Aw==,type:str]
    WATERSMART_PASSWORD: ENC[AES256_GCM,data:2urJWxhJpU9AAg==,iv:BtOJp0MSE9i9IXGFiL+PUNeXCCnCKho0LPnYI/Zyqco=,tag:7CEML0cdWAsWw9Fs+zgVAQ==,type:str]
    PHPSESSID: ""
    SESSION_COOKIE: ""
    MQTT_USERNAME: ""
    MQTT_PASSWORD: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUk9vaXpGbFN3YkRSN1U0
            UVI5RVlIY1JmNzRMeTRtN29xVXV6dHcvaDBjCnJGWEtkZjNCOTlMa290c0o2ZVIx
            RVI4a0FraFV0VjhFaGxjcVlwT1pwSzgKLS0tIHUwcG9NanNlNVhDUHllQ0puczcx
            cUUwTmhWcXBHT09WdS9XZk5iY3Z4L0kKHK3ivobwooVBYFIdwJ1QXW7JGvHu9T40
            aSXsoHlLZWwrXh1iT20jwxJw8nsOXaN7TgQgb4kuUXD8dYoxrZ33zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T06:20:33Z"
    mac: ENC[AES256_GCM,data:8si8lBOtnm4tjfm6xBRWuRvOzEhjWEymT4+7g0VgEvExUr+MN/9Uzsk/kh6r8uul/PkebIgb6nRRaspE807g/SETkfOPDiGPojCHq1YbYnib2eYMHqYvscK9UR/KJ8pQiOFZT8+mMPTn5DeZdH5VoxGxg8E3U8Wn4ICsYwGkVfk=,iv:jwGXU9ik1BrDkjU6BqrrMf0jCZuRj2rANYhitDOED6A=,tag:XenwTzmgCfbxIimThmWi3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
