apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: watersmart-scraper
    namespace: home
stringData:
    WATERSMART_USERNAME: ENC[AES256_GCM,data:AsZaTZQFVY3VLKWwuHn5NQro,iv:eGcqXB0l8nEhOsy1mK7SmwhhagXbt8Z8TBwYRzv9kxA=,tag:H+r9m4NjFQI7il+W20uUVQ==,type:str]
    WATERSMART_PASSWORD: ENC[AES256_GCM,data:Yhek6Wpwj9HmSA==,iv:O+gyL5GZj/br11mhSHSMiQ+FUUiGktmpNsd2R9Ld1zo=,tag:AYDNaXNzM5JLB2i6LqTRJQ==,type:str]
    PHPSESSID: ""
    SESSION_COOKIE: ""
    MQTT_USERNAME: ""
    MQTT_PASSWORD: ""
    HA_TOKEN: null
    HA_URL: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMEREQ045dkFxV1k1ZFBi
            R3IzWm9LNHlvbndLSTNBRUxFU0FBVkNmM2h3CnF4NVZkSHpoeEZ0UlVqa2t5WnNx
            TWNYZFBWRkliL3FIQVpNTTZKV2ludEkKLS0tIFRpWUlrc0lwSjU3NDVwREpGL3Zs
            MVlFT3U5MWsrUzhSS3VhVFFVa1I5aTQKjdtvowst6dRhkMKE4yhRZE9m5/Z0NG+1
            j0Pzbg/kfdpArQ2e4NDBuJElGkYe4xuS9p7EzJ/T7a14BnbVuXzN0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T18:09:57Z"
    mac: ENC[AES256_GCM,data:jH6PTrohMqcvq7f9yCciLh+0OuvPg5Yt2Ore5jupI/sxRpd64WFQYoGlBawNLur5Cqn9knwB+hvr5/vZm5ltGidkHYeuY+Ej07l8rk6f+W11RfyU3J7vliNWYrvElQtRvyv9mm1cyJTIQBYR+N/TaF5dubCV+mNal3AxTuk86ng=,iv:gJTcFy5vhCViBs/pw5yKhhNeb7tnsItCvcyalHwwKYQ=,tag:SIJtWSMfytvUPeAGupZeqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
