apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: mosquitto
    namespace: home
stringData:
    mqttpassword: ENC[AES256_GCM,data:tGv+bLkM5hFr+VopeA93Dlef7e1H4KPoxLQdOPxoWX/G0DjYG7qRqI3+uUJKs3tnSpaykqTZj9WfQwIaEKnrJhJ+7fseJYAE4oNsdPrl3Weh2FP4cC2mXVvDInl65hWpWTkyyekNwd8zFSvn8KHPh7DQqCnBXeT1ktJmGpGMXfrgzK2coa7hPVM6Hxs8AtuNCpTvn/jhAJv2tcJ6U4uE5ym9RiKgGDNbpH+qxqiy79QUZRZO0a/8HjVOguLnPQNcaqhtxxhdbP4R264UXrfi3eQ6ZuVxKLGAaNcVdQRMpKzkuqg1Y3SZ5C53V1jN6Df50Vqd53PNYSfc+nUNLt5y6k45cz21jw0gC5QGCkheCNA=,iv:fXik+dZ5MebixRZWoYdSvy2GQdQQpQ6Oy06n9kdTYYg=,tag:CbzXWKCLsDmfIEkggzvrSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZFo2VVNlREFHb2lLc0Vw
            MXNSaWdkNjErcDBmbjduM0pBbzNUUUNLVXdzClhLU3BIZHFRUEkvbmdUN3V1OURk
            VDVSY05RMkJLTklmeEdIWjNlUGU2OWcKLS0tIGZWSVdPcnRzRG5BM0Z2WHc4RWNr
            cmhIYjRpVld3MTZLVmdKeW5VZW1wRGcKrBo2mwcJK+aGED8l1TVFN6JSmXybpQ8+
            Ncw8nDqj9OiG2rt8X/sWfFIYOnruJcp66M75mRqNVS00xAzCEjgDHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-28T03:08:51Z"
    mac: ENC[AES256_GCM,data:G7da1isov/mz2pYai8DTG+31PTY3Vni6pl/BF1ZoHnpNAlbfgYZTbJhi2pY7DX0zQhIubhV0lX2SYi6KYEDWhO9pXus18ShUQh3muuaLzMv5yznFSkqb/sP3ekM4Za0lJ90XN9mbUmm9hDgWv+NSATqk8bNkA7JNejlqb7L/emQ=,iv:gSE+DM5L9sK5TgXomVIlxXyVsylYLSqzUcjJ+Hae6Rc=,tag:wRVHMxtkHv1LtiFR+m3hOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
