---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - job.yaml
configMapGenerator:
  - name: migration-scripts
    files:
      - build_bridge.py
generatorOptions:
  disableNameSuffixHash: true
