apiVersion: v1
kind: Secret
metadata:
    name: hortusfox
    namespace: home
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7QX//WGS5w/6CtiRJ2Qc/SOaTc9UoUQHRNl7gjwDSVBHqIQVR28Ls5H7ahGnkSNKYI3kzP/STAgW8jjbF3wb,iv:LGnwgdtP/A4KTNTsJDdj24L91eJekvgw+JzaiqLasMw=,tag:pvjod5lTQldgb9JpsXHUpg==,type:comment]
    #ENC[AES256_GCM,data:xo5bKPEYtZmMcQKc28clV01QRwwBdsCqRbyANgCW2wZmMVU0v14urDH3pec3h/AwfOPzhkrIZstg5Ocn0A+KvIlbb2ZREg==,iv:VUMSNb5QZkHYB1g5lbDR9ZjjA2noCa9Mp9Xz3hmC3wc=,tag:c5HNvA9JfVrM2glSewCsGw==,type:comment]
    DB_PASSWORD: ENC[AES256_GCM,data:4iHnTSS+G0svMQS1U41UwSTMgFQ6CHDTcg4=,iv:pNdWhLl4E5UB9HhaCWBOpXtZyejmAOMBqERInm8YZmk=,tag:eKNv++CaD/SHdeV4R074gQ==,type:str]
    #ENC[AES256_GCM,data:EFedtCnubYklsulufR/qL24M6h2BFa0YApqtDqt9cfZ2PQo9yWXjnRgs6ylSkiY=,iv:RaY0GV70Gs2E+v1yfE0qC3G4eqrKdrFSzsnpATLIAB4=,tag:lBXAOg56qyIfXyg/hyiCIQ==,type:comment]
    APP_ADMIN_EMAIL: ENC[AES256_GCM,data:gT/QC97phwQpgQZzCpuqFVVKiM/iYQ==,iv:7NHo3AEmPiHMEvpFbHwNJnnyR7WB9JNt6EsBQV3rsDU=,tag:wE1hpIqxAqR5DZs0Pj/UNg==,type:str]
    APP_ADMIN_PASSWORD: ENC[AES256_GCM,data:TXt1GkEv1QuYig==,iv:Afl7IyF1NPtGKY45+j2P2c1OMCFznGum2r7oOClofoE=,tag:+chDgJMIgYURuHxfFobaRQ==,type:str]
    #ENC[AES256_GCM,data:cRL3d+Br3zXswprlzhdAcMagk9+3auTb8+diuQUcTSylT7G7RdVA08ymPT1k9AW1Dl5AbrbR7ajZtysBmh5y04E=,iv:wf9zZbe2nYKsy6idoX06cRAVCJSLo91fOf93CFT5kVE=,tag:y1VLiN/yCDrSSYDCXYH4NQ==,type:comment]
    CRONPW: ENC[AES256_GCM,data:F3f4td5mI3soZ74hbcqTRNao5RjNV2YCzj7v6r+fUcJz8bQx87EDDQEUZVweTphYFWRV7NzLtv2gyPhJ2OOj2g==,iv:B0Tx0a5JnaJTspmsFtwd5DPehOxmkNhzHlmgtugd8q4=,tag:HSv+kse1efL+75xMq7KWnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZEZEdkdRdVhBcVN1bVpO
            YXBVUko5elJsdzU3WDRKYnFFdm1ObnVYNEZzCmNZNC9FY0dLdGk0MlRIYWxjRDE3
            UlFDeU9oTXVYckJFejdJeU52b21FUkEKLS0tIE9OanhIZjhGb3hwcDBONmV3RTAy
            c1N2RXQ4L25WM3VYNEh5eU1EZE9uVHcKVFfff38l11cbs7lHKRbtLCuhS57ncTIt
            9ImUpthnSAGa8wENZnX1xSBxmEV3uzA3BgR8jsKp1tfu/lTWtpfUFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T23:19:46Z"
    mac: ENC[AES256_GCM,data:xKqBko0628EqeQHrCxRBNYUoElpYMTn8BE7XFVJjgTsIQG9QNZL8ZLj2UAOxnYW0gt8arH+N4ecS9/eIua7p+BC1USrYKgSPDdFZ1E54ALDLmAORKcxkRnONcQ3ACnu6cCv9BN9eJMzBxnrMkI8qiOPc0WuR2I8wseni7DsxVYA=,iv:YlDSzF23MxfenwDBKDf+QfgNCPFqJ5pOQVjNZwjPgOM=,tag:S5omPFFlJEnNTYLKA7Qipg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
