# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5WC+bSXZsp+6xr7D98o7Eo4=,iv:BfL/8qlDQCp2uLC2x6XbogJwRVkAdI7yvvVHBhh5Qto=,tag:tE5gpiQG69RSZz8UJCpttA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8b/UsN7imx4nYSa7JUkKxndCUik=,iv:ZrDqXxYuRRZuyW1Tlf+0L9rTzwJhPUR6WEWsbTEIN9Q=,tag:9ndGTum3CSweqEpTdoQAyQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:jTOKhBLCT+GYcDqMDhRK32345iXTr3QyLEu2qviy11/MREDfgkdpxRK+ovhy5kYX9uqyZFaes3rM/HofeJNYxQ==,iv:pJADPgolAdh0LBVIGYSBP6gmRsUay2M58d34evoKJok=,tag:OeJkS7G6QL5IfLbrPBGkBQ==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:Rf7FVozZfPqRAwBt9gz1AdiPFKrBcX6EAyHl8Wdl8BViqQPq6K9MhNP+Ec1JdjuLTNDLvdFzl3vFOrMMqqLUWw==,iv:PxLD7onkoLu+8bCNHfmnVcnOQYmV36BQWhh504JLejI=,tag:6habz4XwJcsABkm+dCab9Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:FoeLA1YIHMZmcbgr2tvR/ouRx7kLQFBR0fvDDOUDgzqfp57YQcuMyc2fgWMZd1zVARm1v6bYhX3yOTC7xAurbpdYwvaQ70lWfEOAXtSt0xYvLXqqklU=,iv:new3wOFOxJbaBHRsNPszfItttPo8fMXWcpplxvNqbeQ=,tag:u6V9jUqoT2DIvagJ8d8vYw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:vAgzl60FAQ==,iv:AvMjZD94cgmtt+u5l/T4uJaqXwLYMyIp9K0bslh6VsQ=,tag:ava7kEb4yJPUDGHmU/HT5A==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:1FbRVhf9eWyI1jmJ7Q==,iv:vz3G7qLs81RjlxgYx35hf0a+2AlJANoKSKXFyL9ENAg=,tag:5VCBhuV83IPiBK9+ZoPhrw==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:Yrylt+U=,iv:ndeYhR3tnXPvx6C/qXO+TaKUWK0bWKgJLMl2mOl16Dw=,tag:AH4H06SyWXh1W6kEbMcRRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYjdNTkNxS0Y4cW9wRWEw
            anRhRW9TNzNOSVp2bUpoT0pJaU13RTdvNlJvCkhpNTBhN1VJWUdpcE5rSElmSEVl
            OTZkbEJvVGlwWTNaMmFhbDFNbU9qN1EKLS0tIHp2aHJRYmNYTFdpV1V4OXVsN2M5
            c0QvTEhFd0F6QkQzRlVSMjUvakNpbEEKvebAY+1abhClaB7iUniU/94X8LWXVsqu
            AozHUmNta/PD2SWHb+vceCy/I9lWltpP1+ISNkxzE2fuPaZwLz6zZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T16:47:18Z"
    mac: ENC[AES256_GCM,data:f8jB2S3hHZ3jGjQgls/LVORZNsHJp9siJEvsupOG1f+0UfzTZprt/93dmb4jIzdnSYCvpxIwFWMNGs4IJJ2t5JUYmYk8WUtqQY1Z4iLI/zGPzAx5mxclV9k/Pzi/gMPZRwD8wZU23tcICkO6zITShfYGJzVSWcJcv8uLCI+TLko=,iv:PzB6cnzbcRYK/clH6D2HcsctNJjFGaP0qgPnAx9VOps=,tag:vsfy2SkcVjilOU2iuYd67A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
