---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-crashloop
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/default/test-crashloop
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
