apiVersion: v1
kind: Secret
metadata:
    name: kicad-mcp
    namespace: home
type: Opaque
stringData:
    MCP_API_TOKEN: ENC[AES256_GCM,data:X1Je2DH/cIVg5vGHl/rh1GgeVALQz+nCE+1Cyl1q3UH/A7IZdVRvqBQaCrv2ZWoRD2Irob80LG2Q6zafND2Ocg==,iv:Y2PZ3fdgc3hhRFj9PX55qiOObuVFY87G8Uso8J9l11U=,tag:tVE2cpz/P0Vk7os1tevEJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SytwQmcrSm10YU1uWk9T
            WU9SZHNqV096WVl2YUEwU3Z4RGplMEhkNmh3Ckhyb1JBcEY3MUVBTjNwRm1SR0Nj
            OXFrUmZvRDdIV3JUb2kwUEZxeXBVT2cKLS0tIGhLa3dCM2pZa1RVY2RPbHltVnJ6
            eS9IcGdVOFhRNy9OU3o1aHpJRVNUemsKoNPLZ0stRfiUczwB+gDevidSf9NCyWaJ
            kNiNYt60UU4or9UC7IU1+e8hwXEWNI8pEYtJSTtL2wI4nUMgSN+vVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T17:32:15Z"
    mac: ENC[AES256_GCM,data:IILSw9kiA9sjf9vSt2Auom8XISql1q9QeULFU/Ii35R2fBlA8nFfeIy23263BjYpiJgXBMqmDUJy4fX7iPLToOweuKUPa5IZJyPS0N4c3YXQTqyKnoMjXp+LdkBpusCvnVJIHwDdNqk/H7rSr7SxhENfbh8fELsME7COYOrjCYg=,iv:dgO4r+VSqcAcHwwW+Is/J5vt3fh9edcNxRgrIHgUWMg=,tag:dAIfmk2OCsNvQE2Q2+ZHxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
