apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    model: default
    backend: openai
    baseUrl: https://ai.thekao.cloud/v1
    secret:
      name: k8sgpt
      key: litellm-api-key
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.3.48
  #integrations:
  # prometheus:
  #  enabled: true
  #  namespace: monitoring
  sink:
    type: slack
    webhook: ${SECRET_SLACK_HOMEOPS_WEBHOOK}
  #extraOptions:
  #   backstage:
  #     enabled: true
