apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:/MMU5grP/PLNnJWQGZPRioC29IIzxhje7UIEvr6dcZPmsk5BmZYESveRuX7UfDcNxxG0b453t2s1ZArr8vJ+VcaE9m8P3xPkhGtvc2dSGqr9hRHYbdW72DsA4fwNxOGpAfr7dPk2Jcm4mbBB56vVF3boFvQRTw==,iv:SfgsGTZzzDyhCro/0f2OPjWf6UiXSlFEN1FtxPjryoc=,tag:PB9eD4w1iy5sXqd/WnV7QQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:p7/3mGJ5dQQk6/UGDcwH7mf89r1KaaF9mg==,iv:qzUvx/nFIGtwDeMfi5CMqpep9hvfDfeSU0HUsG6+0Ds=,tag:pKY9JTtCzdst0Zr7DLMkCw==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:nFcE7rloArChQD82JnW9DUf6yE7upK/mb12olvq7,iv:do6ReBVfmT2eXx0tNwXoQIRl/Sc/yk+4emivLKlGO+A=,tag:1MFztDaQeceDNr6vzfjUag==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:OTd9avnOe3UeyMSoAf10uRuq58/kUBV3SkcHo1Rx,iv:feHm2byhiblxwLEVy4uXGQmQ67J4GN7sM690dluzZdw=,tag:yZCYzbkT1eKFRkJpOmCjaA==,type:str]
    SMTP_SECRET: ENC[AES256_GCM,data:WC1B3xr4x8x0k7Gx2eTVjP3EW0LlLkYntPqp,iv:im94WyuYmHmHYx0pUlngXdLsZJBdh/QSPENtB/Qp9OE=,tag:5MInjwTVA9OiITYcCjhMLQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:+3Sp,iv:yfm5lsQlyJrZHBalLsgzItthDNFxuwD6vaQwES6l3PA=,tag:QIQ+8UaPZiW4FKH/j87vQg==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:QS2b+zDZi+khpb+fht2NaZgSfo8VHN87zsx6exY=,iv:hayFe9Lw4a1g/4IhmT8cESFHs5uu/4SUzCq//XOyFHI=,tag:ynFy4k2JMVg/V4mJZZ4ahw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:4GQ9PZy8r98bSYLxsQdMJ1g5mPxZ0C0I7Etl75g=,iv:+mrUgHFB1mQfo3dbnYqzDeDRkqwFOcEdvYFLoiFn6p8=,tag:YaPv8tc8oShM1jxwbvbIZA==,type:str]
    YUBICO_CLIENT_ID: ENC[AES256_GCM,data:dW/c/Lw=,iv:sk4zjLVpRgUaoL1snWC+08b+NuXiGpA8bz9EDiwzKHU=,tag:RQBk6DYCMaLk9p6u6TKUHA==,type:str]
    YUBICO_SECRET_KEY: ENC[AES256_GCM,data:QBYowwNXrPeD0LgvtaAzUiXO/qM=,iv:FBL9f6QZOhqx5pkYt2n/wik1Mkallh9xGt65S1ESWIY=,tag:8wGGAVnmokOtcUx9/ILSMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYkVDMEZBRVpZd0lqQzYw
            aUxFVWdydG9ydkV5MmJkcDJlaVdzQm0vVkFFCkhjNWxubG1jNkhLb01iNWNlQ3Vq
            STVqWDNIZDBpSzBWanF6RWJkSGw5dkUKLS0tIEtSN0t6eENrdkcreTE1ajBWa0dW
            MW01UnQ2V1lMZDl5R1RQRG9qdDcxRGcK/3986PODhVceAodvsylyycxZfl5K/BkJ
            0tyaLjGqaZ77ctlLtXgZ9JYRZlaadSqPRpQ0kAcn5teruKSNuoNO9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T20:50:21Z"
    mac: ENC[AES256_GCM,data:3nbYOj075U191DMW7Mxpjo2NhP23FBZNCgxArYSSLRJeB1Y70GbGKJ1qlKDQ93n3un9P2iIYmTX8OY1Z9UcbeplsA1rAreUPC0C7vWPOMiXwQZ1QOf+XYDKahXH7mzjeTXay2DCHj8swfoVTcuZrL17245BpeIrF5ePglg2+JBM=,iv:3UxPnEMIOv8izRZri+5HwW9G664F0+3bm6PkDbTlajo=,tag:kShG1P0ryKv55V5/UqWaVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
