apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:swYMxIR9P2FararMcKP4Z06JXt6OQkqKuGf7Ukw6J/BunJAEV0VOOW+kTITRM/O1QqsHRp8Rb2Lwr8xTVx9RwZvdEvA+ODD2LF2UB+0q1NPc8YOmJq8ehNLwj0NCbXCUMiInNDUGPLEshpnij8sunJ0/f8XRLQ==,iv:6X9FeEzSwfDp3GCiV9JfrJjS+ZzTo2X2cMJa1agLFTM=,tag:zQ98asyTca71Z1+eRCj4gw==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:9ncCZmx4o7WmSe6odWhcNFK+ZblESMvJrw==,iv:34aaozcCWCPm3Ze8x+B3SrAd22J0KGNNd0s2KQcDJzM=,tag:LrjD3YuVCsejBPRemYrLmw==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:cHHalVVP8vozks/J+wM+1pkgBiwmEfZUFyTdx90Z,iv:BLG3H5pds90f7cJxzRdP31WHGbchFoXdt7k3id3vq6c=,tag:dkvWQJs9UVukRzR4N1A54Q==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:Mja/1pxeTvYtczFjJJ9GFvOW00kgOkQ4TMFefGEw,iv:mq5A78Ay4bytfXv7CsZ+SF8UQxil13wQadcaO8cnDtc=,tag:ozwrTEacyL9VCm9SY47ChA==,type:str]
    SMTP_SECRET: ENC[AES256_GCM,data:9w0k/ZETqi9YjWUhP4yfYiBktyIozzgiALPv,iv:sgINeL24VmwsVEecft9+PZV9BJn4g3qfn97Johe9Rj4=,tag:MhHv8Z1AUyf1aFRTJtA5Ig==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:pz3M,iv:tql6COYVO3psjVtUj67ceBYS6XeuQxtAu+ZVVRKlFo8=,tag:+XJr3dtJ8W7QIw80utigcQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:FrmENiwIsxNipuiY4PBAZ6NOk4qeurB1PfoTitM=,iv:S58QVsYYFdgHGcGD1ss3gr2A6hChUxtghr0tl3NHQD4=,tag:ZFnUGkvT3PGjMp0Khg3hvA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:vaGWM2fdx3jAzAfHKn//nicfvZTHdiyYlsDCdnE=,iv:l3JWM1eB/FaHIIHktYEuH9oQwFf0YdQiHwEE7uQrqCw=,tag:9X5VkhzQ6d23vbE9W03paQ==,type:str]
    YUBICO_CLIENT_ID: ENC[AES256_GCM,data:Jf4eSJc=,iv:06L6kHyoWzZ3J+psjVQCtgF8+r4025g9RRDEEZr+33Y=,tag:H6dxdBl021SAO+CNgeyUgA==,type:str]
    YUBICO_SECRET_KEY: ENC[AES256_GCM,data:IDjLzcTzwcS4CrLSL2BkI0hwa2w=,iv:Hvhcn5hVij1uMDZ03tP22z194EIvZ5WbzRQ1K6CVC2k=,tag:xB/C42fcF86SaO/dFWLalw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBac1VSSElMU01kaXk5ZzR0
            TVBxbDBCY05ORDF3RUhDVjNrd0sxa3FZUVQ0CmJ3MEFrcFlvNDlLR2NYODNjeUVh
            ZTdNZi80TmxoMy9yZ2lLMXczMURCT2MKLS0tIGN1K25MTjVUVW5DSUZkRGplaStB
            dEgxTEd5ckpFTEhXakgzU240aVQ4K1kKWreb8Y+zzroy1dlInycWfgJxovvxdVr4
            L3uW5jDsMjH/V0WFZUSDy7mFfdOuM4qdxDS91iw2FzK0e23gIBDzQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T21:26:12Z"
    mac: ENC[AES256_GCM,data:/FBb1iC/nkWzCz6I6OuFqlLXvf+98V5bo6rke+0zD5mV9H/rILybCj9bF0ZU+oiFklW3euBbnoiQtL5FZYS+5rFxw/5fvM4D0uxGd91WFX4Y2F40hrkzn/yFh91Kfh9D9Db5QVX26ea6VPsaDwkZFmTrikwxOb5rj4dY3x3oyXc=,iv:9bueyjj7BkdZdVj2Kb6nS0UHrdfDiF7F2y7zQO3Uouc=,tag:33ACwwjtsLRZs8OWojO8Fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
