apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:utjlZQo+fVN8CzWYPYBkCi3SbXd9zYYg3SB6g3xaUwnhH8nhag5hvilzHBQcTBF7B3am8vezOGqmBogyR/FXcA==,iv:28OfuBwsiLOGCp95/IPbKd/m2D6q5ZnpGsmJhJ7ZcKM=,tag:/pXDPg9TgVLNjraBgiHYww==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:zXEqR7qbJkubKI8uec5muAPbdM78mynsEg==,iv:Pau3mLRGtLU149AV4NiB9c4U9GznYgG6WxZcJwAAJjs=,tag:jDEnD3PdsYisIs0EltjvoQ==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:K4emFplgDoMBu6/A0WiwrCmLBiRxS9lKQyOXJ63C,iv:9hdmZuP9TbKwP2wSe3fJ+9X/rLY6UpO9kSz5GGsfyk8=,tag:pPYzuHapMxF/pUV10lXd/Q==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:9bcSXMzX8kqpuYs4BiUECA7A1CCyXAdi1SsCPEho,iv:vdIhybx22Qw/rHSwNoQLiG9NQQEBujX8lAziG+Elzas=,tag:5gAhIO6wau9po50+6TiTig==,type:str]
    SMTP_SECRET: ENC[AES256_GCM,data:wHZVfWX7DhpEPYO+6CJ1uGbPxHTxEqkW2WTC,iv:7+vp/1nanNJAK2NAfGwHUSZRkp0IZ8X8DzC6FpOTpUw=,tag:mURAJnvn8CV4gGyCguWJ6g==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:rJAg,iv:g77Z/VTf9lrRRO3xr6/aRCF01WJ9rtuPXyHerRI7ja8=,tag:m280h+V3RW66qvHGD1uo3A==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:SFOobcO6vYUDAjf9fB06WZj3vGWYR0sbu74q+HQ=,iv:6HULBxONlJHlbC0z3JUOclefS7rdMaxYU7XMgEqanls=,tag:7pxHQdLGlF29h/k9nCN5Sg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:1VIdCLEItzJfveL9QD3h81yoHqJ2iZYPtKL8aPU=,iv:K3ToFOXbd6u2EpxX+CgOKlgOjjTd6Gtpk/85tVhg7iQ=,tag:Bvb34UKSsdbtHf3i0XnNBg==,type:str]
    YUBICO_CLIENT_ID: ENC[AES256_GCM,data:4xkXE1c=,iv:70dVD13YHBwijLZ50BkWZU5+iXd8JaaFmEOEgUVDubA=,tag:iaYb5iItwVU6x5NCsF1Vdg==,type:str]
    YUBICO_SECRET_KEY: ENC[AES256_GCM,data:pCYawcijT0VM23Sfp4dlqmASkYQ=,iv:o5nG8g5gkz9CS7qDH5vn/Qu2zrzEEekH33dItJkSSO4=,tag:ECo8yKrplecyGLGmDfrwNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUDhhR1g1czl4L1V3Mk42
            Q2tqTG5IbWZIcDRYRmIwbDNPWjVWUEtXaEJrClgxYm1nZ2FXSVNxOVRueVZ3ME9h
            a0lMSTJObE9Wb0txTTZlM05rUDFJSkEKLS0tIE9qSzNoVkZJSUd2ZzRwTnUwVUEv
            SEpIVlJrYlNuSkJranJEWkdlN05LYjAKUDNH+CxFtVCWnBp1kO38Y6ESXQSw3dQa
            Nqc1tnxBo/2qUIvVD1wZNkpJ687kru/Ts2YRiJJHC851S0Me1svxHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T18:02:22Z"
    mac: ENC[AES256_GCM,data:DGXuHcMldMRxRPiLvntHmsSRibi3bn/zuysWJ0F3rw7o1WDNZT36FmhckPnL8/tCu7E+Z+wxNfHbJigKIEevS8Rmz5uNTvOyAXPRXJP0+LXP6T5FWVlOp2CnkunfQiFnukggF4XynYazzKckvPpmhMsh9XIIDbJLdVJ+YJFHM34=,iv:hkx+3P6DFEkR9AfRAgyd22rGyCe8I8Cu1xz0LjPVkk0=,tag:iUppJSACAk7JLDkm7fk0Ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
