# SECRET SKELETON — fill in values, then encrypt:
#   sops --encrypt --in-place kubernetes/apps/utilities/firefly-iii/app/secret.sops.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: firefly-iii
    namespace: utilities
stringData:
    #ENC[AES256_GCM,data:bxzqqynBz6JZTu992OZFDQbx453UPF93/DwV5/DVeSn5dxnRnBDcKBhgTs4qpIgc380MNZuJqGM6DbQ1ORPF+aan,iv:4CyWkobUDSJE2k8yNzkWGnbemQ81nZYrgFMZjZlt8Ps=,tag:WyLS9+VvIV/iw6PQJ+FOtQ==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:lAzAF0BJOZRjI5xCLwiHlJQXMGnwCZO2Y41pdxedfbP7s67TYZSPNFOKEYFSsEOL6/5V,iv:32OszTxhGGQ2mtDsoxerGXToVigHWXdvuLH69oGn7Po=,tag:4u39NH8XNfV7+/doQOcgqg==,type:str]
    #ENC[AES256_GCM,data:dCxMSS73WpiEPNksT5AO5trKWxdb6SKAJ+T0NhHBQdQpZQ6qw1jVJcN49kgaA6m5trgDgp0fAJA=,iv:Fq+fL49amdD3hN1IS6ePDrzwJ3i24qN+oftOlzXI1pA=,tag:5kqzpjctu1M6zwC04MS5mQ==,type:comment]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:VKnel1WCOGWMevBI9tk772F46dtsilSfjG2Se0K+Lyc=,iv:FGV/xgAvCAMd5l7FKVbDwe8+9yAvHcuZ8e766s/nkNU=,tag:hQqthmWeqzLGONdMOCo1bg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:MaUsQEmYwm+OR9+iWcv73HFc+dd1ApgG4eHmFcHJRAx2S7VnHpi7AQ==,iv:MV6z7VrPw4+j3XBDn8MlTapKmlq1nhiXzgL4rzlQPjk=,tag:2NgGoG81/E+sDP6UQEuaeA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:59puKlFN1Q==,iv:DR+pTwjlMVA/T2HvijoUY7sUnHnYAowiqIkTmgmEQcQ=,tag:qhTPixnsduZchECO8ZfpRw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:FhUjl/EHMw==,iv:vAmZEgc28ixJaspD4dFXq+SYP5G5WxusRT+DH+CHuRk=,tag:XLmCKbB7yxSK4gj3vFrSBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNDR5anUyT2ovOFBZSURw
            RGRvMjFmNW1ZTnlVUzVuR2dkdlpKWE93ZlF3CmkrdTNrYkVhdVRJMHlMT21hZHVU
            RXlseGFBRFVkUjZtb1FBcXlRWWJJOHcKLS0tIGo2akxYNzBXQ2JEZzJIKzEzZ2d2
            QjdiWHlsVWxaYnVIV0ZhUnAvWjdOa0EKqeIJx43d7b1opJGpbAVZpy/N7lQQYpOZ
            ILG/8ejSahcD9dQNB9tvA+qV7RocXEQ4aeQE79M7iwN4lLxywKC28g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T06:24:19Z"
    mac: ENC[AES256_GCM,data:wWL+2s+FDX0jX4oKabdUDkO6BZVJ1QCy28CEkxA0Am+sMJy5OVkt6uExJl7kJQyGlROrwSLepmt9TA+3qV1gVpvQvH9VuoUu0ivOEmT+b2cNr1M/ZuN13YAhVD7OigwqPVVNAFYZnRQMhgoEdiQ+tzytkedZmaW9zARxmVPotAs=,iv:znVsFacX8GaPfsJ0v7DOu+fodb5ejyrPFwsLDVKeYI0=,tag:SBbhGEJcXLyDCKHn4dLYcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
