---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &appname gokore
  namespace: ragnarok
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      interval: 16m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        node-role.kubernetes.io/worker: 'true'

    controllers:
      main:
        enabled: true
        type: deployment
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/lenaxia/gokore
              tag: v1.4.0
              pullPolicy: IfNotPresent
            args:
              - -config-dir
              - /config
              - -log-level
              - info
            envFrom:
              - secretRef:
                  name: gokore
            env:
              - name: TZ
                value: ${TIMEZONE}
              - name: RATHENA_DB_PATH
                value: /data/db
              - name: OPENAI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: gokore
                    key: OPENAI_API_KEY
              - name: OPENAI_API_BASE
                valueFrom:
                  secretKeyRef:
                    name: gokore
                    key: OPENAI_API_BASE
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  httpGet:
                    path: /healthz
                    port: 9090
                    scheme: HTTP
              readiness:
                enabled: true
                custom: true
                spec:
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  httpGet:
                    path: /healthz
                    port: 9090
                    scheme: HTTP

    service:
      main:
        enabled: true
        primary: true
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 9090
            enabled: true
          grpc:
            port: 50051
            enabled: true

    persistence:
      data:
        enabled: true
        existingClaim: gokore-config
        globalMounts:
          - path: /data
      config:
        enabled: true
        type: configMap
        name: gokore-config-files
        defaultMode: 0755
        globalMounts:
          - path: /config
