apiVersion: v1
kind: Secret
metadata:
    name: gokore
    namespace: ragnarok
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:p2B6wlfOPoB9QiS1N8k6WdxdiW4Xzis4dA==,iv:ePfcE0bZ1F3iVluPbicRaEuxdQNGQjKOVlbZpEvHvxE=,tag:reF/M656WhfETZqbcWHuRw==,type:str]
    OPENAI_API_BASE: ENC[AES256_GCM,data:aqJSCUDhYlyZ55RWqq6sKKZHYSnym9jUk8M=,iv:UoCKctigOdYP5+P0aniQCrWELWqTGiDbNKZcrc87Gcc=,tag:v9VpaPVHyaBs57lcSarXUg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNmZWUHU4SThuc09xaW1p
            eStvLzhha1NjSExvbStSVjA5WkRsbnNMN1d3CmxjSzJZck1GVGIzRUxYcnl6WSth
            VFB6a1BQNDFPQlo3SkFVbW5IK1pTaDgKLS0tIGpYNTh2L2xBQmpSZDVaNjdqL2dL
            YXlnT2F3azlpRUxlcUdsQkRMcHMrUzgK+/3UzzIY62Kwrckp4G7QleScMKJoplCX
            AGMPzmoGxTUku0K8E4/gyAqVETocokqJtBgXpAUVq6lrvkmtct/QUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T06:33:35Z"
    mac: ENC[AES256_GCM,data:C8rmzqZAAXCnn/+JX1OWO93curH1Ga30pdUh2TVMddH6jDG2YvWmhepkp6wi9dUN55FyhBKYJ2/k/TREt34I2syoWx0wGKVczfAniBsZTfBnEFTQPj8HbQTI2+ZcS4tWxyuxveXBBsq0LcONELDTVzv/C0AjNzL2WOfWQJAQJCU=,iv:10Dl6kG//BVe3uTCDe+3HTRoxFnAVIt5p5BUQMDugzc=,tag:NXTrxhxGC3hhyOBrOD3pRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
