apiVersion: v1
kind: Secret
metadata:
    name: gokore
    namespace: ragnarok
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:Asbqx3C8XLvR0GHwfHjcF4HPvzTMx3nuDVWpwvPLw8ePNiSu,iv:HzJiGIA6evxEej9t94G7DfWeIJSI5m96jX+K0SPVmxc=,tag:h4uptw3qRUXSDkI0EKU8eg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QVkwbjM5WFg0TTY4Z01D
            R2ludjNhOWZMbFdYNjgyQ2JrREVZd3d2c1E4CnhQbTZSZy9VaG5seDZZc2R5d1Y1
            dS93Tmt4L3NsZW5veXMyMEs3OG9NOUEKLS0tIFhVai9ESDFWTzVXMTh4c3Zna0g5
            UDBUUzJPRlYvRGE3ZDkzSEc1ZGY4OXMK4MPVncJZ2mjd7njwwL3JqtjUwbJdtsyS
            me8QWxgoD2RI/iptmyiVcCig0BfdtGpNPkAAZbE8Y+UWXNb8iBYsXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T05:40:14Z"
    mac: ENC[AES256_GCM,data:kGYwRvQQizikFBQop8uP3ALJjknXEqVGXJoon5qYM8Uxd7TNdG+N7rvuzzmwwOrGjeoDz3bmXOTj+X7+vAzQAcRV0JDYzZF92K4MTScf7KdowVzh1jHnmfHeCCNFTEHu7tRw/f894PBNwAb5FYWLdQ/i7TlNHJrtCCLEFvN/epo=,iv:BjzARzYOS3nqx8y2D7FQR4ycI3bO5cg/6H/LjPG80hE=,tag:jXPOqi/OYwjbFnzG4L6f5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
