apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - priorityclass.yaml
  - defaultpg.yaml
  - vectorpg.yaml
  - synofotopg.yaml
  - synofotopg-lb.yaml
  - vectorpg-lb.yaml
  - llmsafespacespg.yaml
  - dawarich-postgis.yaml
  #- backup.yaml
