---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: synofotopg-scheduled-backup
  namespace: databases
spec:
  schedule: "0 0 13 * * *"
  backupOwnerReference: self
  cluster:
    name: synofotopg
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: synofotopg
  namespace: databases
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.8
  primaryUpdateStrategy: unsupervised
  storage:
    size: 50Gi
    storageClass: openebs-hostpath
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser
  affinity:
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 1GB
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: "s3://${S3_CNPG}/synofotopg16"
      endpointURL: http://minio.storage.svc.cluster.local:9000
      serverName: synofotopg-backup-v01
      s3Credentials:
        accessKeyId:
          name: postgres-minio
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: postgres-minio
          key: MINIO_SECRET_KEY
        region:
          name: postgres-minio
          key: MINIO_REGION
  bootstrap:
    initdb: {}
