---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vectorpg-scheduled-backup
  namespace: databases
spec:
  schedule: "0 0 12 * * *"
  backupOwnerReference: self
  cluster:
    name: vectorpg
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vectorpg
  namespace: databases
spec:
  instances: 1
  # pgvecto.rs image — provides 'vectors' (pgvecto.rs) and 'vector' (pgvector) extensions
  # suitable for Immich, LLM vector search, embeddings, etc.
  imageName: ghcr.io/tensorchord/pgvecto-rs:pg16-v0.3.0
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser
  affinity:
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB
      shared_preload_libraries: "vectors.so"
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: "s3://${S3_CNPG}/vectorpg16"
      endpointURL: http://minio.storage.svc.cluster.local:9000
      serverName: vectorpg-backup-v01
      s3Credentials:
        accessKeyId:
          name: postgres-minio
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: postgres-minio
          key: MINIO_SECRET_KEY
        region:
          name: postgres-minio
          key: MINIO_REGION
  bootstrap:
    initdb: {}
