apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: nessie
    namespace: jobhunt
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ZoBXnk1zDA==,iv:oMPoQkepnIxTXgRqo6p/n51CZxnY4n8yZixPQxToGLc=,tag:Ct9UUC2LJD6DbApPvHehDQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:IjA/1RFMElskXw9inwF65/qz81Y=,iv:5BDpAhuduKuDUtPze5TZUiSdFVD8cYmxpYiP3g10qWk=,tag:tJfYFkXiJkVnaO19oLKwZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcTFhNno3ZTY3SXdyQVdB
            cTlYelM4RDhoeGI2WnI4RDlXTUZ1OWVvS1NjCnlodWZTSllMY2VqY2VDTjI3b253
            cm5yWE9YaVhKK0JMdmlKZ0hBV04xQ0UKLS0tICtTbHpLZkZOQVYrUlNwcDFZcEZT
            a0tOUmI4djBiUlRwMHRJengwLzJyVVEKwAnlX6nT15FE+hoD9/wthI6HalriZAyW
            VlvJerNpBemkGO3XLQShaG0NknYWo/nJIRnv6QI0Oy9YPxHZT+0WZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T01:21:07Z"
    mac: ENC[AES256_GCM,data:saAO78nQ3HOYsOKkfaN+xXolURzqpY1r6q3nJWMSFWFLgHmeu7xrtJT6r/klJDxsXFBZJcXSQVv/VP5KVLkB0RgCIWkP4KeflUULZ8LkJANutJ4bDg2IO/oSt7zAZLPDTSvjQro7OAuOg7EisWB7TbO7UMTx+C4Ylv9bpg7abq8=,iv:pc4gx2Q44kB/mvI0eeFPacRLEakEEZLv/Cwxw0gsopQ=,tag:jkETiXoYcxBGdYySRZRcRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
