---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_EXAMPLE: Global secrets for your cluster go in this file, this file is encrypted with sops
