apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:r9wJDQTrrXU=,iv:fosxoRp4duEcaTyT6oAQRo4H6DAIAPXJXU3pWGi4ZRs=,tag:fSSVRD/yk6wPYYgnAUaJ/g==,type:str]
    SECRET_SLACK_HOMEOPS_WEBHOOK: ENC[AES256_GCM,data:dlGdQdTtpxRpqLNthbBi4NNam0a+zm1kBLkhSAg1rm76JcWEt2ViJLePSZXcRxmjpqYQRDiU37X2+35V379tqHhSMVgj2JVKnSNqjgyuvA==,iv:M0gSIuRH9l2Cg0NuXZLvhv+yr+2PwMtx+g/iuayIQbs=,tag:C8r6jcKdtsdM2+g5hXmTUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUkdZSVVXNFhCekJaRFN1
            OUQyYVJhRFFwR3JzRjNha3BBY3ZPSWh6R1cwCmo0UzNrKzZkaFBLUkxsTHJDZzho
            eVFPQTFSRjhGRlFNMTgvY1MyZE1QRW8KLS0tIHJiN0MzNmFaREt4azdxU3ArRVNK
            Vi8vT0tjb000cWRmOVNxa2MxTnVlTW8KntLBC72gIwcEWLPcftB91KbfpiyD56sU
            7y+2LHG8ZHoitjcsLU8j2GpRHitla+AC5QcNoqOjuDd3Y7LOjdYpyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T05:49:42Z"
    mac: ENC[AES256_GCM,data:gVhh3H9bSmZUxFaWCw0ZWpWGv3vih7dmFCMmPszfcWEaYNFyKLb7A93t6XjJCLvbiL+q41Q6XlxjoOGI2iNqIl7BlwRYMJBXmno3S85uRi/NsSANWUu2wBGkAbf5+qPzr0zjXFOd6xNRjGHKRnnwn1BDsHx6nhM/RIPz3chYUGM=,iv:98evw8tpQ2ok5y+21q7OQbUUlNc8T0HnP2XVOHiTLMk=,tag:8y4zglbcpmtiTWZH21WNgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
