# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: subgen
    namespace: media
type: Opaque
stringData:
    PLEX_TOKEN: Jz9jqihpin5DUmRBup2e
    PREFERRED_AUDIO_LANGUAGES: "eng,jpn,zh-tw"
