apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: tinyrsvp
    namespace: default
stringData:
    #ENC[AES256_GCM,data:vyt+MxxRGn5eeQi5j1Q2ZvrMl29ZQqSQzegWD2BAm/aQ71XC,iv:pqPNNy8aUIkjv5/msWvm1clZMj91gn1oAwFzBOsAoho=,tag:aKsbFXUBjwJiA7dMn3H1UA==,type:comment]
    TOKEN_SECRET: ENC[AES256_GCM,data:K9Y0/UsjpzhNRJWCtf2QcNZNdzXH1xaL7R3z9c0FeJPg7AcY/05jeoenyxqbKNVujY1L/boVRBq+kN2a0/d4Xw==,iv:mNL/5U0c4j52oL+e3p/c5LZ284YzTJ42L2y54rLa8UM=,tag:8aEIpIU9ZG8qmDDsWeboKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS0hQTndwamtpM2pEUExD
            REVzSjBKVWhnTktEeUU1bENyOU41RW9Zc2pVCk91bGJOeVdoVThRb2lzN3RVaUw1
            Q2RaUTF2WS92YjMzaXpZeExMbDJENXMKLS0tIDQvUTNFMGpaWG9JQUgxWmVwQW1y
            TmRjTG5HNlFkdGQvTjNMRitQK3ZUSzAKhfcMlCNsZxuA4PR8qSkfnP0NiUIqt2Gh
            1Z0iy6jXW1wYaB6d5WWi8i6hwicAaEbgcnveFyVldzr9mSGiBbtuCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T16:18:41Z"
    mac: ENC[AES256_GCM,data:7ccjctrjCB9W2GtnVZtngXV7vKv3oFry6CGoxcK8spoOK6N6YvSQ85tih/vxXg24yLame31L4WxyZPKELd2meU39UsK/ULsiWh9Vr5qYgmhDWjpfn6exHePrLzVJio8o07U6s8Rg6P8x000/7Lu4xx7dBpdrKsJQMJScGmwDAwo=,iv:Z218mLf5aVPKHAidP9yzTKPlgSji4PTqkqcHJ/xMJAY=,tag:MF2p3VVn8IOFU0xaiGSStg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
