apiVersion: v1
kind: Secret
metadata:
    name: mariadb-operator-secret
    namespace: databases
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:HgIYoiE8j7A=,iv:BSBhJnUAxiTRKdrIu+/cQBTr9lAB9vxD3C/3Ty3inCE=,tag:Izuk9b+Us09FosIhW4+XoA==,type:str]
    user-password: ENC[AES256_GCM,data:R3uD8gpaXVSTY3mCEdeqvug=,iv:XiNY0/s8vFS8M3d4hRiLReBjKofyNxMyFUm1HtGZDmw=,tag:6iwdFPpmJIeUi6t+IPDxWQ==,type:str]
    hortusfox-password: ENC[AES256_GCM,data:2dmAN8sZDXnEMR1aDYnquMiBfWx1ADD7FFY=,iv:80y7TycrchVh3umouqiZveBCegLxSTm6apeiMAvbVjw=,tag:X6FlP+47128AOmKBZonIMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N0d2Q2VJRmRiMlBvRVVK
            TzlteTVRYXBaNW5HZnljN1J1MFBFeHlWM1NRCmpseWNsSjBOQlNCc0ZhdDAxOWRq
            UDlrcGtPUmNJZDNGaGFrSENtN2JHVDQKLS0tIHB5elBYb0JjR2tIZlEzME1hQ1Zn
            MTB0VlB0aDJJWXZSTk9UeHM3N0RmWjAK7wJmuJqmUvbAtp8p1+fmp1Zz7dA9fnUj
            kMJe98cCGWuFUJOse0PeW7579Af0WwM7g24G/tMQr6o3/O+yz7zPOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T23:20:09Z"
    mac: ENC[AES256_GCM,data:n45kkXlKxEAU+RoYl/FJASoS0JydieUkkgq/7jQWPW9L3vr69t5SAlBnDlARWDYO4sTu89zf1OZ9DGC7cvipXuXQLdbuhxp//eavIbRNwCd6ajxziYBt+vL9TXwwlTdnjiOwsUa6RLZjh4UM0EerKzWMKMQHwmXwP/rznYv5yVo=,iv:I9AKYTFRcxt6anJyjDuyXtQsIjsWlW8LUCpeEVmEwwE=,tag:iVFS/dhuIZqzhBH/lRiIeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: mariadb-operator-s3-secret
    namespace: databases
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:1dt4YUhOthA=,iv:Vlh6B+tpgHWohpt4YdV/03bKobw+r43Hgx6VTTDr0KA=,tag:fSpDs+Qa4eGIxvN2rKM78A==,type:str]
    secret-access-key: ENC[AES256_GCM,data:4tTXY8IYMHk=,iv:sv/q/13UoX1taXAafpLT36cm0nYxKc49zwFzSaqvEjU=,tag:Om8LGfsPRynjbR0FUXk2OA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N0d2Q2VJRmRiMlBvRVVK
            TzlteTVRYXBaNW5HZnljN1J1MFBFeHlWM1NRCmpseWNsSjBOQlNCc0ZhdDAxOWRq
            UDlrcGtPUmNJZDNGaGFrSENtN2JHVDQKLS0tIHB5elBYb0JjR2tIZlEzME1hQ1Zn
            MTB0VlB0aDJJWXZSTk9UeHM3N0RmWjAK7wJmuJqmUvbAtp8p1+fmp1Zz7dA9fnUj
            kMJe98cCGWuFUJOse0PeW7579Af0WwM7g24G/tMQr6o3/O+yz7zPOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T23:20:09Z"
    mac: ENC[AES256_GCM,data:n45kkXlKxEAU+RoYl/FJASoS0JydieUkkgq/7jQWPW9L3vr69t5SAlBnDlARWDYO4sTu89zf1OZ9DGC7cvipXuXQLdbuhxp//eavIbRNwCd6ajxziYBt+vL9TXwwlTdnjiOwsUa6RLZjh4UM0EerKzWMKMQHwmXwP/rznYv5yVo=,iv:I9AKYTFRcxt6anJyjDuyXtQsIjsWlW8LUCpeEVmEwwE=,tag:iVFS/dhuIZqzhBH/lRiIeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
