apiVersion: v1
kind: Secret
metadata:
    name: hortusfox-mcp
    namespace: home
type: Opaque
stringData:
    HORTUSFOX_API_TOKEN: ENC[AES256_GCM,data:h9CtgI498jIUhyRR8pZVts4l4vwKxdlLwJaDVr14a2k=,iv:pNSfmS4rMIaYndQ2Id8YYS7su/fcGhULTt09rZNfUvk=,tag:9PUu7co+TpNpCf6Jzhrsvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVkNyZ0xoV1Z6TlkxL05B
            SlZJQ3NHYTdsYmtyVHBjZ1g5Y0RON0xuSXpzCnd5aHkrY2V4dUFQYTFacnRFMFVG
            aElKcjg5aEwrcGZGbU1ubjhKejhRbEkKLS0tIEdTenIraXl2NnFJUXFwWkNyVGNK
            azN3WmJ3Y1NISURtcmNRaEduZGlQNm8Kka3/clgjk/dpIUG4u+igoDVfpZzRHqhM
            ugZ8yJtfyNPQpFmdhyTB1W/ypSoCHA04zCSWDKekH4Hm64e5jXqO5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T21:05:23Z"
    mac: ENC[AES256_GCM,data:7dEfAT9MDowJ+ynEGvrRBJnyOL3GGmSveH9XTcYF+P8i3uInA6pe9xCzRMaiVe6oQ9kNBBifIktUX/SGuURAIqtOrPQgmmjz5oXmRBmaT2Uv/qwotUHHtlidAtCYMLFCCgxJegtKbtuLtvOJKwJEdT3br/Qzlaybdig/l0niKss=,iv:D4kR0XyEg55BA13m3lmnu990oehywuDAThgiXbmLtoU=,tag:cftt121Os4CN0EVaqJlyeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
