---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml

patchesStrategicMerge:
  - patches/multus-daemonset-patch.yml
  - patches/multus-initcontainer-patch.yml
  - patches/cilium-initcontainer-patch.yml

#configMapGenerator:
#  - name: multus-configmap
#    files:
#      - ./resources/00-multus.conf
#generatorOptions:
#  disableNameSuffixHash: true
