---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llmsafespaces
commonLabels:
  app.kubernetes.io/name: &app llmsafespaces
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - ingress-frontend.yaml
  - ingress-api.yaml
  - middleware-cors.yaml
  - rbac-relay-creds-workaround.yaml
  - networkpolicy-relay-router-api-workaround.yaml
