apiVersion: v1
kind: Secret
metadata:
    name: ansible-runner
    namespace: home
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:tK9AXz0=,iv:UUI6rFkmCb8I94JprnzgLRaLaTTucnwJnphqUg55VNc=,tag:H64k0wrH9rYXvcVNS58Mxg==,type:str]
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:uztGmiM=,iv:WVJGj8MItgeBJbxkxRx/pqR+HsQBYDx0C1YwYuxiHTA=,tag:Ylz/R7uTyG1BDuAKu8nb8A==,type:str]
    SSH_PRIVATE_KEY: ENC[AES256_GCM,data:o3kC1Q1nOT6o54zj+DQ9t0oG1R8N94ZcbTjV5iwWp18r/NgFkutEOOrHgbIvGUPxk63lkZLrZHzCDgogctNLNhffd3D/m7IY39rcWQxe0MkWoMnbhqUOqpXUcj6SpUEfs0yiJds7+8MzfLrmkFwhjib5IXcqlKrubG02ELnMAZNlS2YwrAevZjz1mogdsMuK8vwG9Qq4gKw84lp5mFd3L7nCmolaxYpTSD/6ufxSBvIsaI3xhEcbpp/c/gpB21G/T0cueUdGFGLM3gfrRqqS6MloWx1435uFz6/7s8+T193oR2ycD1NrmWkOnUO2rcGPOsRzDGO+oN4a+tS7WEAiCQMacY+4ScGC6TcI1zcJ+N7XyxLgFyjjP4YKai2k9qPUNU7YJMuMCHWW4JLhsBlYRuaTFiGYf0rIUy50hvWUEBBHBVXru5bTdQ6+LUFz+guC6RDTbxtPMSCK64WdhfDx0kcQzgsqKfqy3UgAff5WeikiGN4rYLKxqXNXNY0wsY3+IiTWsJu8FHTXc3BvdFvyUvFQIxcxRPApb8QN,iv:WtU0eeXnfj+PJ2JYY2PbOAHQVo+C2ssfMaS/ZLwAuE4=,tag:0FrlzYMsxNjkLPIca4TxDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMVdSNVZzKzNXZ0JiTkdu
            aXV6dDFxczczTnlmVzVNeVpjejJNcDZGajJjCjBUWkJQS2dSMklvcHVpQVN4dGNN
            WFRPbEtCZmxIWVZsdEpaaExSUWk3T2sKLS0tIHdZOHdURkxzZm5RV005OXBVVFc4
            WUdIbjVRakVGU2hCeTVxUWtIU1BLaFUKdwP2ENrzhJwF5dKHXSa19aY9WacPu1Z4
            9uSa130G5KXMWQ2ueiLlU9g5rU1pk6wtpvlFkJLXpPPHmImYGBrtYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T15:35:48Z"
    mac: ENC[AES256_GCM,data:asFnsQRx9nTs3c1nwxtc5t0tT4d3VyBXLynfuGq5yv1Y/W/FQ8ZX0qzmEEianTiCVoSaAFDiIU5XoKjGjHnivLztG31C+g236XeZEjNigiKdMcMvT93/u7g2Ixm2Nv9niDV/d6dztNm5JCtO4RjyNekpGSiqFJCh7ly7/dYS/HM=,iv:CQAu1rTOY97fWmb8o4oIJBHh82IkvEwMH29+zQhZpVs=,tag:GXfWxqvpXcPs2d0RUvkyng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
