apiVersion: v1
kind: Secret
metadata:
    name: ansible-runner
    namespace: home
stringData:
    SSH_PRIVATE_KEY: ENC[AES256_GCM,data:hTSJEu8JzLf6COoQj9TJ6D3IMlS6Wxv0TUm1oG1GTPV0aIJIr7xE3370Vx+1OVIYftWG4Hf3la4tCdJECzJI29xB+g5csaT1X6KxKm810dNws4kCKk6zyduziBJHTuUrheRZxv30mau8S2R5ehnTfuRPqa7i81QVq+Y/mZIJyoPL9AojZTpP1dND01iYBVzOZVq4Fjsr8ZUTH+hIvaBJ7A2j5RiM0CiTX3P9AuJQ20a0XYWcg/47n0PEnVPVov/aQPOlH7/kwAASciFvP2gfPKjqoosUDYPNp6+J0PShFutr7r57wyo6EohDF2wy/g/JuYa+Wre7mEiaIEaBS4qfEiU0d7FYI7fOsR670VTc36jcPg5D5PZJvO8VouvWmbQB+yFiKArHqurBQzZZz9dAb1MaOfUTVWsKAeiKdXlPEvTqoT5sskq+fW5mP0RA4wRn6jjCenGZUak54YvfhNeuPrajhJKNfuXbnKRqUrP/w6vSawtB7AfHQYCu7ojddJcnF3ZICg3P4NVKzQsPja/lUVtUKkfnfKi+DMZt,iv:u7/pf5qm68rfJkUPEBHM8MOeyLoDL6k9FfqNEcYEN9M=,tag:XMJTfWaaeUZCnWvww9z5vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFBmR1hiNmIzbTJFSWl1
            K1hCYjFCYnp5Q1V5N0pTcktjVGhidWhyMFhjClpLNjJEY3lSVmhUV09Qd2dVaGFh
            ZXI3OThHU2s1K3BNTXBNenJ4MStuZ00KLS0tIGIyWTM4MDBlempsV2wvM1BiY1Rs
            WmtHOXhqNTBzMkllU3JuNWFzMFNmRzQKg7Igm0tKSSpzYjhQHg1NpItkSN2Z+MO+
            VUqvHbonyOtSbCMHezQnyMglQnl3e6cPLBTizVOUOR0gNDqkhmhh9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T06:18:46Z"
    mac: ENC[AES256_GCM,data:Oj3JlR66VIU9UUQYid/XpPXsa6KRLcyQT3zhSkcmJfnSioW8o7XGUHJwr+uGpMmdHQD/Vq+1/KqZAAdD7B/F0cfEStTYGkaUaalX92UB4e1cK3wLjGYNsMDNUOk6CLFjvAQ0EPVMmZe+79ki2h9uVxxwuR4qCFGW2IspuGv5zXY=,iv:kdnOJV1/JfqPHdufZG1QlGZz6C1Fvwrprbi5cECyLE0=,tag:JfPGXBQl4iYWuCsQ/AZN3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
