apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: oncall-sim
    namespace: home
stringData:
    #ENC[AES256_GCM,data:j200JCcVT9uVqvIav9Ffw4hmex7YtxiMCUr4eoK8rf/JuZ2eJQuDIjXXUw==,iv:6UAoZWSz0BsIfX4J18duq+o4u5o0MPmeY7LEfAbcCjo=,tag:84RzUb4fqaKJWUii1fkfRg==,type:comment]
    #ENC[AES256_GCM,data:Fo0X+TQET69omdsoySEGg5X8KqSoILpzGaOrbvB+T/e2Q527p9g/aQSkLZEXLOmDKZs7gzBNFZ25c2ilDfyF+mtd1jzWP1S1RqEdWA==,iv:Q/JYaQBQfF7zZldPS/KYPvs8HXJr/vFYZ/0XwWuQmRs=,tag:0RclDzKSmbmP/ZfwTUlmCg==,type:comment]
    LLM_MODEL: ENC[AES256_GCM,data:VpTOn2nD0gXfv1TpoWI=,iv:RCBcqiDlmbFhOHvQjw6eY/284kLFpd9rFAlg27q4Bro=,tag:KxvQ/31cVCQM/ofrLUfKDQ==,type:str]
    #ENC[AES256_GCM,data:7JTv8zuGzdAC/Kp2xharAzltECsmbQZzbP5FkjWW12y62Jyux5W8KpJbW4Al5FHaHQyl1MJpoyMiZF9M+hJ0,iv:wFpSsz+t17q75fo5fdcZWpoysn/xZ6zR8CDAfzdu+fU=,tag:gcL+bK1B6bvOyxR5bmqToA==,type:comment]
    LLM_API_KEY: ENC[AES256_GCM,data:/YhA8FiS8aGzPyivciHTu8YAYOZ2khcxTA==,iv:lblvhJTM4uJvWy+umAeSPWKVDuS02LiB1qku0MTepKw=,tag:XomCVPkOo8w1ZqXQjaJU1w==,type:str]
    #ENC[AES256_GCM,data:RdJzPUU3tlQG6ZNV8m/ad2KJbJ17f2e4nfiIfQg4NhO+06I2wyksKogGYb4xAiU86vngLJgnFUQ8D+Fxv5FuNicOSJ4=,iv:nVfAlm4EO5u35MhaLDvVte4yaG441ODcrAViTAFRVEQ=,tag:bTUqOpL2ubUU+ZTd2t8Jxw==,type:comment]
    LLM_BASE_URL: ENC[AES256_GCM,data:/l9iFtMQanvcehH3rSglI3K0/SMdUy2ic4A=,iv:aBV3YxwSIsD17yn0v7Mi9JIO+6a/GQ0/IxmhQRliLcI=,tag:BrgVyssns8+qmZSYikKzdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ekRuaGF2RTdNZ09tcHpV
            dE5PZS8ydWhKczE2NEVzMnRDVDlHYUN1eVRjCmRLVW5jMXhPQ3ZWeHVGYnBlNEM1
            SW9BV1E2Zm9sS1VjclVNRGtsZkVTZ1EKLS0tIGVrT2Z5UExpdGQ1czNjSm9IM1Vh
            VFZCTVNwR09ac2EwWHRIYVJUUmY1cE0KIIH4OzF23zV4CIlfk01b/1UOd3wIBYX/
            7T92dOgP9z6qbivef+JLyAFo92uTEePoSIXyT8mhOYYUiJQ5Sc5HEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T22:10:22Z"
    mac: ENC[AES256_GCM,data:1cU040vRFb5XcIEZnDV80s8i6XUMBPUwwTVeMu/FnwFihFQbc1P0YZD1Qocn2nvWi8/IyBipkP/01EWmujgS7UufNxtuYjpxQfDkTEcYO7517pu6uBZ6rfa52x76vHzSp36F4zjUgNh415jcKjLTaCwlHSx3uAuginOzgp33FtU=,iv:o1hmbImgFX9X8rKFNqIY+kKwJcdaXE/71/KSNHTRWzc=,tag:0/H2c343PsrViVXZeFBj3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
