---
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: python3-manga-updater
  namespace: fission
spec:
  version: 3
  runtime:
    image: fission/python-env:latest
    podspec:
      volumes:
        - name: scratch
          nfs:
            server: 10.96.71.134
            path: /pvc-bda72dc7-8405-4e16-99a9-a88be18d5d97
            readOnly: false
      containers:
        - name: python3-manga-updater
          volumeMounts:
            - name: scratch
              mountPath: /mnt/scratch
  builder:
    image: fission/python-builder:latest
    command: build
