---
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: python3-manga-updater
  namespace: fission
spec:
  version: 3
  runtime:
    image: fission/python-env:latest
    podspec:
      volumes:
        - name: scratch
          csi:
            driver: driver.longhorn.io
            fsType: ext4
            volumeAttributes:
              share: "true"
            volumeHandle: pvc-ef74068c-15b1-4151-b64f-7fc8e946fde0
      containers:
        - name: python3-manga-updater
          volumeMounts:
            - name: scratch
              mountPath: /mnt/scratch
  builder:
    image: fission/python-builder:latest
    command: build
