apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
commonLabels:
  app.kubernetes.io/name: &app vllm
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - secret.sops.yaml
    #configMapGenerator:
    #  - name: vllm-license-py
    #    files:
    #      - ./artifacts/vllm_license.py
    #generatorOptions:
    #  disableNameSuffixHash: true
