apiVersion: v1
kind: Secret
metadata:
    name: vllm
    namespace: home
stringData:
    HUGGING_FACE_HUB_TOKEN: ENC[AES256_GCM,data:lOaN84w0lR/wN0lb25cn05ue6g3C2H4HCsJEaHKX0KPDxX1sOw==,iv:6KiFpnMn64+FW03IAeWDudfs2zq2xUDjxX0VkRkXOSU=,tag:FUrV4zYdVHcdLM7vi+VQzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUzhNNUNCUTBjazdXcWN0
            Y1VlendjZzFaYjIrOUQ0RTlTSXh0N0d5UkZFCmFsYmFhajcxa244UmRTaW5pTkRC
            aDVzWlcvL1V6bm1NTnlFZGxieDJMUmcKLS0tIGhsMEFHbWF4TVB2QVd3MC81UFc4
            MkE2SStCdFdwaDRxK0VwVkVIWVUyWU0KqzDrIc/zrepFpKtkISzFpN/BERmz7+UP
            JE2mx2awZzRQ5jRtxY/LSrXMUyxYIuU4QgW4qdhbHKBiKh5VyxlOQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-09T03:55:11Z"
    mac: ENC[AES256_GCM,data:7E7E1MKVi8uygAJqGGKB7+mTAJDUwRG+SgmPq4wTm9+rSeZcO9yezl9UNVNPaNjHwaE0rT8YvxzZC5QJ2nUWITQGosAlwxHnEXJnLrgZAGpq9ITMDytztq/RF/UlNHwLoAqLciLiriJm6HClnE0cmIBqXDBYpWiE/GwwywBlU00=,iv:Pw0rFxi75XlGhlJ8aGJcrNZysZRIACZC55us+NRcIWw=,tag:apAcqw9v331Mcss4FhpDhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
