apiVersion: v1
kind: Secret
metadata:
    name: vllm
    namespace: home
stringData:
    HUGGING_FACE_HUB_TOKEN: ENC[AES256_GCM,data:LwKATeRx7qJZDpaAwRTG13AImgQSwTS8VDtWys6Gqr6Q8nazYw==,iv:CzGpDd1kSLoUSnkWSXykXxmoNtIChyEjW2S2x6RaFXs=,tag:OFHV9dZ7qcN8D+40ADuyEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSHJleHhoT0dySHJwcjZv
            aFBWaGRlRUJxdHBPN3p2OStnU3FWUlpFVG13CjBWaGZObUsyaEZ5KzdSL3FZbm5m
            b1lITGVtTFBSYmhMY2daZGdHMVBTKzgKLS0tIDg1ck0rM3FYVUVLM0t2UEFOVHJT
            MVV0ajBuVVlwS1lzU3R1SDhma1RqNG8K3Rf1zco+t8TyOuoQmQ1CqFuR4X+1C1vY
            ksuAPI1MfKbLwgMHMUpLbg3tUa8cr6YgSvz1xL/nRzwX0rQeO29N9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T07:10:29Z"
    mac: ENC[AES256_GCM,data:VEZ7875dgH0bJv7WtAoM5Y7yQntAJIGqFHQ6nEITj/PTBuKBsVmZ+AX+u1vCQR5WdafYDHyPAKnxyH2Rrin6Pdtv0X4Kh7khi8u02X/m/9U4yBY6HdnorNDDl3HehPOVONaaEOmJIl0lqAVai6t0VEMJvwsMd/ovmseyGFbeYdk=,iv:Z+4aDmHa9BaYUIPyA+VVkFqIwso1pB6tpphg2fanrTk=,tag:U9bTNfxehITlbTV0T/RAPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
