apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: llmsafespaces-valkey
    namespace: llmsafespaces
stringData:
    #ENC[AES256_GCM,data:PxjZVXvTxk44bppSfA26AJ8Tyg8wiY7MrxuSoDO/EKKxU3+s1F3xr0/4T5+G8TzunUAA,iv:amDZPF6h98VUMjmHvCfhyWQZjoonixv97v1IjF4OIFE=,tag:fFsgDSIC+n1LO3CAFgwqmg==,type:comment]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:h/DqusQUwT2O4LIc5ijIxU4wjd9M6eLUKzQSbqeLEr8Dc39mpucF1DbR,iv:bNVq3+aTVxhJpSlP1HRNTxJj4pK62UPHp5apRBjY4Qk=,tag:H6dX5DA2ldZGOXiU3pw+XA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUFdNUTYvL3QxaTV5MVlE
            VVZ2QzRUZU1zakozZGJPUEdtcXhkUDR0YkR3Ckhjb1c2bXZOS2FCR05FdFhWQzhZ
            eE4xeHVleitBejdsQ1N1NmxWczZ2RVUKLS0tIDBhRmNHN21VY3JxQzAvZ3V2a01N
            VkFuTDloUnBwZ2RSUExBVUZjbU5Eam8KH0uRJZ0dNoBQjkvSopBO6nsI/CkozbKG
            MHIFzX0YgIHpn+XXFW8PnJ1MuwJh7PCoFfQYir9sl1fNx38gMxoPFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T19:42:10Z"
    mac: ENC[AES256_GCM,data:Btfi9ollvnD2FPK48vVjwS6ZYsxQzxh+WBWY6sIWATnAp2k+MpsyoAR03c1WR0w1Jjz+OkAqQzMlR30wR85YIMikH00S9fL8OKhvsEz2fEBou3LZlg5ZZhXOS0VNlFVsE5Ql+1ovUM5yB6/r7/ajNnD77fm4y3w9DaUvdct7UtI=,iv:mDxMpySv4iCFZOSdbxl8mX8CbA9ReKaFoUaschs9Usk=,tag:DELIjsr+F50jYDrnLdnhKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
