apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-ldap
stringData:
    config.toml: ENC[AES256_GCM,data:caYpxZxlNAU8Tcx6mGxzM/PnvFrxRrrn61aJXc5mYKqSraGjUaA6gYW1hBp9geDaS5E9W/m9izndAWmJb5c4cUR7P9pbd0n8kuyAhR7FaqJQYpqN8ven3txJRO9M2lYCMtcn+q6TSC+rlOFIMTe+Z8Jp05lXJF51F0Gky74RA++0ItedxAyEmR/F6aN6ANekq6aJghYXa+va9WdhScqwifPCohRqy0sWcpplVAnomu9bkWswi7c31JwZwGFtf0sfGJv00jdPyyeU2zDfwgiylQEhn2V4HoGLlIO6PB996W3z1SsWtj0PMuJPmdFEjb6eiB86kw5xrfeSHCV/u1M07YLiPsWnp5tKrWl/DPDYErrFyDjaMO9T3amy8vmmG+mhK3NXJyV4XVD76FBERFrsitFBFcQmQVZu/IiVnKDaLSUsM9A0EwjhKvQICesxaImEFaI4DFDKqlgF8UyV5MaThYclIWNAA4IvArLm2kItYbWK1z5im0m34YMQqmtjO+9x+FKN3/ycbQj8GI08AIyp3AkAHAzcEy2v1yWemObo2XNHY9KXBhWRrTUFpzyb1mWWERXokL6/I+zqS4TK39O86sI/yf/aj74Yccq9i2mW9PeW,iv:30Dce6+Vc952n8n386DAOpIjdfj45K8EGcJ4lOGaf/M=,tag:xKc0j6pp+L+3JmZ8+e5BDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOURhalpGQ1p6WnZDRU1G
            am01a1pMN2l6Z0xjZk5ndFcyVEx1RERYYUhBCm9PSkJqaHZ6eGNJMEVCZ0hJRFVE
            QkJxS0NCZDFtQUJlWVI5YU5XOFl6a1kKLS0tIHdPMGVlRWkxZmNYbjhCbHJPWkli
            NTM4UlMrdy8vUVdZWWhBUTA3YmtuMjgKPj2KmtfmEqgfkNfLRWxwiyW0Ola0rv7f
            KDA02kuhxyPv4xnZZgixmdK9YgtIwMCbzALq3GKvzcYJNg/UuUfO7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T17:59:03Z"
    mac: ENC[AES256_GCM,data:MiG0+zkFhSsl0aeAnZMuUGwKdWNMvYC3pY492i5gknceqWbqdk1Sf6whU+a+D5GrkYqKirleXlvB70vqLUBH/rAGTSLtV6PKxsOpKnCN6njgA+DKNaaNFvnaH5Wc2+2bScjXRR5AijlkISndR3C6Kk60FMHUO2PMAfRU2EfSkxE=,iv:SsxPPGMNuNCjhRFlZUGIzU/2hyWWcd5Eb80U27qtz5U=,tag:zygNQkf/Ak1nfyb8yybhUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
