apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-ldap
stringData:
    config.toml: ENC[AES256_GCM,data:CoqOCI9mosulUVaW8ybp7FeCv35hZ7L0W5rWymkTsBF+9lFI8EP6yhONdNlpoIhQWLkSWxOJw0mdKNnNO0UqOtxuUZPEmj7A/6CdYPmGWLa3iLAyNg/ZRA5AJUc9ELxmf4R5RK82q8f8KyJtt7S2xHxNseMcseUZxsMsHhEaDoJtXNlFCw2XN9+tK5VnUeljOg8H+6tpX7T6DzmHpfcvtkuelme7DQEhBGgnH/2oppJYYA4x98h/gk5RgbbSqVG0duSyWcG0o8HunqZyGwCi+zpcTEHUzxzq4yL5szHyKyBPmzq2s1bUDrGyLQjrou034nho+0oPJKCbd0z0aJi1yk2fx1LDOPJqBP7agv+xHWoTmf2HMJWxfpILv8foE4D5RMqtv2rXBt7Q4W9vGQMwPsS6yMzRwJVWVjdKxC8pIlnhlDckUbEQ7wxICf5xqKmeFUcbYmBz6Hwy0u1FlCRabU2vYEoFFrvuVsZmFMqRw8w0v1pb7m/uP0rxOFnSFXSL5DEN6xmQwIkJqBjlEiMQa0N+5pQEJ42K1FqQ3yyphronGJ1pydvW3Jzfzg5ar6e1wbdGbNY8jPtVV1W4STIa48xbEgcBQgG1S4MXidAaMhE2,iv:vaJMh9nK2Dn7ftVA1+aeghR3rhe60UJ5yyCLQQUEDoQ=,tag:wIBq+sECYXkQEm/8obx2mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNY05jZlhGWXRIY1NYZHhM
            LzFNdGtReUJCQmp3cFBMTE1JU29zVC9DcXlRClNLa1RzTmxhQk93UHFKVm9DakEr
            U010QWNIb05NUWtTLzdGSUNkZHY3SHMKLS0tIEFQSzZ1OUIwcHB4ZldzQUxmOXA2
            U05GNVJHek9PeXpCS3RYWTVXM21JOGsKeKoC7XX6K+83bRI4KxhcolnlaSfmPbxq
            4XwJAE+mSNd2ZfiqqDJuJ3mAskzwf/UdxJSi+lSZGCYVKZ0Emc+4Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T18:42:40Z"
    mac: ENC[AES256_GCM,data:FTEMKOs5I+gtpEx+fRWyJOliyKSND/oHKOCwLxQzE9fgScWWuEPGCcADEfw68RrHRyo7GnKO9RiLQ9S4xnSRdqOGVUBys8UNg8NKh7vvNmONkFXsiokJGbVIr0Fqm75iStQs2/ySDgAA7ebv5mmeKq8yvG6b3h1tLIPknC//jck=,iv:uV7/LMTqTTA8MG75DBo3pD7SAIHKwX6PZH6BDjM4reQ=,tag:WNDZO+JXhMxN0aBfl2rOAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
