apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: hass-mcp
    namespace: home
stringData:
    #ENC[AES256_GCM,data:KmBD5TyWng1O3cfJlWzZmsvczbiAdqvrYMBE2+mPr6Qyroi9Pmd6pmsJrVovd4OQi21CDFGaD0Aqr0h7JR1a01qoaLwoZZI=,iv:5IFRLKHjSAe2Whi4yuSxxAYjX/89w8nG5+2//YjVyKI=,tag:7RzV1PIG1IQPN9Co/bjoJA==,type:comment]
    #ENC[AES256_GCM,data:0/Y2nKYGSIhUxIjLw/J9DBblX4UIFSPSSZPYXts2fK/F/NtUqW2totG6fxj2isPjPYamQQ1LV9f+b5/+fIR4VWnJ,iv:Jd9tqZjVD3j4F2GPLji7uHlaBkEbghrm4Qths9K6iAY=,tag:NH4x+GBEvWUtvrdfYfjGUg==,type:comment]
    #ENC[AES256_GCM,data:xiAj4Zh2shJHPPIfoTeGyMKgu/UbRELZOd0SWjtfPp2Vh8yMz9CAnvT3aLdSnIQ4nRPV3ZTW9rXZS22dFvVahhFGPPfNPm8=,iv:BE5qVTQ5daXc7qMaQDCw6qOwHBATgBasK077t/JD9Mo=,tag:0NXUh1Hjqw/HWovdLHb22A==,type:comment]
    #ENC[AES256_GCM,data:JB0Q0a5e757SwEu89ddNTwRvjh8F+ed6rheRqxePhYgy2xJ6++H7T18AlZHz1NQAMX0zLYHiMAu5qSsTjJMplXH/DR+u,iv:7bKO8JOzCbtcoDVdZ6LX6y6aAvtQiSnoizR1gauIdi4=,tag:6e7lGdgiWO1rcdO/NwSQ9w==,type:comment]
    #ENC[AES256_GCM,data:OokpkLQtEbNPYuK3Sxq5JEDdLT43P2/cM+W9zwelnyfAfh4Rj2DsJiBKjVOCbGw4RFQdtzbpxWc=,iv:DOZBG2zrRw3H0RyHf1qieGfoUvUaaQULMsT3qzzAWkQ=,tag:ApdFTTZpbOp7tO9bqC9sJA==,type:comment]
    #ENC[AES256_GCM,data:b03yaFBAj2PXz2EzBqrctxkYTsPg6/6pgMnrdyJ1srJf8JSCoLgPTxeVRX6lSqENBY9tsKon4n9ozeA0dwroY/zU894eFebhfqx8RyA=,iv:ztBsyDwDUa7D2Iu3CtCqxanCGsfc3vipDJyYKLK10S4=,tag:hYEMVe6+pGveqkKWSRuNKg==,type:comment]
    #ENC[AES256_GCM,data:Icdh8ecCVz+FZ1g3snRAocHxW6KinzZcLmHBHhCk3Z1qWwIIE+ti2yMuWD2aDhZYZljK+rAFdxHSzAygzA==,iv:alPIqnVqrz0tdjqNEMIMDxaTTHvIYocmM9O5U1e6RKk=,tag:DPkxdMRoYVgknXtRsD3z+Q==,type:comment]
    #ENC[AES256_GCM,data:WapQ5FyMw9KpO8D+cB9W7sZyOEpVbDrNpTI0gp2tE+LxvBEG4oCPpxBO5Ql6F6gFeMuWPYj0kb6v9UcQHRUW,iv:NYfr/V5aWmDW1RcSIytm2cUD9vktKxaQ+AbGvEW3uPA=,tag:1f4PF+8OClvyGhKB6btllw==,type:comment]
    HA_TOKEN: ENC[AES256_GCM,data:/bjw+p9OJiw+qW7r6a8txZW6RPQ9EBwDcKZuVLPKAADR179xOBb9ehTkpYe43p6MHMnJ+yUrnTWjrnp87yty5YF00BIIducjclQoypbLju8PgfxMwaZ9oa7/qVY6km6LU7qXMZRGHKGnfrKyUkLP1IUJC8EDj4VnfCk4e0yx96diZ0yr7zEh0odCHtW319GTTrM5O4L01128wKl5cbgX6IuWr4WziAxzH5f8psKBC5wFogkbUs9I,iv:1lexzRnJler1Qi8sAMWLPvt7ViM3mtP7Zc0NNGdVAjg=,tag:U2aTqskECtlMYA/J/mXF4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRS8rcWF1am1sRkd5K3Uw
            RnpqOVJjeUxEbFBZMkxpWGN0UmZxOEtFUFRjCkc4bU81aTVac1o3YzdLU2NUWHZG
            UG1VWWVLT0F0TE8xTzh0cEZ5TXJBWG8KLS0tIGhCemFFY1k1WFFpS1hocjF4ODFD
            NzROYk0rcU9peEFWRUk2WGd6R0NlTEUKAmpgJBQZ+yxdcDhxLInB0fvRYjT/Yrnq
            Tc8piI4L2LdYlmgO2IaqRWke6Uz7zGvzpLP9FiBzB8DJcRhY8VBnPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T06:01:42Z"
    mac: ENC[AES256_GCM,data:2AIaaDSG13sGoW6jg3M4SU51VUY0ntBV+dCvJHq9Xvbo6usIbuAAFwLysSR7Srb0PJz3HM0PNXfkZHtu/JfmEX0DVt42UcXIuqBz9pI2ocDqJdNh0JdwLkFK7G9dVBVWqPXT/tFayoZOMnBIrS/wUZmC4W+9Ag7jwSwGKTROijU=,iv:Jda8GyURMv8YozpRRAsaqYaaPCxZlNcBkpjn1a6Av5o=,tag:A620zXoBTBIKJ2Q/nrrVgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
