apiVersion: v1
kind: Secret
metadata:
    name: f1replaytiming
    namespace: home
stringData:
    AUTH_PASSPHRASE: ENC[AES256_GCM,data:VOMmTraRC01a/F2y/pOT47JsUEXgHNZZ0eqIZYRl3hc5xeIs/X/oDyPhMRk=,iv:6jKIueef0mrxPyBYNHVcc+70mlRZs/1+pXOwwzVyBTY=,tag:HZNZmdIqY0GRSu0aqT8NyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYzN1bllsU1Fzek41VFFT
            Lyt0NE90K2pIbDZMdUZ5cHNSSGN4cFhjVERzCk9tYmhIby9aanlQemZOVVhycjh1
            OGYyRkg4ak11MHFWN3c1dGFzVWJsdFUKLS0tIFlZYnB1MlN4TEx5cXhMTklyc1ND
            cXgwYklSdGxnLy9EcDhKR0I1T0x6aUEKZqnk8WZUBEzq8OVRuBkm4DVm52lI9e/i
            9vMt6hszfS4+Rh7pjxHKlOe/IW2Poh+ie58czUBkjYZfWjhEcp51+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T06:42:46Z"
    mac: ENC[AES256_GCM,data:7yQaZ33MovlTZ5IN/zbbA6plXMbMpWfvLYCy5o0WNoyRjjPW7APiu3FAgRgjEw2pzqmEg/IYvBEFsvYbLt4/rYT06+jk/zsY3ehhtEjSFQJ6IekES0MPF9L/UEjjQKKVUncV5+P+g4TcqJsjHLzcB5plY/waDzu9esRaxtoZQK4=,iv:Owz0APoyiTLyOhQVm/7lYPwFtsuyOQLZy2LxQLCN12c=,tag:fm6WvfLBQLsf85OFybjxGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
