apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: immich
    namespace: media
stringData:
    DB_HOSTNAME: ENC[AES256_GCM,data:1dLJCYz1jRplOgjy7KribASyTNECpwV/eaHya/m50EcG3HPjww4Fvg==,iv:hL/ZPpjstU8bhcB3Saq/9JcgaYbtYOF+U9xCGV49iUw=,tag:Ld0tUvYhqJs4dWBQmCAOmA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:sCVGLA==,iv:2IRykGgVsj2mpfi8TIjc76xxkqwKQ6GmYyK97XccxMg=,tag:zNsI1qGh71msJ21p33OCtA==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:n+zh5vHP,iv:5VjdrY8vAIxVDDhGntI4GXIVtfpDyz23OsgxEKgPuHQ=,tag:q676MOVg/Jj9W4Hyqvo01g==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:5jWPmFHY,iv:OX+RYWcz/Ct8HX0FwSTHZN7FoQQaWgL8KMNnvcwnudQ=,tag:N1CgUUMfXoUXo5sGiOnFEg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:4SwEi+XhmTrm77EfOTJxteaw5toztKc=,iv:yQoGqp7f7SkNAL3LSPWeBWRTQA9HfUoxKfimHqha9JQ=,tag:EV10J7kTqr56DXTidmpSiQ==,type:str]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:rTG+T+E7BaFEwvPeFW5b9rudCN3c/yywV3rO10JFtZ44LSqk,iv:M2so11LlAM2ESqb7vn0yccfepCshGdVyTwucPgRFXHk=,tag:N8nymcf76YeqPfBjtwTwdg==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:yGtpbw==,iv:/77+Dzp0yN86+ybJhYvfR39DcT0hAl7g+ZTZBvfon78=,tag:lFt6pMnmmcpJP9lS1r+Lvw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:MuT11A1xZm8ZhnPyQmyaN/uErSbOw+jCHD92BZiDAy+IHQjO,iv:gpvRehtut8DLvMfUmh7qJZ8n1NFD9MOLHcMq2Yd6BrM=,tag:uM+ofgu8S3OqpgtWECEvAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSzk5Z1c0NUg1dXhHUVVt
            TmE0eXlJWnNxai90Zmk0NytUNi9RMUFmZVNJClIrdXJuRmdWdDdiaGlwbDRxbVg5
            bGVyNy9LaE4wcmJFTVdDMVBIc2k5SncKLS0tIDJDMEpJUDBldytJSzF6VEhydTh3
            b1R6YmRDb0RZbjRCZGdoRHJqRGhMSFUKHcxrygA5PgUq/x6Ng1qoXPEk5qjLTNMR
            dWxFF4pzQlv7Gpd5abNJqkUr5aayGW04zbYQB5ngZODQR2hb02I45A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T07:42:39Z"
    mac: ENC[AES256_GCM,data:uw0eCDk0Rxj/CbA/3mdpshE9g4PJ4aXEu/ys60EhUqbMDwsr7NTB0lpEbtEi26b214sGc3vmw8iPw1icoHd8KA/S3C9e17cSCvqxYBlyadSLT7bshSO/lhl8SBbvKGGDqZ2JeRFqnPIh8+5lTAe46ZsCJiBY82a1r6Q53NrpP10=,iv:SRVaRuRDgS0Z6IGlrIFcKaRfzszCCUzYtD8qqrZwmzI=,tag:cW446VV330MX91/QYVeulQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
