apiVersion: v1
kind: Secret
metadata:
    name: opengist
    namespace: home
stringData:
    OG_OIDC_SECRET: ENC[AES256_GCM,data:pqwpZQnTnHvNoLguaBwHtvWFvSEzhmoUp4zii+rtgEnqPQ7UNfePKkNEreXg3wZsacBojU3thAVvQQN41Yw0oWS4AfabC3jr,iv:LZjGTGD0ggsAbkLRGHAO7clPFhf1k6Bjwys9/Xz4b10=,tag:dC3PHupYhnn9aah7zQAVbQ==,type:str]
    OG_SECRET_KEY: ENC[AES256_GCM,data:ip80HZ+0VFTz/buyY7DFGKqy+s82NrVF5g62MSb3wN9jXoN9I9/BEqnZohLr/o+Y9h4+mrpFZGPGmgHu4i1Baw==,iv:xY5Vx+HD0T+uEqb5WO4jPFITERhv6/NjZuW/7KzMe3s=,tag:o7W7k9YD5TkK1poTbCU7Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dDYyTk5SbkhDM1A1dUQz
            Zmt6cGFDY3Uxc1VsTTBZczZSUGV0VGtkT2g0CmxxcUdlVnNNWG80RjJSSEtNNGY2
            a2tlK0w1bExERjh2YjBMS0VIMjZSYWcKLS0tIEFKUzJJQTVWcWJDNk05UkNNTjhj
            dW9MQTJ5WTdKbS9rbDcyK0tzL3M0dEUK8Eg9mZwqgEKAHifnpFD4Kw4iNE+N/Deh
            PHrbJhbiIthuDIhyfwsGd9V/KOpTOWZ3WXI7x8+DFCg5a7gYnvEZjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T08:14:35Z"
    mac: ENC[AES256_GCM,data:mVc1EtlUrO8/BDdKeASCMo0+fywzwqFTS/1HTG6ZVfhDAXoclhOJ14UYHrtWmF1+CRn3AKzcxXu3tYi62Mk+uzKOSmvCLuv+3YerhJlY1l9KghlJEWYO38lj5DCdWOolQIqhESIZL7e7xRqghikkXmgFUfgIyBBbDgoLK1v6nc4=,iv:GETL9dW6If9ui7ynWokxx0rdLnOAu5c5xaVL/ix1GBw=,tag:2XLv3ggQ5gp4ghBuDLkX4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
