apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
commonLabels:
  app.kubernetes.io/name: &app linkwarden
  app.kubernetes.io/instance: *app
resources:
  - pvc-storage.yaml
  - helm-release.yaml
  - secret.sops.yaml
