apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
  - name: "instance-64512"
    localASN: 64512
    peers:
    - name: "peer-64513"
      peerASN: 64513
      peerAddress: 192.168.0.6
