#---
#apiVersion: cilium.io/v2alpha1
#kind: CiliumBGPClusterConfig
#metadata:
#  name: cilium-bgp
#spec:
#  nodeSelector:
#    matchLabels:
#      kubernetes.io/os: linux
#  bgpInstances:
#  - name: "instance-64512"
#    localASN: 64512
#    peers:
#    - name: "peer-64513"
#      peerASN: 64513
#      peerAddress: 192.168.0.6
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumbgppeeringpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: l3-policy
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    - localASN: 64512
      exportPodCIDR: false
      serviceSelector:
        matchExpressions:
          - key: thisFakeSelector
            operator: NotIn
            values:
              - will-match-and-announce-all-services
      neighbors:
        - peerAddress: 192.168.0.6/32
          peerASN: 64513
