---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
